/*
###############################################################
#  Generated by:      Cadence Innovus 23.31-s109_1
#  OS:                Linux x86_64(Host ID ei-vm-018.othr.de)
#  Generated on:      Fri Aug  8 17:32:59 2025
#  Design:            Main
#  Command:           saveNetlist pnr_outputs/post_layout_main.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Aug  7 2025 21:21:25 CEST (Aug  7 2025 19:21:25 UTC)
// Verification Directory fv/Main 
module ActivationMultiplier_6_IN_WIDTH8_NUM_UNITS6_ACTIVATION_WIDTH8 (
	\activation[0] , 
	\activation[1] , 
	\activation[2] , 
	\activation[3] , 
	\activation[4] , 
	\activation[5] , 
	\weight[0] , 
	\weight[1] , 
	\weight[2] , 
	\weight[3] , 
	\weight[4] , 
	\weight[5] , 
	clk, 
	rst, 
	start, 
	\result[0] , 
	\result[1] , 
	\result[2] , 
	\result[3] , 
	\result[4] , 
	\result[5] , 
	en, 
	\DFT_/sdi , 
	\DFT_/sen , 
	n_0, 
	SPCASCAN_N1, 
	p_1, 
	SPCASCAN_N2, 
	SPCASCAN_N3, 
	n_3, 
	SPCASCAN_N5);
   input [7:0] \activation[0] ;
   input [7:0] \activation[1] ;
   input [7:0] \activation[2] ;
   input [7:0] \activation[3] ;
   input [7:0] \activation[4] ;
   input [7:0] \activation[5] ;
   input [7:0] \weight[0] ;
   input [7:0] \weight[1] ;
   input [7:0] \weight[2] ;
   input [7:0] \weight[3] ;
   input [7:0] \weight[4] ;
   input [7:0] \weight[5] ;
   input clk;
   input rst;
   input start;
   output [7:0] \result[0] ;
   output [7:0] \result[1] ;
   output [7:0] \result[2] ;
   output [7:0] \result[3] ;
   output [7:0] \result[4] ;
   output [7:0] \result[5] ;
   output en;
   input \DFT_/sdi ;
   input \DFT_/sen ;
   output n_0;
   input SPCASCAN_N1;
   input p_1;
   input SPCASCAN_N2;
   input SPCASCAN_N3;
   output n_3;
   input SPCASCAN_N5;

   // Internal wires
   wire FE_OFN5_n_180;
   wire FE_OFN1_scan_en;
   wire FE_DBTN0_n_54;
   wire [7:0] \am_result[0] ;
   wire [7:0] \am_result[1] ;
   wire [7:0] \am_result[2] ;
   wire [7:0] \am_result[3] ;
   wire [7:0] \am_result[4] ;
   wire [7:0] \am_result[5] ;
   wire [7:0] \activation_reg[4] ;
   wire [7:0] \activation_reg[1] ;
   wire [7:0] \activation_reg[3] ;
   wire [7:0] \activation_reg[5] ;
   wire [7:0] \activation_reg[0] ;
   wire [7:0] \activation_reg[2] ;
   wire [3:0] cycle_counter;
   wire n_1;
   wire n_2;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;

   assign \result[5] [5] = 1'b0 ;
   assign \result[5] [6] = 1'b0 ;
   assign \result[5] [7] = 1'b0 ;
   assign \result[4] [5] = 1'b0 ;
   assign \result[4] [6] = 1'b0 ;
   assign \result[4] [7] = 1'b0 ;
   assign \result[3] [5] = 1'b0 ;
   assign \result[3] [6] = 1'b0 ;
   assign \result[3] [7] = 1'b0 ;
   assign \result[2] [5] = 1'b0 ;
   assign \result[2] [6] = 1'b0 ;
   assign \result[2] [7] = 1'b0 ;
   assign \result[1] [5] = 1'b0 ;
   assign \result[1] [6] = 1'b0 ;
   assign \result[1] [7] = 1'b0 ;
   assign \result[0] [5] = 1'b0 ;
   assign \result[0] [6] = 1'b0 ;
   assign \result[0] [7] = 1'b0 ;

   BUJIX1 FE_OFC4_n_180 (.Q(FE_OFN5_n_180),
	.A(n_180));
   BUJIX1 FE_OFC0_scan_en (.Q(FE_OFN1_scan_en),
	.A(\DFT_/sen ));
   NA3I1JIX0 FE_RC_0_0 (.Q(n_135),
	.AN(n_190),
	.B(cycle_counter[3]),
	.C(cycle_counter[0]));
   INVJIX1 FE_DBTC0_n_54 (.Q(FE_DBTN0_n_54),
	.A(n_54));
   ActivationMultiplier_IN_WIDTH8 \AM_INST[0].am  (.weight(\weight[0] ),
	.activation(n_184),
	.en(en),
	.result(\am_result[0] ));
   ActivationMultiplier_IN_WIDTH8 \AM_INST[1].am  (.weight(\weight[1] ),
	.activation(n_188),
	.en(en),
	.result(\am_result[1] ));
   ActivationMultiplier_IN_WIDTH8 \AM_INST[2].am  (.weight(\weight[2] ),
	.activation(n_187),
	.en(en),
	.result(\am_result[2] ));
   ActivationMultiplier_IN_WIDTH8 \AM_INST[3].am  (.weight(\weight[3] ),
	.activation(n_186),
	.en(en),
	.result(\am_result[3] ));
   ActivationMultiplier_IN_WIDTH8 \AM_INST[4].am  (.weight(\weight[4] ),
	.activation(n_185),
	.en(en),
	.result(\am_result[4] ));
   ActivationMultiplier_IN_WIDTH8 \AM_INST[5].am  (.weight(\weight[5] ),
	.activation(n_189),
	.en(en),
	.result(\am_result[5] ));
   INVJIX1 g2406 (.Q(n_180),
	.A(rst));
   NA4JIX0 g3309__2398 (.Q(n_184),
	.A(n_169),
	.B(n_171),
	.C(n_165),
	.D(n_160));
   NA4JIX0 g3310__5107 (.Q(n_185),
	.A(n_167),
	.B(n_163),
	.C(n_179),
	.D(n_157));
   NA4JIX0 g3311__6260 (.Q(n_186),
	.A(n_172),
	.B(n_175),
	.C(n_177),
	.D(n_159));
   NA4JIX0 g3312__4319 (.Q(n_189),
	.A(n_173),
	.B(n_176),
	.C(n_174),
	.D(n_161));
   NA4JIX0 g3313__8428 (.Q(n_187),
	.A(n_168),
	.B(n_162),
	.C(n_166),
	.D(n_158));
   NA4JIX0 g3314__5526 (.Q(n_188),
	.A(n_164),
	.B(n_178),
	.C(n_170),
	.D(n_156));
   AN22JIX0 g3315__6783 (.Q(n_179),
	.A(n_151),
	.B(\activation_reg[4] [1]),
	.C(n_147),
	.D(\activation_reg[4] [0]));
   AN22JIX0 g3316__3680 (.Q(n_178),
	.A(n_152),
	.B(\activation_reg[1] [7]),
	.C(n_155),
	.D(\activation_reg[1] [3]));
   AN22JIX0 g3317__1617 (.Q(n_177),
	.A(n_151),
	.B(\activation_reg[3] [1]),
	.C(n_147),
	.D(\activation_reg[3] [0]));
   AN22JIX0 g3318__2802 (.Q(n_176),
	.A(n_152),
	.B(\activation_reg[5] [7]),
	.C(n_155),
	.D(\activation_reg[5] [3]));
   AN22JIX0 g3319__1705 (.Q(n_175),
	.A(n_152),
	.B(\activation_reg[3] [7]),
	.C(n_155),
	.D(\activation_reg[3] [3]));
   AN22JIX0 g3320__5122 (.Q(n_174),
	.A(n_151),
	.B(\activation_reg[5] [1]),
	.C(n_147),
	.D(\activation_reg[5] [0]));
   AN22JIX0 g3321__8246 (.Q(n_173),
	.A(n_153),
	.B(\activation_reg[5] [6]),
	.C(n_154),
	.D(\activation_reg[5] [2]));
   AN22JIX0 g3322__7098 (.Q(n_172),
	.A(n_153),
	.B(\activation_reg[3] [6]),
	.C(n_154),
	.D(\activation_reg[3] [2]));
   AN22JIX0 g3323__6131 (.Q(n_171),
	.A(n_152),
	.B(\activation_reg[0] [7]),
	.C(n_155),
	.D(\activation_reg[0] [3]));
   AN22JIX0 g3324__1881 (.Q(n_170),
	.A(n_151),
	.B(\activation_reg[1] [1]),
	.C(n_147),
	.D(\activation_reg[1] [0]));
   AN22JIX0 g3325__5115 (.Q(n_169),
	.A(n_153),
	.B(\activation_reg[0] [6]),
	.C(n_154),
	.D(\activation_reg[0] [2]));
   AN22JIX0 g3326__7482 (.Q(n_168),
	.A(n_153),
	.B(\activation_reg[2] [6]),
	.C(n_154),
	.D(\activation_reg[2] [2]));
   AN22JIX0 g3327__4733 (.Q(n_167),
	.A(n_153),
	.B(\activation_reg[4] [6]),
	.C(n_154),
	.D(\activation_reg[4] [2]));
   AN22JIX0 g3328__6161 (.Q(n_166),
	.A(n_151),
	.B(\activation_reg[2] [1]),
	.C(n_147),
	.D(\activation_reg[2] [0]));
   AN22JIX0 g3329__9315 (.Q(n_165),
	.A(n_151),
	.B(\activation_reg[0] [1]),
	.C(n_147),
	.D(\activation_reg[0] [0]));
   AN22JIX0 g3330__9945 (.Q(n_164),
	.A(n_153),
	.B(\activation_reg[1] [6]),
	.C(n_154),
	.D(\activation_reg[1] [2]));
   AN22JIX0 g3331__2883 (.Q(n_163),
	.A(n_152),
	.B(\activation_reg[4] [7]),
	.C(n_155),
	.D(\activation_reg[4] [3]));
   AN22JIX0 g3332__2346 (.Q(n_162),
	.A(n_152),
	.B(\activation_reg[2] [7]),
	.C(n_155),
	.D(\activation_reg[2] [3]));
   AN22JIX0 g3333__1666 (.Q(n_161),
	.A(n_149),
	.B(\activation_reg[5] [5]),
	.C(n_146),
	.D(\activation_reg[5] [4]));
   AN22JIX0 g3334__7410 (.Q(n_160),
	.A(n_149),
	.B(\activation_reg[0] [5]),
	.C(n_146),
	.D(\activation_reg[0] [4]));
   AN22JIX0 g3335__6417 (.Q(n_159),
	.A(n_149),
	.B(\activation_reg[3] [5]),
	.C(n_146),
	.D(\activation_reg[3] [4]));
   AN22JIX0 g3336__5477 (.Q(n_158),
	.A(n_149),
	.B(\activation_reg[2] [5]),
	.C(n_146),
	.D(\activation_reg[2] [4]));
   AN22JIX0 g3337__2398 (.Q(n_157),
	.A(n_149),
	.B(\activation_reg[4] [5]),
	.C(n_146),
	.D(\activation_reg[4] [4]));
   AN22JIX0 g3338__5107 (.Q(n_156),
	.A(n_149),
	.B(\activation_reg[1] [5]),
	.C(n_146),
	.D(\activation_reg[1] [4]));
   AND2JIX0 g3339__6260 (.Q(n_155),
	.A(n_150),
	.B(cycle_counter[2]));
   AND2JIX0 g3340__4319 (.Q(n_154),
	.A(n_148),
	.B(cycle_counter[2]));
   NO2I1JIX0 g3341__8428 (.Q(n_153),
	.AN(n_148),
	.B(cycle_counter[2]));
   NO2I1JIX0 g3342__5526 (.Q(n_152),
	.AN(n_150),
	.B(cycle_counter[2]));
   AND3JIX0 g3343__6783 (.Q(n_151),
	.A(n_144),
	.B(cycle_counter[2]),
	.C(cycle_counter[1]));
   NO2I1JIX0 g3344__3680 (.Q(n_150),
	.AN(n_144),
	.B(cycle_counter[1]));
   NO2I1JIX0 g3345__1617 (.Q(n_149),
	.AN(n_144),
	.B(n_190));
   INVJIX0 g3346 (.Q(n_147),
	.A(n_192));
   INVJIX0 g3347 (.Q(n_191),
	.A(n_146));
   NO2JIX0 g3348__2802 (.Q(n_148),
	.A(n_145),
	.B(cycle_counter[1]));
   NO2JIX0 g3350__1705 (.Q(n_146),
	.A(n_145),
	.B(n_190));
   NA2I1JIX0 g3352__5122 (.Q(n_145),
	.AN(cycle_counter[3]),
	.B(cycle_counter[0]));
   NO2JIX0 g3353__8246 (.Q(n_144),
	.A(cycle_counter[3]),
	.B(cycle_counter[0]));
   NA2I1JIX0 g3354__7098 (.Q(n_190),
	.AN(cycle_counter[2]),
	.B(cycle_counter[1]));
   NA3I1JIX0 g2__6131 (.Q(n_192),
	.AN(n_145),
	.B(cycle_counter[1]),
	.C(cycle_counter[2]));
   SDFRRQJIX1 \activation_reg_reg[0][0]  (.Q(\activation_reg[0] [0]),
	.C(clk),
	.D(n_104),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[1] [2]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[0][1]  (.Q(\activation_reg[0] [1]),
	.C(clk),
	.D(n_109),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[0] [5]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[0][2]  (.Q(\activation_reg[0] [2]),
	.C(clk),
	.D(n_107),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[0] [3]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[0][3]  (.Q(\activation_reg[0] [3]),
	.C(clk),
	.D(n_106),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[0] [4]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[0][4]  (.Q(\activation_reg[0] [4]),
	.C(clk),
	.D(n_105),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[0] [1]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[0][5]  (.Q(\activation_reg[0] [5]),
	.C(clk),
	.D(n_103),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[1] [0]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[0][6]  (.Q(\activation_reg[0] [6]),
	.C(clk),
	.D(n_100),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[0] [2]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[0][7]  (.Q(\activation_reg[0] [7]),
	.C(clk),
	.D(n_102),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[0] [6]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[1][0]  (.Q(\activation_reg[1] [0]),
	.C(clk),
	.D(n_101),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[1] [1]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[1][1]  (.Q(\activation_reg[1] [1]),
	.C(clk),
	.D(n_99),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[0] [0]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[1][2]  (.Q(\activation_reg[1] [2]),
	.C(clk),
	.D(n_98),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[1] [3]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[1][3]  (.Q(\activation_reg[1] [3]),
	.C(clk),
	.D(n_97),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[1] [5]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[1][4]  (.Q(\activation_reg[1] [4]),
	.C(clk),
	.D(n_96),
	.RN(FE_OFN5_n_180),
	.SD(n_13),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[1][5]  (.Q(\activation_reg[1] [5]),
	.C(clk),
	.D(n_95),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[1] [7]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[1][6]  (.Q(\activation_reg[1] [6]),
	.C(clk),
	.D(n_94),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[1] [4]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[1][7]  (.Q(\activation_reg[1] [7]),
	.C(clk),
	.D(n_93),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[2] [2]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[2][0]  (.Q(\activation_reg[2] [0]),
	.C(clk),
	.D(n_92),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[1] [6]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[2][1]  (.Q(\activation_reg[2] [1]),
	.C(clk),
	.D(n_91),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[2] [0]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[2][2]  (.Q(\activation_reg[2] [2]),
	.C(clk),
	.D(n_90),
	.RN(FE_OFN5_n_180),
	.SD(n_16),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[2][3]  (.Q(\activation_reg[2] [3]),
	.C(clk),
	.D(n_89),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[3] [0]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[2][4]  (.Q(\activation_reg[2] [4]),
	.C(clk),
	.D(n_88),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[2] [1]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[2][5]  (.Q(\activation_reg[2] [5]),
	.C(clk),
	.D(n_87),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[2] [4]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[2][6]  (.Q(\activation_reg[2] [6]),
	.C(clk),
	.D(n_132),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[2] [3]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[2][7]  (.Q(\activation_reg[2] [7]),
	.C(clk),
	.D(n_134),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[2] [5]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[3][0]  (.Q(\activation_reg[3] [0]),
	.C(clk),
	.D(n_133),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[2] [7]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[3][1]  (.Q(\activation_reg[3] [1]),
	.C(clk),
	.D(n_131),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[3] [4]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[3][2]  (.Q(\activation_reg[3] [2]),
	.C(clk),
	.D(n_130),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[3] [1]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[3][3]  (.Q(\activation_reg[3] [3]),
	.C(clk),
	.D(n_129),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[3] [6]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[3][4]  (.Q(\activation_reg[3] [4]),
	.C(clk),
	.D(n_136),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[3] [5]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \activation_reg_reg[3][5]  (.Q(\activation_reg[3] [5]),
	.C(clk),
	.D(n_127),
	.RN(FE_OFN5_n_180),
	.SD(\DFT_/sdi ),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[3][6]  (.Q(\activation_reg[3] [6]),
	.C(clk),
	.D(n_126),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[3] [2]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[3][7]  (.Q(\activation_reg[3] [7]),
	.C(clk),
	.D(n_125),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[4] [1]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[4][0]  (.Q(\activation_reg[4] [0]),
	.C(clk),
	.D(n_124),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[3] [7]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[4][1]  (.Q(\activation_reg[4] [1]),
	.C(clk),
	.D(n_123),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[3] [3]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[4][2]  (.Q(\activation_reg[4] [2]),
	.C(clk),
	.D(n_122),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[4] [7]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[4][3]  (.Q(\activation_reg[4] [3]),
	.C(clk),
	.D(n_121),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[4] [6]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[4][4]  (.Q(\activation_reg[4] [4]),
	.C(clk),
	.D(n_120),
	.RN(FE_OFN5_n_180),
	.SD(cycle_counter[1]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[4][5]  (.Q(\activation_reg[4] [5]),
	.C(clk),
	.D(n_119),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[4] [4]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[4][6]  (.Q(\activation_reg[4] [6]),
	.C(clk),
	.D(n_118),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[4] [2]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[4][7]  (.Q(\activation_reg[4] [7]),
	.C(clk),
	.D(n_117),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[4] [5]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[5][0]  (.Q(\activation_reg[5] [0]),
	.C(clk),
	.D(n_116),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[5] [1]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[5][1]  (.Q(\activation_reg[5] [1]),
	.C(clk),
	.D(n_115),
	.RN(FE_OFN5_n_180),
	.SD(n_8),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[5][2]  (.Q(\activation_reg[5] [2]),
	.C(clk),
	.D(n_114),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[5] [0]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[5][3]  (.Q(\activation_reg[5] [3]),
	.C(clk),
	.D(n_113),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[5] [2]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[5][4]  (.Q(\activation_reg[5] [4]),
	.C(clk),
	.D(n_112),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[5] [5]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[5][5]  (.Q(\activation_reg[5] [5]),
	.C(clk),
	.D(n_111),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[5] [6]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[5][6]  (.Q(\activation_reg[5] [6]),
	.C(clk),
	.D(n_110),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[5] [7]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \activation_reg_reg[5][7]  (.Q(\activation_reg[5] [7]),
	.C(clk),
	.D(n_108),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[5] [3]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \cycle_counter_reg[0]  (.Q(cycle_counter[0]),
	.C(clk),
	.D(n_128),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[4] [0]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \cycle_counter_reg[1]  (.Q(cycle_counter[1]),
	.C(clk),
	.D(n_140),
	.RN(FE_OFN5_n_180),
	.SD(cycle_counter[0]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \cycle_counter_reg[2]  (.Q(cycle_counter[2]),
	.C(clk),
	.D(n_142),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[2] [6]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \cycle_counter_reg[3]  (.Q(cycle_counter[3]),
	.C(clk),
	.D(n_141),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[4] [3]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 en_reg (.Q(en),
	.C(clk),
	.D(n_143),
	.RN(FE_OFN5_n_180),
	.SD(cycle_counter[2]),
	.SE(FE_OFN1_scan_en));
   SDFRRSJIX1 \result_reg[0][0]  (.Q(\result[0] [0]),
	.QN(n_17),
	.C(clk),
	.D(n_75),
	.RN(FE_OFN5_n_180),
	.SD(cycle_counter[3]),
	.SE(FE_OFN1_scan_en),
	.SN(1'b1));
   SDFRRSJIX1 \result_reg[0][1]  (.Q(\result[0] [1]),
	.QN(n_16),
	.C(clk),
	.D(n_74),
	.RN(FE_OFN5_n_180),
	.SD(en),
	.SE(FE_OFN1_scan_en),
	.SN(1'b1));
   SDFRRSJIX1 \result_reg[0][2]  (.Q(\result[0] [2]),
	.QN(n_15),
	.C(clk),
	.D(n_79),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[0] [7]),
	.SE(FE_OFN1_scan_en),
	.SN(1'b1));
   SDFRRQJIX1 \result_reg[0][3]  (.Q(\result[0] [3]),
	.C(clk),
	.D(n_73),
	.RN(FE_OFN5_n_180),
	.SD(n_15),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \result_reg[0][4]  (.Q(\result[0] [4]),
	.C(clk),
	.D(n_72),
	.RN(FE_OFN5_n_180),
	.SD(\result[1] [4]),
	.SE(FE_OFN1_scan_en));
   SDFRRSJIX1 \result_reg[1][0]  (.Q(\result[1] [0]),
	.QN(n_14),
	.C(clk),
	.D(n_78),
	.RN(FE_OFN5_n_180),
	.SD(n_17),
	.SE(FE_OFN1_scan_en),
	.SN(1'b1));
   SDFRRSJIX1 \result_reg[1][1]  (.Q(\result[1] [1]),
	.QN(n_13),
	.C(clk),
	.D(n_56),
	.RN(FE_OFN5_n_180),
	.SD(n_9),
	.SE(FE_OFN1_scan_en),
	.SN(1'b1));
   SDFRRSJIX1 \result_reg[1][2]  (.Q(\result[1] [2]),
	.QN(n_12),
	.C(clk),
	.D(n_70),
	.RN(FE_OFN5_n_180),
	.SD(n_10),
	.SE(FE_OFN1_scan_en),
	.SN(1'b1));
   SDFRRQJIX1 \result_reg[1][3]  (.Q(\result[1] [3]),
	.C(clk),
	.D(n_64),
	.RN(FE_OFN5_n_180),
	.SD(\result[0] [3]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \result_reg[1][4]  (.Q(\result[1] [4]),
	.C(clk),
	.D(n_69),
	.RN(FE_OFN5_n_180),
	.SD(\result[3] [3]),
	.SE(FE_OFN1_scan_en));
   SDFRRSJIX1 \result_reg[2][0]  (.Q(\result[2] [0]),
	.QN(n_11),
	.C(clk),
	.D(n_57),
	.RN(FE_OFN5_n_180),
	.SD(n_14),
	.SE(\DFT_/sen ),
	.SN(1'b1));
   SDFRRSJIX1 \result_reg[2][1]  (.Q(\result[2] [1]),
	.QN(n_10),
	.C(clk),
	.D(n_67),
	.RN(FE_OFN5_n_180),
	.SD(n_7),
	.SE(FE_OFN1_scan_en),
	.SN(1'b1));
   SDFRRSJIX1 \result_reg[2][2]  (.Q(\result[2] [2]),
	.QN(n_9),
	.C(clk),
	.D(n_66),
	.RN(FE_OFN5_n_180),
	.SD(n_6),
	.SE(FE_OFN1_scan_en),
	.SN(1'b1));
   SDFRRQJIX1 \result_reg[2][3]  (.Q(\result[2] [3]),
	.C(clk),
	.D(n_65),
	.RN(FE_OFN5_n_180),
	.SD(\result[1] [3]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \result_reg[2][4]  (.Q(\result[2] [4]),
	.C(clk),
	.D(n_68),
	.RN(FE_OFN5_n_180),
	.SD(\result[0] [4]),
	.SE(FE_OFN1_scan_en));
   SDFRRSJIX1 \result_reg[3][0]  (.Q(\result[3] [0]),
	.QN(n_8),
	.C(clk),
	.D(n_63),
	.RN(FE_OFN5_n_180),
	.SD(n_11),
	.SE(\DFT_/sen ),
	.SN(1'b1));
   SDFRRSJIX1 \result_reg[3][1]  (.Q(\result[3] [1]),
	.QN(n_7),
	.C(clk),
	.D(n_61),
	.RN(FE_OFN5_n_180),
	.SD(p_1),
	.SE(FE_OFN1_scan_en),
	.SN(1'b1));
   SDFRRSJIX1 \result_reg[3][2]  (.Q(\result[3] [2]),
	.QN(n_6),
	.C(clk),
	.D(n_59),
	.RN(FE_OFN5_n_180),
	.SD(n_12),
	.SE(FE_OFN1_scan_en),
	.SN(1'b1));
   SDFRRQJIX1 \result_reg[3][3]  (.Q(\result[3] [3]),
	.C(clk),
	.D(n_62),
	.RN(FE_OFN5_n_180),
	.SD(\result[2] [3]),
	.SE(FE_OFN1_scan_en));
   SDFRRQJIX1 \result_reg[3][4]  (.Q(\result[3] [4]),
	.C(clk),
	.D(n_60),
	.RN(FE_OFN5_n_180),
	.SD(\result[2] [4]),
	.SE(FE_OFN1_scan_en));
   SDFRRSJIX1 \result_reg[4][0]  (.Q(\result[4] [0]),
	.QN(n_5),
	.C(clk),
	.D(n_80),
	.RN(FE_OFN5_n_180),
	.SD(n_2),
	.SE(\DFT_/sen ),
	.SN(1'b1));
   SDFRRSJIX1 \result_reg[4][1]  (.Q(\result[4] [1]),
	.QN(n_4),
	.C(clk),
	.D(n_85),
	.RN(n_180),
	.SD(n_1),
	.SE(\DFT_/sen ),
	.SN(1'b1));
   SDFRRSJIX1 \result_reg[4][2]  (.Q(\result[4] [2]),
	.QN(n_3),
	.C(clk),
	.D(n_77),
	.RN(n_180),
	.SD(n_4),
	.SE(\DFT_/sen ),
	.SN(1'b1));
   SDFRRQJIX1 \result_reg[4][3]  (.Q(\result[4] [3]),
	.C(clk),
	.D(n_58),
	.RN(n_180),
	.SD(\result[5] [3]),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \result_reg[4][4]  (.Q(\result[4] [4]),
	.C(clk),
	.D(n_81),
	.RN(n_180),
	.SD(\result[4] [3]),
	.SE(\DFT_/sen ));
   SDFRRSJIX1 \result_reg[5][0]  (.Q(\result[5] [0]),
	.QN(n_2),
	.C(clk),
	.D(n_83),
	.RN(FE_OFN5_n_180),
	.SD(\activation_reg[5] [4]),
	.SE(\DFT_/sen ),
	.SN(1'b1));
   SDFRRSJIX1 \result_reg[5][1]  (.Q(\result[5] [1]),
	.QN(n_1),
	.C(clk),
	.D(n_82),
	.RN(n_180),
	.SD(n_5),
	.SE(\DFT_/sen ),
	.SN(1'b1));
   SDFRRSJIX1 \result_reg[5][2]  (.Q(\result[5] [2]),
	.QN(n_0),
	.C(clk),
	.D(n_71),
	.RN(n_180),
	.SD(SPCASCAN_N5),
	.SE(\DFT_/sen ),
	.SN(1'b1));
   SDFRRQJIX1 \result_reg[5][3]  (.Q(\result[5] [3]),
	.C(clk),
	.D(n_84),
	.RN(n_180),
	.SD(n_0),
	.SE(\DFT_/sen ));
   SDFRRQJIX1 \result_reg[5][4]  (.Q(\result[5] [4]),
	.C(clk),
	.D(n_76),
	.RN(n_180),
	.SD(\result[4] [4]),
	.SE(\DFT_/sen ));
   AO21JIX0 g3409__1881 (.Q(n_143),
	.A(n_135),
	.B(en),
	.C(n_54));
   ON21JIX0 g3411__5115 (.Q(n_142),
	.A(n_191),
	.B(n_47),
	.C(n_139));
   ON21JIX0 g3412__7482 (.Q(n_141),
	.A(n_192),
	.B(n_47),
	.C(n_138));
   AO32JIX0 g3439__4733 (.Q(n_140),
	.A(en),
	.B(cycle_counter[0]),
	.C(n_49),
	.D(cycle_counter[1]),
	.E(n_86));
   NA2JIX0 g3440__6161 (.Q(n_139),
	.A(n_137),
	.B(cycle_counter[2]));
   NA2JIX0 g3441__9315 (.Q(n_138),
	.A(n_137),
	.B(cycle_counter[3]));
   AO22JIX0 g3465__9945 (.Q(n_136),
	.A(n_54),
	.B(\activation[3] [4]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[3] [4]));
   AO22JIX0 g3467__2346 (.Q(n_134),
	.A(n_54),
	.B(\activation[2] [7]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[2] [7]));
   AO22JIX0 g3468__1666 (.Q(n_133),
	.A(n_54),
	.B(\activation[3] [0]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[3] [0]));
   AO22JIX0 g3469__7410 (.Q(n_132),
	.A(n_54),
	.B(\activation[2] [6]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[2] [6]));
   AO22JIX0 g3470__6417 (.Q(n_131),
	.A(n_54),
	.B(\activation[3] [1]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[3] [1]));
   AO22JIX0 g3471__5477 (.Q(n_130),
	.A(n_54),
	.B(\activation[3] [2]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[3] [2]));
   AO22JIX0 g3472__2398 (.Q(n_129),
	.A(n_54),
	.B(\activation[3] [3]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[3] [3]));
   ON31JIX0 g3473__5107 (.Q(n_128),
	.A(start),
	.B(en),
	.C(n_48),
	.D(n_55));
   AO21JIX0 g3495__6260 (.Q(n_137),
	.A(n_49),
	.B(en),
	.C(n_86));
   AO22JIX0 g3505__4319 (.Q(n_127),
	.A(n_54),
	.B(\activation[3] [5]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[3] [5]));
   AO22JIX0 g3506__8428 (.Q(n_126),
	.A(n_54),
	.B(\activation[3] [6]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[3] [6]));
   AO22JIX0 g3507__5526 (.Q(n_125),
	.A(n_54),
	.B(\activation[3] [7]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[3] [7]));
   AO22JIX0 g3508__6783 (.Q(n_124),
	.A(n_54),
	.B(\activation[4] [0]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[4] [0]));
   AO22JIX0 g3509__3680 (.Q(n_123),
	.A(n_54),
	.B(\activation[4] [1]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[4] [1]));
   AO22JIX0 g3510__1617 (.Q(n_122),
	.A(n_54),
	.B(\activation[4] [2]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[4] [2]));
   AO22JIX0 g3511__2802 (.Q(n_121),
	.A(n_54),
	.B(\activation[4] [3]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[4] [3]));
   AO22JIX0 g3512__1705 (.Q(n_120),
	.A(n_54),
	.B(\activation[4] [4]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[4] [4]));
   AO22JIX0 g3513__5122 (.Q(n_119),
	.A(n_54),
	.B(\activation[4] [5]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[4] [5]));
   AO22JIX0 g3514__8246 (.Q(n_118),
	.A(n_54),
	.B(\activation[4] [6]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[4] [6]));
   AO22JIX0 g3515__7098 (.Q(n_117),
	.A(n_54),
	.B(\activation[4] [7]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[4] [7]));
   AO22JIX0 g3516__6131 (.Q(n_116),
	.A(n_54),
	.B(\activation[5] [0]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[5] [0]));
   AO22JIX0 g3517__1881 (.Q(n_115),
	.A(n_54),
	.B(\activation[5] [1]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[5] [1]));
   AO22JIX0 g3518__5115 (.Q(n_114),
	.A(n_54),
	.B(\activation[5] [2]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[5] [2]));
   AO22JIX0 g3519__7482 (.Q(n_113),
	.A(n_54),
	.B(\activation[5] [3]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[5] [3]));
   AO22JIX0 g3520__4733 (.Q(n_112),
	.A(n_54),
	.B(\activation[5] [4]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[5] [4]));
   AO22JIX0 g3521__6161 (.Q(n_111),
	.A(n_54),
	.B(\activation[5] [5]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[5] [5]));
   AO22JIX0 g3522__9315 (.Q(n_110),
	.A(n_54),
	.B(\activation[5] [6]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[5] [6]));
   AO22JIX0 g3523__9945 (.Q(n_109),
	.A(n_54),
	.B(\activation[0] [1]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[0] [1]));
   AO22JIX0 g3524__2883 (.Q(n_108),
	.A(n_54),
	.B(\activation[5] [7]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[5] [7]));
   AO22JIX0 g3525__2346 (.Q(n_107),
	.A(n_54),
	.B(\activation[0] [2]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[0] [2]));
   AO22JIX0 g3526__1666 (.Q(n_106),
	.A(n_54),
	.B(\activation[0] [3]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[0] [3]));
   AO22JIX0 g3527__7410 (.Q(n_105),
	.A(n_54),
	.B(\activation[0] [4]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[0] [4]));
   AO22JIX0 g3528__6417 (.Q(n_104),
	.A(n_54),
	.B(\activation[0] [0]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[0] [0]));
   AO22JIX0 g3529__5477 (.Q(n_103),
	.A(n_54),
	.B(\activation[0] [5]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[0] [5]));
   AO22JIX0 g3530__2398 (.Q(n_102),
	.A(n_54),
	.B(\activation[0] [7]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[0] [7]));
   AO22JIX0 g3531__5107 (.Q(n_101),
	.A(n_54),
	.B(\activation[1] [0]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[1] [0]));
   AO22JIX0 g3532__6260 (.Q(n_100),
	.A(n_54),
	.B(\activation[0] [6]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[0] [6]));
   AO22JIX0 g3533__4319 (.Q(n_99),
	.A(n_54),
	.B(\activation[1] [1]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[1] [1]));
   AO22JIX0 g3534__8428 (.Q(n_98),
	.A(n_54),
	.B(\activation[1] [2]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[1] [2]));
   AO22JIX0 g3535__5526 (.Q(n_97),
	.A(n_54),
	.B(\activation[1] [3]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[1] [3]));
   AO22JIX0 g3536__6783 (.Q(n_96),
	.A(n_54),
	.B(\activation[1] [4]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[1] [4]));
   AO22JIX0 g3537__3680 (.Q(n_95),
	.A(n_54),
	.B(\activation[1] [5]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[1] [5]));
   AO22JIX0 g3538__1617 (.Q(n_94),
	.A(n_54),
	.B(\activation[1] [6]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[1] [6]));
   AO22JIX0 g3539__2802 (.Q(n_93),
	.A(n_54),
	.B(\activation[1] [7]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[1] [7]));
   AO22JIX0 g3540__1705 (.Q(n_92),
	.A(n_54),
	.B(\activation[2] [0]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[2] [0]));
   AO22JIX0 g3541__5122 (.Q(n_91),
	.A(n_54),
	.B(\activation[2] [1]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[2] [1]));
   AO22JIX0 g3542__8246 (.Q(n_90),
	.A(n_54),
	.B(\activation[2] [2]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[2] [2]));
   AO22JIX0 g3543__7098 (.Q(n_89),
	.A(n_54),
	.B(\activation[2] [3]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[2] [3]));
   AO22JIX0 g3544__6131 (.Q(n_88),
	.A(n_54),
	.B(\activation[2] [4]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[2] [4]));
   AO22JIX0 g3545__1881 (.Q(n_87),
	.A(n_54),
	.B(\activation[2] [5]),
	.C(FE_DBTN0_n_54),
	.D(\activation_reg[2] [5]));
   AO22JIX0 g3546__5115 (.Q(n_85),
	.A(n_47),
	.B(\result[4] [1]),
	.C(en),
	.D(\am_result[4] [1]));
   AO22JIX0 g3547__7482 (.Q(n_84),
	.A(n_47),
	.B(\result[5] [3]),
	.C(en),
	.D(\am_result[5] [3]));
   AO22JIX0 g3548__4733 (.Q(n_83),
	.A(n_47),
	.B(\result[5] [0]),
	.C(en),
	.D(\am_result[5] [0]));
   AO22JIX0 g3549__6161 (.Q(n_82),
	.A(n_47),
	.B(\result[5] [1]),
	.C(en),
	.D(\am_result[5] [1]));
   AO22JIX0 g3550__9315 (.Q(n_81),
	.A(n_47),
	.B(\result[4] [4]),
	.C(en),
	.D(\am_result[4] [4]));
   AO22JIX0 g3551__9945 (.Q(n_80),
	.A(n_47),
	.B(\result[4] [0]),
	.C(en),
	.D(\am_result[4] [0]));
   AO22JIX0 g3552__2883 (.Q(n_79),
	.A(n_47),
	.B(\result[0] [2]),
	.C(en),
	.D(\am_result[0] [2]));
   AO22JIX0 g3553__2346 (.Q(n_78),
	.A(n_47),
	.B(\result[1] [0]),
	.C(en),
	.D(\am_result[1] [0]));
   AO22JIX0 g3554__1666 (.Q(n_77),
	.A(n_47),
	.B(\result[4] [2]),
	.C(en),
	.D(\am_result[4] [2]));
   AO22JIX0 g3555__7410 (.Q(n_76),
	.A(n_47),
	.B(\result[5] [4]),
	.C(en),
	.D(\am_result[5] [4]));
   AO22JIX0 g3556__6417 (.Q(n_75),
	.A(n_47),
	.B(\result[0] [0]),
	.C(en),
	.D(\am_result[0] [0]));
   AO22JIX0 g3557__5477 (.Q(n_74),
	.A(n_47),
	.B(\result[0] [1]),
	.C(en),
	.D(\am_result[0] [1]));
   AO22JIX0 g3558__2398 (.Q(n_73),
	.A(n_47),
	.B(\result[0] [3]),
	.C(en),
	.D(\am_result[0] [3]));
   AO22JIX0 g3559__5107 (.Q(n_72),
	.A(n_47),
	.B(\result[0] [4]),
	.C(en),
	.D(\am_result[0] [4]));
   ON21JIX0 g3560__6260 (.Q(n_86),
	.A(en),
	.B(start),
	.C(n_55));
   AO22JIX0 g3561__4319 (.Q(n_71),
	.A(n_47),
	.B(\result[5] [2]),
	.C(en),
	.D(\am_result[5] [2]));
   AO22JIX0 g3562__8428 (.Q(n_70),
	.A(n_47),
	.B(\result[1] [2]),
	.C(en),
	.D(\am_result[1] [2]));
   AO22JIX0 g3563__5526 (.Q(n_69),
	.A(n_47),
	.B(\result[1] [4]),
	.C(en),
	.D(\am_result[1] [4]));
   AO22JIX0 g3564__6783 (.Q(n_68),
	.A(n_47),
	.B(\result[2] [4]),
	.C(en),
	.D(\am_result[2] [4]));
   AO22JIX0 g3565__3680 (.Q(n_67),
	.A(n_47),
	.B(\result[2] [1]),
	.C(en),
	.D(\am_result[2] [1]));
   AO22JIX0 g3566__1617 (.Q(n_66),
	.A(n_47),
	.B(\result[2] [2]),
	.C(en),
	.D(\am_result[2] [2]));
   AO22JIX0 g3567__2802 (.Q(n_65),
	.A(n_47),
	.B(\result[2] [3]),
	.C(en),
	.D(\am_result[2] [3]));
   AO22JIX0 g3568__1705 (.Q(n_64),
	.A(n_47),
	.B(\result[1] [3]),
	.C(en),
	.D(\am_result[1] [3]));
   AO22JIX0 g3569__5122 (.Q(n_63),
	.A(n_47),
	.B(\result[3] [0]),
	.C(en),
	.D(\am_result[3] [0]));
   AO22JIX0 g3570__8246 (.Q(n_62),
	.A(n_47),
	.B(\result[3] [3]),
	.C(en),
	.D(\am_result[3] [3]));
   AO22JIX0 g3571__7098 (.Q(n_61),
	.A(n_47),
	.B(\result[3] [1]),
	.C(en),
	.D(\am_result[3] [1]));
   AO22JIX0 g3572__6131 (.Q(n_60),
	.A(n_47),
	.B(\result[3] [4]),
	.C(en),
	.D(\am_result[3] [4]));
   AO22JIX0 g3573__1881 (.Q(n_59),
	.A(n_47),
	.B(\result[3] [2]),
	.C(en),
	.D(\am_result[3] [2]));
   AO22JIX0 g3574__5115 (.Q(n_58),
	.A(n_47),
	.B(\result[4] [3]),
	.C(en),
	.D(\am_result[4] [3]));
   AO22JIX0 g3575__7482 (.Q(n_57),
	.A(n_47),
	.B(\result[2] [0]),
	.C(en),
	.D(\am_result[2] [0]));
   AO22JIX0 g3576__4733 (.Q(n_56),
	.A(n_47),
	.B(\result[1] [1]),
	.C(en),
	.D(\am_result[1] [1]));
   NA2JIX0 g3577__6161 (.Q(n_55),
	.A(n_48),
	.B(en));
   AND2JIX1 g3582__9315 (.Q(n_54),
	.A(n_47),
	.B(start));
   INVJIX0 g3584 (.Q(n_49),
	.A(cycle_counter[1]));
   INVJIX0 g3585 (.Q(n_48),
	.A(cycle_counter[0]));
   INVJIX0 g3586 (.Q(n_47),
	.A(en));
endmodule

module adder_nbit_N5 (
	A, 
	B, 
	Sum);
   input [4:0] A;
   input [4:0] B;
   output [5:0] Sum;

   // Internal wires
   wire n_2;
   wire n_3;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_20;
   wire n_21;
   wire n_23;
   wire n_24;
   wire n_26;
   wire n_27;
   wire n_29;
   wire n_30;

   NA2JIX1 g294__9945 (.Q(Sum[5]),
	.A(n_30),
	.B(n_8));
   EO2JIX1 g295__2883 (.Q(Sum[4]),
	.A(n_29),
	.B(n_15));
   NA2JIX0 g296__2346 (.Q(n_30),
	.A(n_29),
	.B(n_10));
   NA2JIX1 g297__1666 (.Q(n_29),
	.A(n_27),
	.B(n_7));
   EO2JIX1 g298__7410 (.Q(Sum[3]),
	.A(n_26),
	.B(n_18));
   NA2JIX1 g299__6417 (.Q(n_27),
	.A(n_26),
	.B(n_11));
   NA2JIX1 g300__5477 (.Q(n_26),
	.A(n_24),
	.B(n_5));
   EO2JIX1 g301__2398 (.Q(Sum[2]),
	.A(n_23),
	.B(n_17));
   NA2JIX1 g302__5107 (.Q(n_24),
	.A(n_23),
	.B(n_14));
   NA2JIX1 g303__6260 (.Q(n_23),
	.A(n_21),
	.B(n_6));
   EO2JIX1 g304__4319 (.Q(Sum[1]),
	.A(n_16),
	.B(n_20));
   NA2JIX1 g305__8428 (.Q(n_21),
	.A(n_20),
	.B(n_13));
   INVJIX1 g306 (.Q(n_20),
	.A(n_9));
   NO2I1JIX1 g307__5526 (.Q(Sum[0]),
	.AN(n_9),
	.B(n_12));
   EO2JIX0 g308__6783 (.Q(n_18),
	.A(B[3]),
	.B(A[3]));
   EO2JIX1 g309__3680 (.Q(n_17),
	.A(B[2]),
	.B(A[2]));
   EO2JIX1 g310__1617 (.Q(n_16),
	.A(B[1]),
	.B(A[1]));
   EO2JIX0 g311__2802 (.Q(n_15),
	.A(B[4]),
	.B(A[4]));
   OR2JIX0 g312__1705 (.Q(n_14),
	.A(A[2]),
	.B(B[2]));
   NA2JIX1 g313__5122 (.Q(n_13),
	.A(n_3),
	.B(n_2));
   NO2JIX0 g314__8246 (.Q(n_12),
	.A(B[0]),
	.B(A[0]));
   OR2JIX0 g315__7098 (.Q(n_11),
	.A(A[3]),
	.B(B[3]));
   OR2JIX0 g316__6131 (.Q(n_10),
	.A(A[4]),
	.B(B[4]));
   NA2JIX0 g317__1881 (.Q(n_8),
	.A(B[4]),
	.B(A[4]));
   NA2JIX0 g318__5115 (.Q(n_7),
	.A(B[3]),
	.B(A[3]));
   NA2JIX1 g319__7482 (.Q(n_6),
	.A(B[1]),
	.B(A[1]));
   NA2JIX0 g320__4733 (.Q(n_5),
	.A(B[2]),
	.B(A[2]));
   NA2JIX1 g321__6161 (.Q(n_9),
	.A(B[0]),
	.B(A[0]));
   INVJIX1 g323 (.Q(n_3),
	.A(B[1]));
   INVJIX1 g325 (.Q(n_2),
	.A(A[1]));
endmodule

module adder_nbit_N5_158 (
	A, 
	B, 
	Sum);
   input [4:0] A;
   input [4:0] B;
   output [5:0] Sum;

   // Internal wires
   wire n_2;
   wire n_3;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_20;
   wire n_21;
   wire n_23;
   wire n_24;
   wire n_26;
   wire n_27;
   wire n_29;
   wire n_30;

   NA2JIX1 g294__9315 (.Q(Sum[5]),
	.A(n_30),
	.B(n_8));
   EO2JIX1 g295__9945 (.Q(Sum[4]),
	.A(n_29),
	.B(n_15));
   NA2JIX0 g296__2883 (.Q(n_30),
	.A(n_29),
	.B(n_10));
   NA2JIX1 g297__2346 (.Q(n_29),
	.A(n_27),
	.B(n_7));
   EO2JIX1 g298__1666 (.Q(Sum[3]),
	.A(n_26),
	.B(n_18));
   NA2JIX1 g299__7410 (.Q(n_27),
	.A(n_26),
	.B(n_11));
   NA2JIX1 g300__6417 (.Q(n_26),
	.A(n_24),
	.B(n_5));
   EO2JIX1 g301__5477 (.Q(Sum[2]),
	.A(n_23),
	.B(n_17));
   NA2JIX1 g302__2398 (.Q(n_24),
	.A(n_23),
	.B(n_14));
   NA2JIX1 g303__5107 (.Q(n_23),
	.A(n_21),
	.B(n_6));
   EO2JIX1 g304__6260 (.Q(Sum[1]),
	.A(n_16),
	.B(n_20));
   NA2JIX1 g305__4319 (.Q(n_21),
	.A(n_20),
	.B(n_13));
   INVJIX1 g306 (.Q(n_20),
	.A(n_9));
   NO2I1JIX1 g307__8428 (.Q(Sum[0]),
	.AN(n_9),
	.B(n_12));
   EO2JIX0 g308__5526 (.Q(n_18),
	.A(B[3]),
	.B(A[3]));
   EO2JIX1 g309__6783 (.Q(n_17),
	.A(B[2]),
	.B(A[2]));
   EO2JIX1 g310__3680 (.Q(n_16),
	.A(B[1]),
	.B(A[1]));
   EO2JIX0 g311__1617 (.Q(n_15),
	.A(B[4]),
	.B(A[4]));
   OR2JIX0 g312__2802 (.Q(n_14),
	.A(A[2]),
	.B(B[2]));
   NA2JIX1 g313__1705 (.Q(n_13),
	.A(n_3),
	.B(n_2));
   NO2JIX0 g314__5122 (.Q(n_12),
	.A(B[0]),
	.B(A[0]));
   OR2JIX0 g315__8246 (.Q(n_11),
	.A(A[3]),
	.B(B[3]));
   OR2JIX0 g316__7098 (.Q(n_10),
	.A(A[4]),
	.B(B[4]));
   NA2JIX0 g317__6131 (.Q(n_8),
	.A(B[4]),
	.B(A[4]));
   NA2JIX0 g318__1881 (.Q(n_7),
	.A(B[3]),
	.B(A[3]));
   NA2JIX1 g319__5115 (.Q(n_6),
	.A(B[1]),
	.B(A[1]));
   NA2JIX0 g320__7482 (.Q(n_5),
	.A(B[2]),
	.B(A[2]));
   NA2JIX1 g321__4733 (.Q(n_9),
	.A(B[0]),
	.B(A[0]));
   INVJIX1 g323 (.Q(n_3),
	.A(B[1]));
   INVJIX1 g325 (.Q(n_2),
	.A(A[1]));
endmodule

module adder_nbit_N5_157 (
	A, 
	B, 
	Sum);
   input [4:0] A;
   input [4:0] B;
   output [5:0] Sum;

   // Internal wires
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_17;
   wire n_18;
   wire n_20;
   wire n_21;
   wire n_23;

   AO22JIX0 g294__6161 (.Q(Sum[5]),
	.A(n_23),
	.B(n_8),
	.C(B[4]),
	.D(A[4]));
   EO2JIX1 g295__9315 (.Q(Sum[4]),
	.A(n_23),
	.B(n_13));
   NA2JIX1 g296__9945 (.Q(n_23),
	.A(n_21),
	.B(n_9));
   EO2JIX1 g297__2883 (.Q(Sum[3]),
	.A(n_20),
	.B(n_15));
   NA2JIX1 g298__2346 (.Q(n_21),
	.A(n_20),
	.B(n_11));
   NA2JIX1 g299__1666 (.Q(n_20),
	.A(n_18),
	.B(n_7));
   EO2JIX1 g300__7410 (.Q(Sum[2]),
	.A(n_17),
	.B(n_14));
   NA2JIX0 g301__6417 (.Q(n_18),
	.A(n_17),
	.B(n_12));
   NA2JIX1 g302__5477 (.Q(n_17),
	.A(n_3),
	.B(n_10));
   EO3JIX0 g303__2398 (.Q(Sum[1]),
	.A(n_4),
	.B(B[1]),
	.C(A[1]));
   EO2JIX0 g307__5107 (.Q(n_15),
	.A(B[3]),
	.B(A[3]));
   EO2JIX1 g308__6260 (.Q(n_14),
	.A(n_6),
	.B(n_5));
   EO2JIX0 g309__4319 (.Q(n_13),
	.A(B[4]),
	.B(A[4]));
   NA2JIX0 g311__8428 (.Q(n_12),
	.A(n_5),
	.B(n_6));
   OR2JIX0 g312__5526 (.Q(n_11),
	.A(A[3]),
	.B(B[3]));
   NA2JIX0 g313__6783 (.Q(n_10),
	.A(B[1]),
	.B(A[1]));
   NA2JIX0 g314__3680 (.Q(n_9),
	.A(B[3]),
	.B(A[3]));
   OR2JIX0 g315__1617 (.Q(n_8),
	.A(A[4]),
	.B(B[4]));
   NA2JIX0 g316__2802 (.Q(n_7),
	.A(B[2]),
	.B(A[2]));
   INVJIX1 g318 (.Q(n_6),
	.A(A[2]));
   INVJIX1 g320 (.Q(n_5),
	.A(B[2]));
   AND2JIX0 g2__1705 (.Q(n_4),
	.A(B[0]),
	.B(A[0]));
   ON211JIX1 g323__5122 (.Q(n_3),
	.A(B[1]),
	.B(A[1]),
	.C(B[0]),
	.D(A[0]));
   EO2JIX1 g333__8246 (.Q(Sum[0]),
	.A(B[0]),
	.B(A[0]));
endmodule

module adder_nbit_N6 (
	A, 
	B, 
	Sum);
   input [5:0] A;
   input [5:0] B;
   output [6:0] Sum;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_8;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_24;
   wire n_25;
   wire n_27;
   wire n_28;
   wire n_30;
   wire n_31;
   wire n_33;
   wire n_34;
   wire n_36;
   wire n_37;

   NA2I1JIX1 g380__7098 (.Q(Sum[6]),
	.AN(n_10),
	.B(n_37));
   EO2JIX1 g381__6131 (.Q(Sum[5]),
	.A(n_36),
	.B(n_22));
   NA2JIX0 g382__1881 (.Q(n_37),
	.A(n_36),
	.B(n_14));
   NA2JIX1 g383__5115 (.Q(n_36),
	.A(n_34),
	.B(n_11));
   EO2JIX1 g384__7482 (.Q(Sum[4]),
	.A(n_21),
	.B(n_33));
   NA2JIX1 g385__4733 (.Q(n_34),
	.A(n_33),
	.B(n_16));
   NA2JIX1 g386__6161 (.Q(n_33),
	.A(n_31),
	.B(n_13));
   EO2JIX1 g387__9315 (.Q(Sum[3]),
	.A(n_30),
	.B(n_20));
   NA2JIX1 g388__9945 (.Q(n_31),
	.A(n_30),
	.B(n_17));
   NA2JIX1 g389__2883 (.Q(n_30),
	.A(n_28),
	.B(n_12));
   EO2JIX1 g390__2346 (.Q(Sum[2]),
	.A(n_27),
	.B(n_19));
   NA2JIX1 g391__1666 (.Q(n_28),
	.A(n_27),
	.B(n_15));
   NA2JIX1 g392__7410 (.Q(n_27),
	.A(n_25),
	.B(n_0));
   EO2JIX1 g393__6417 (.Q(Sum[1]),
	.A(n_18),
	.B(n_24));
   NA2JIX1 g394__5477 (.Q(n_25),
	.A(n_1),
	.B(n_24));
   HAJIX1 g395__2398 (.CO(n_24),
	.S(Sum[0]),
	.A(A[0]),
	.B(B[0]));
   EO2JIX0 g396__5107 (.Q(n_22),
	.A(B[5]),
	.B(A[5]));
   EO2JIX1 g397__6260 (.Q(n_21),
	.A(B[4]),
	.B(A[4]));
   EO2JIX1 g398__4319 (.Q(n_20),
	.A(B[3]),
	.B(A[3]));
   EO2JIX1 g399__8428 (.Q(n_19),
	.A(B[2]),
	.B(A[2]));
   EO2JIX1 g400__5526 (.Q(n_18),
	.A(B[1]),
	.B(A[1]));
   NA2I1JIX1 g401__6783 (.Q(n_17),
	.AN(B[3]),
	.B(n_4));
   NA2JIX0 g403__3680 (.Q(n_16),
	.A(n_3),
	.B(n_5));
   NA2I1JIX1 g404__1617 (.Q(n_15),
	.AN(B[2]),
	.B(n_2));
   OR2JIX0 g405__2802 (.Q(n_14),
	.A(A[5]),
	.B(B[5]));
   NA2JIX0 g406__1705 (.Q(n_13),
	.A(B[3]),
	.B(A[3]));
   NA2JIX0 g407__5122 (.Q(n_12),
	.A(B[2]),
	.B(A[2]));
   NA2JIX0 g408__8246 (.Q(n_11),
	.A(B[4]),
	.B(A[4]));
   AND2JIX0 g410__7098 (.Q(n_10),
	.A(B[5]),
	.B(A[5]));
   INVJIX1 g414 (.Q(n_8),
	.A(A[1]));
   INVJIX1 g417 (.Q(n_6),
	.A(B[1]));
   INVJIX0 g418 (.Q(n_5),
	.A(A[4]));
   INVJIX0 g419 (.Q(n_4),
	.A(A[3]));
   INVJIX0 g420 (.Q(n_3),
	.A(B[4]));
   INVJIX0 g421 (.Q(n_2),
	.A(A[2]));
   NA2I1JIX1 g2__6131 (.Q(n_1),
	.AN(A[1]),
	.B(n_6));
   NA2I1JIX1 g422__1881 (.Q(n_0),
	.AN(n_8),
	.B(B[1]));
endmodule

module adder_nbit_N6_1 (
	A, 
	B, 
	Sum);
   input [5:0] A;
   input [5:0] B;
   output [6:0] Sum;

   // Internal wires
   wire [6:0] Carry;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_14;
   wire n_16;

   assign Sum[0] = 1'b0 ;

   EO2JIX1 g72__5115 (.Q(Sum[1]),
	.A(A[1]),
	.B(B[1]));
   EO2JIX1 g83__7482 (.Q(Sum[2]),
	.A(n_14),
	.B(n_16));
   EN2JIX0 g84__4733 (.Q(n_14),
	.A(A[2]),
	.B(B[2]));
   NA2JIX1 g86__6161 (.Q(n_16),
	.A(A[1]),
	.B(B[1]));
   NA2JIX1 g156__9315 (.Q(Sum[5]),
	.A(Sum[6]),
	.B(n_12));
   NA2JIX0 g159__9945 (.Q(n_12),
	.A(n_11),
	.B(A[5]));
   NA2JIX0 g160__2883 (.Q(n_11),
	.A(n_10),
	.B(n_4));
   EO2JIX1 g161__2346 (.Q(Sum[4]),
	.A(n_8),
	.B(n_6));
   ON21JIX1 g162__1666 (.Q(n_10),
	.A(A[4]),
	.B(B[4]),
	.C(n_8));
   NA2JIX1 g164__7410 (.Q(n_8),
	.A(n_7),
	.B(n_5));
   ON21JIX1 g165__6417 (.Q(n_7),
	.A(A[3]),
	.B(B[3]),
	.C(Carry[3]));
   EO2JIX1 g166__5477 (.Q(n_6),
	.A(A[4]),
	.B(B[4]));
   NA2JIX0 g167__2398 (.Q(n_5),
	.A(A[3]),
	.B(B[3]));
   NA2JIX0 g168__5107 (.Q(n_4),
	.A(A[4]),
	.B(B[4]));
   NA3I1JIX0 g2__6260 (.Q(Sum[6]),
	.AN(A[5]),
	.B(n_10),
	.C(n_4));
   EO2JIX1 g109__4319 (.Q(Sum[3]),
	.A(n_2),
	.B(Carry[3]));
   ON21JIX1 g111__8428 (.Q(Carry[3]),
	.A(n_1),
	.B(n_16),
	.C(n_0));
   EO2JIX1 g112__5526 (.Q(n_2),
	.A(A[3]),
	.B(B[3]));
   NO2JIX1 g113__6783 (.Q(n_1),
	.A(A[2]),
	.B(B[2]));
   NA2JIX1 g114__3680 (.Q(n_0),
	.A(A[2]),
	.B(B[2]));
endmodule

module adder_nbit_N7 (
	A, 
	B, 
	Sum);
   input [6:0] A;
   input [6:0] B;
   output [7:0] Sum;

   // Internal wires
   wire [7:0] Carry;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_24;

   EO2JIX0 g138__1617 (.Q(Sum[0]),
	.A(A[0]),
	.B(B[0]));
   EN3JIX0 g149__2802 (.Q(Sum[1]),
	.A(A[1]),
	.B(B[1]),
	.C(n_24));
   NA2JIX0 g150__1705 (.Q(n_24),
	.A(A[0]),
	.B(B[0]));
   EO3JIX0 g175__5122 (.Q(Sum[2]),
	.A(Carry[2]),
	.B(A[2]),
	.C(B[2]));
   ON21JIX1 g177__8246 (.Q(Carry[2]),
	.A(n_22),
	.B(n_24),
	.C(n_21));
   NO2JIX1 g178__7098 (.Q(n_22),
	.A(B[1]),
	.B(A[1]));
   NA2JIX0 g179__6131 (.Q(n_21),
	.A(A[1]),
	.B(B[1]));
   EO3JIX0 g180__1881 (.Q(Sum[3]),
	.A(Carry[3]),
	.B(A[3]),
	.C(B[3]));
   NA2JIX1 g181__5115 (.Q(Carry[3]),
	.A(n_20),
	.B(n_19));
   NA2JIX1 g182__7482 (.Q(n_20),
	.A(n_18),
	.B(Carry[2]));
   NA2JIX0 g183__4733 (.Q(n_19),
	.A(A[2]),
	.B(B[2]));
   OR2JIX0 g2__6161 (.Q(n_18),
	.A(A[2]),
	.B(B[2]));
   NA2JIX1 g291__9315 (.Q(Sum[7]),
	.A(n_17),
	.B(n_5));
   EO2JIX1 g292__9945 (.Q(Sum[6]),
	.A(n_16),
	.B(n_10));
   NA2JIX0 g293__2883 (.Q(n_17),
	.A(n_4),
	.B(n_16));
   NA2JIX1 g294__2346 (.Q(n_16),
	.A(n_15),
	.B(n_3));
   EO2JIX0 g295__1666 (.Q(Sum[5]),
	.A(n_12),
	.B(n_14));
   ON21JIX1 g296__7410 (.Q(n_15),
	.A(B[5]),
	.B(A[5]),
	.C(n_14));
   ON21JIX1 g297__6417 (.Q(n_14),
	.A(n_9),
	.B(n_13),
	.C(n_6));
   EN2JIX0 g298__5477 (.Q(Sum[4]),
	.A(n_11),
	.B(n_13));
   AN21JIX1 g299__2398 (.Q(n_13),
	.A(Carry[3]),
	.B(n_7),
	.C(n_8));
   EO2JIX0 g300__5107 (.Q(n_12),
	.A(A[5]),
	.B(B[5]));
   EO2JIX0 g301__6260 (.Q(n_11),
	.A(A[4]),
	.B(B[4]));
   EO2JIX1 g302__4319 (.Q(n_10),
	.A(A[6]),
	.B(B[6]));
   NO2JIX1 g303__8428 (.Q(n_9),
	.A(A[4]),
	.B(B[4]));
   AND2JIX0 g304__5526 (.Q(n_8),
	.A(A[3]),
	.B(B[3]));
   NA2JIX1 g305__6783 (.Q(n_7),
	.A(n_1),
	.B(n_2));
   NA2JIX0 g306__3680 (.Q(n_6),
	.A(A[4]),
	.B(B[4]));
   NA2JIX0 g307__1617 (.Q(n_5),
	.A(A[6]),
	.B(B[6]));
   OR2JIX0 g308__2802 (.Q(n_4),
	.A(A[6]),
	.B(B[6]));
   NA2JIX0 g309__1705 (.Q(n_3),
	.A(A[5]),
	.B(B[5]));
   INVJIX0 g310 (.Q(n_2),
	.A(B[3]));
   INVJIX0 g311 (.Q(n_1),
	.A(A[3]));
endmodule

module AdderTree_6_WEIGHT_WIDTH8_NUM_UNITS6 (
	\input_data[0] , 
	\input_data[1] , 
	\input_data[2] , 
	\input_data[3] , 
	\input_data[4] , 
	\input_data[5] , 
	clk, 
	rst, 
	sum_combinational, 
	\DFT_/sen , 
	\DFT_/sdo , 
	SPCASCAN_N0, 
	sum_out_2, 
	SPCASCAN_N4, 
	sum_out_1, 
	SPCBSCAN_N6);
   input [7:0] \input_data[0] ;
   input [7:0] \input_data[1] ;
   input [7:0] \input_data[2] ;
   input [7:0] \input_data[3] ;
   input [7:0] \input_data[4] ;
   input [7:0] \input_data[5] ;
   input clk;
   input rst;
   output [10:0] sum_combinational;
   input \DFT_/sen ;
   output \DFT_/sdo ;
   input SPCASCAN_N0;
   output sum_out_2;
   input SPCASCAN_N4;
   output sum_out_1;
   input SPCBSCAN_N6;

   // Internal wires
   wire [5:0] \int_sum_L1[0] ;
   wire [5:0] \int_sum_L1[1] ;
   wire [5:0] \int_sum_L1[2] ;
   wire [6:0] \int_sum_L2[0] ;
   wire [10:0] sum_out;
   wire [6:0] \int_sum_L2[1] ;
   wire UNCONNECTED;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;

   assign sum_out_2 = sum_out[2] ;
   assign sum_out_1 = sum_out[1] ;
   assign sum_combinational[0] = 1'b0 ;
   assign sum_combinational[1] = 1'b0 ;
   assign sum_combinational[2] = 1'b0 ;
   assign sum_combinational[3] = 1'b0 ;
   assign sum_combinational[8] = 1'b0 ;
   assign sum_combinational[9] = 1'b0 ;
   assign sum_combinational[10] = 1'b0 ;

   adder_nbit_N5 \L1_ADD[0].inst_L1  (.A({ \input_data[0] [4],
		\input_data[0] [3],
		\input_data[0] [2],
		\input_data[0] [1],
		\input_data[0] [0] }),
	.B({ \input_data[1] [4],
		\input_data[1] [3],
		\input_data[1] [2],
		\input_data[1] [1],
		\input_data[1] [0] }),
	.Sum(\int_sum_L1[0] ));
   adder_nbit_N5_158 \L1_ADD[1].inst_L1  (.A({ \input_data[2] [4],
		\input_data[2] [3],
		\input_data[2] [2],
		\input_data[2] [1],
		\input_data[2] [0] }),
	.B({ \input_data[3] [4],
		\input_data[3] [3],
		\input_data[3] [2],
		\input_data[3] [1],
		\input_data[3] [0] }),
	.Sum(\int_sum_L1[1] ));
   adder_nbit_N5_157 \L1_ADD[2].inst_L1  (.A({ \input_data[4] [4],
		\input_data[4] [3],
		\input_data[4] [2],
		\input_data[4] [1],
		\input_data[4] [0] }),
	.B({ \input_data[5] [4],
		\input_data[5] [3],
		\input_data[5] [2],
		\input_data[5] [1],
		\input_data[5] [0] }),
	.Sum(\int_sum_L1[2] ));
   adder_nbit_N6 inst_L2 (.A(\int_sum_L1[0] ),
	.B(\int_sum_L1[1] ),
	.Sum(\int_sum_L2[0] ));
   adder_nbit_N6_1 inst_L2_extra (.A({ \int_sum_L1[2] [5],
		\int_sum_L1[2] [4],
		\int_sum_L1[2] [3],
		\int_sum_L1[2] [2],
		\int_sum_L1[2] [1],
		1'b0 }),
	.B({ 1'b1,
		\DFT_/sdo ,
		sum_out[2],
		sum_out[1],
		sum_out[0],
		1'b0 }),
	.Sum({ \int_sum_L2[1] [6],
		\int_sum_L2[1] [5],
		\int_sum_L2[1] [4],
		\int_sum_L2[1] [3],
		\int_sum_L2[1] [2],
		\int_sum_L2[1] [1],
		UNCONNECTED }));
   adder_nbit_N7 inst_L6_0 (.A(\int_sum_L2[0] ),
	.B({ \int_sum_L2[1] [6],
		\int_sum_L2[1] [5],
		\int_sum_L2[1] [4],
		\int_sum_L2[1] [3],
		\int_sum_L2[1] [2],
		\int_sum_L2[1] [1],
		\int_sum_L1[2] [0] }),
	.Sum({ sum_combinational[7],
		sum_combinational[6],
		sum_combinational[5],
		sum_combinational[4],
		n_40,
		n_41,
		n_42,
		n_43 }));
   SDFRQJIX1 \sum_out_reg[3]  (.Q(\DFT_/sdo ),
	.C(clk),
	.D(n_3),
	.SD(sum_out_2),
	.SE(\DFT_/sen ));
   NO2I1JIX0 g9__5122 (.Q(n_3),
	.AN(n_40),
	.B(rst));
   SDFRQJIX1 \sum_out_reg[2]  (.Q(sum_out[2]),
	.C(clk),
	.D(n_2),
	.SD(SPCBSCAN_N6),
	.SE(\DFT_/sen ));
   NO2I1JIX0 g11__8246 (.Q(n_2),
	.AN(n_41),
	.B(rst));
   SDFRQJIX1 \sum_out_reg[1]  (.Q(sum_out[1]),
	.C(clk),
	.D(n_1),
	.SD(sum_out[0]),
	.SE(\DFT_/sen ));
   NO2I1JIX0 g13__7098 (.Q(n_1),
	.AN(n_42),
	.B(rst));
   SDFRQJIX1 \sum_out_reg[0]  (.Q(sum_out[0]),
	.C(clk),
	.D(n_0),
	.SD(SPCASCAN_N4),
	.SE(\DFT_/sen ));
   NO2I1JIX0 g15__6131 (.Q(n_0),
	.AN(n_43),
	.B(rst));
endmodule

module Out_Gen_Func (
	clk, 
	reset, 
	IN, 
	z_p, 
	z_n, 
	\DFT_/sdi , 
	\DFT_/sen , 
	R1, 
	p_1, 
	R2, 
	p_2, 
	R0);
   input clk;
   input reset;
   input [3:0] IN;
   output z_p;
   output z_n;
   input \DFT_/sdi ;
   input \DFT_/sen ;
   output R1;
   input p_1;
   output R2;
   input p_2;
   output R0;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;

   SDFRRQJIX1 R3_reg (.Q(z_n),
	.C(clk),
	.D(n_13),
	.RN(n_1),
	.SD(R2),
	.SE(\DFT_/sen ));
   NA2JIX1 g253__1881 (.Q(z_p),
	.A(n_12),
	.B(n_0));
   EO2JIX0 g254__5115 (.Q(n_13),
	.A(n_9),
	.B(n_11));
   NA2JIX0 g255__7482 (.Q(n_12),
	.A(n_9),
	.B(n_10));
   EO2JIX0 g256__4733 (.Q(n_11),
	.A(IN[3]),
	.B(R2));
   NA2I1JIX0 g257__6161 (.Q(n_10),
	.AN(R2),
	.B(n_2));
   SDFRRQJIX1 R2_reg (.Q(R2),
	.C(clk),
	.D(n_8),
	.RN(n_1),
	.SD(p_1),
	.SE(\DFT_/sen ));
   ON21JIX1 g260__9315 (.Q(n_9),
	.A(n_7),
	.B(n_3),
	.C(n_6));
   EN3JIX0 g261__9945 (.Q(n_8),
	.A(n_3),
	.B(IN[2]),
	.C(R1));
   NO2JIX1 g262__2883 (.Q(n_7),
	.A(IN[2]),
	.B(R1));
   NA2JIX0 g263__2346 (.Q(n_6),
	.A(IN[2]),
	.B(R1));
   SDFRRQJIX1 R1_reg (.Q(R1),
	.C(clk),
	.D(n_5),
	.RN(n_1),
	.SD(\DFT_/sdi ),
	.SE(\DFT_/sen ));
   NO2I1JIX0 g265__1666 (.Q(n_5),
	.AN(n_3),
	.B(n_4));
   NO2JIX0 g266__7410 (.Q(n_4),
	.A(IN[1]),
	.B(R0));
   NA2JIX1 g267__6417 (.Q(n_3),
	.A(IN[1]),
	.B(R0));
   SDFRRQJIX1 R0_reg (.Q(R0),
	.C(clk),
	.D(IN[0]),
	.RN(n_1),
	.SD(R1),
	.SE(\DFT_/sen ));
   INVJIX0 g270 (.Q(n_2),
	.A(IN[3]));
   INVJIX0 g271 (.Q(n_1),
	.A(reset));
   NA2I1JIX0 g2__5477 (.Q(n_0),
	.AN(n_2),
	.B(R2));
endmodule

module Main (
	\weight[0] , 
	\weight[1] , 
	\weight[2] , 
	\weight[3] , 
	\weight[4] , 
	\weight[5] , 
	\activation[0] , 
	\activation[1] , 
	\activation[2] , 
	\activation[3] , 
	\activation[4] , 
	\activation[5] , 
	start, 
	clk, 
	rst, 
	en, 
	z_p, 
	z_n, 
	scan_en, 
	scan_in, 
	scan_out);
   input [7:0] \weight[0] ;
   input [7:0] \weight[1] ;
   input [7:0] \weight[2] ;
   input [7:0] \weight[3] ;
   input [7:0] \weight[4] ;
   input [7:0] \weight[5] ;
   input [7:0] \activation[0] ;
   input [7:0] \activation[1] ;
   input [7:0] \activation[2] ;
   input [7:0] \activation[3] ;
   input [7:0] \activation[4] ;
   input [7:0] \activation[5] ;
   input start;
   input clk;
   input rst;
   output en;
   output z_p;
   output z_n;
   input scan_en;
   input scan_in;
   output scan_out;

   // Internal wires
   wire SPCBSCAN_N6;
   wire SPCASCAN_N5;
   wire SPCASCAN_N4;
   wire SPCASCAN_N3;
   wire SPCASCAN_N2;
   wire SPCASCAN_N1;
   wire SPCASCAN_N0;
   wire [7:0] \result[0] ;
   wire [7:0] \result[1] ;
   wire [7:0] \result[2] ;
   wire [7:0] \result[3] ;
   wire [7:0] \result[4] ;
   wire [7:0] \result[5] ;
   wire [10:0] sum_combinational;
   wire n_105;

   assign scan_out = z_n ;

   ActivationMultiplier_6_IN_WIDTH8_NUM_UNITS6_ACTIVATION_WIDTH8 A6M (.\activation[0] (\activation[0] ),
	.\activation[1] (\activation[1] ),
	.\activation[2] (\activation[2] ),
	.\activation[3] (\activation[3] ),
	.\activation[4] (\activation[4] ),
	.\activation[5] (\activation[5] ),
	.\weight[0] (\weight[0] ),
	.\weight[1] (\weight[1] ),
	.\weight[2] (\weight[2] ),
	.\weight[3] (\weight[3] ),
	.\weight[4] (\weight[4] ),
	.\weight[5] (\weight[5] ),
	.clk(clk),
	.rst(rst),
	.start(start),
	.\result[0] (\result[0] ),
	.\result[1] (\result[1] ),
	.\result[2] (\result[2] ),
	.\result[3] (\result[3] ),
	.\result[4] (\result[4] ),
	.\result[5] (\result[5] ),
	.en(en),
	.\DFT_/sdi (scan_in),
	.\DFT_/sen (scan_en),
	.n_0(SPCASCAN_N0),
	.SPCASCAN_N1(SPCASCAN_N1),
	.p_1(n_105),
	.SPCASCAN_N2(SPCASCAN_N2),
	.SPCASCAN_N3(SPCASCAN_N3),
	.n_3(SPCASCAN_N4),
	.SPCASCAN_N5(SPCASCAN_N5));
   AdderTree_6_WEIGHT_WIDTH8_NUM_UNITS6 AT6 (.\input_data[0] ({ 1'b0,
		1'b0,
		1'b0,
		\result[0] [4],
		\result[0] [3],
		\result[0] [2],
		\result[0] [1],
		\result[0] [0] }),
	.\input_data[1] ({ 1'b0,
		1'b0,
		1'b0,
		\result[1] [4],
		\result[1] [3],
		\result[1] [2],
		\result[1] [1],
		\result[1] [0] }),
	.\input_data[2] ({ 1'b0,
		1'b0,
		1'b0,
		\result[2] [4],
		\result[2] [3],
		\result[2] [2],
		\result[2] [1],
		\result[2] [0] }),
	.\input_data[3] ({ 1'b0,
		1'b0,
		1'b0,
		\result[3] [4],
		\result[3] [3],
		\result[3] [2],
		\result[3] [1],
		\result[3] [0] }),
	.\input_data[4] ({ 1'b0,
		1'b0,
		1'b0,
		\result[4] [4],
		\result[4] [3],
		\result[4] [2],
		\result[4] [1],
		\result[4] [0] }),
	.\input_data[5] ({ 1'b0,
		1'b0,
		1'b0,
		\result[5] [4],
		\result[5] [3],
		\result[5] [2],
		\result[5] [1],
		\result[5] [0] }),
	.clk(clk),
	.rst(rst),
	.sum_combinational(sum_combinational),
	.\DFT_/sen (scan_en),
	.\DFT_/sdo (n_105),
	.SPCASCAN_N0(SPCASCAN_N0),
	.sum_out_2(SPCASCAN_N1),
	.SPCASCAN_N4(SPCASCAN_N4),
	.sum_out_1(SPCASCAN_N5),
	.SPCBSCAN_N6(SPCBSCAN_N6));
   Out_Gen_Func OGF (.clk(clk),
	.reset(rst),
	.IN({ sum_combinational[7],
		sum_combinational[6],
		sum_combinational[5],
		sum_combinational[4] }),
	.z_p(z_p),
	.z_n(z_n),
	.\DFT_/sdi (\result[5] [4]),
	.\DFT_/sen (scan_en),
	.R1(SPCASCAN_N2),
	.p_1(\result[3] [4]),
	.R2(SPCASCAN_N3),
	.p_2(\result[0] [4]),
	.R0(SPCBSCAN_N6));
endmodule

