
//input ports
add mapped point weight[0][7] weight[0][7] -type PI PI
add mapped point weight[0][6] weight[0][6] -type PI PI
add mapped point weight[0][5] weight[0][5] -type PI PI
add mapped point weight[0][4] weight[0][4] -type PI PI
add mapped point weight[0][3] weight[0][3] -type PI PI
add mapped point weight[0][2] weight[0][2] -type PI PI
add mapped point weight[0][1] weight[0][1] -type PI PI
add mapped point weight[0][0] weight[0][0] -type PI PI
add mapped point weight[1][7] weight[1][7] -type PI PI
add mapped point weight[1][6] weight[1][6] -type PI PI
add mapped point weight[1][5] weight[1][5] -type PI PI
add mapped point weight[1][4] weight[1][4] -type PI PI
add mapped point weight[1][3] weight[1][3] -type PI PI
add mapped point weight[1][2] weight[1][2] -type PI PI
add mapped point weight[1][1] weight[1][1] -type PI PI
add mapped point weight[1][0] weight[1][0] -type PI PI
add mapped point weight[2][7] weight[2][7] -type PI PI
add mapped point weight[2][6] weight[2][6] -type PI PI
add mapped point weight[2][5] weight[2][5] -type PI PI
add mapped point weight[2][4] weight[2][4] -type PI PI
add mapped point weight[2][3] weight[2][3] -type PI PI
add mapped point weight[2][2] weight[2][2] -type PI PI
add mapped point weight[2][1] weight[2][1] -type PI PI
add mapped point weight[2][0] weight[2][0] -type PI PI
add mapped point weight[3][7] weight[3][7] -type PI PI
add mapped point weight[3][6] weight[3][6] -type PI PI
add mapped point weight[3][5] weight[3][5] -type PI PI
add mapped point weight[3][4] weight[3][4] -type PI PI
add mapped point weight[3][3] weight[3][3] -type PI PI
add mapped point weight[3][2] weight[3][2] -type PI PI
add mapped point weight[3][1] weight[3][1] -type PI PI
add mapped point weight[3][0] weight[3][0] -type PI PI
add mapped point weight[4][7] weight[4][7] -type PI PI
add mapped point weight[4][6] weight[4][6] -type PI PI
add mapped point weight[4][5] weight[4][5] -type PI PI
add mapped point weight[4][4] weight[4][4] -type PI PI
add mapped point weight[4][3] weight[4][3] -type PI PI
add mapped point weight[4][2] weight[4][2] -type PI PI
add mapped point weight[4][1] weight[4][1] -type PI PI
add mapped point weight[4][0] weight[4][0] -type PI PI
add mapped point weight[5][7] weight[5][7] -type PI PI
add mapped point weight[5][6] weight[5][6] -type PI PI
add mapped point weight[5][5] weight[5][5] -type PI PI
add mapped point weight[5][4] weight[5][4] -type PI PI
add mapped point weight[5][3] weight[5][3] -type PI PI
add mapped point weight[5][2] weight[5][2] -type PI PI
add mapped point weight[5][1] weight[5][1] -type PI PI
add mapped point weight[5][0] weight[5][0] -type PI PI
add mapped point activation[0][7] activation[0][7] -type PI PI
add mapped point activation[0][6] activation[0][6] -type PI PI
add mapped point activation[0][5] activation[0][5] -type PI PI
add mapped point activation[0][4] activation[0][4] -type PI PI
add mapped point activation[0][3] activation[0][3] -type PI PI
add mapped point activation[0][2] activation[0][2] -type PI PI
add mapped point activation[0][1] activation[0][1] -type PI PI
add mapped point activation[0][0] activation[0][0] -type PI PI
add mapped point activation[1][7] activation[1][7] -type PI PI
add mapped point activation[1][6] activation[1][6] -type PI PI
add mapped point activation[1][5] activation[1][5] -type PI PI
add mapped point activation[1][4] activation[1][4] -type PI PI
add mapped point activation[1][3] activation[1][3] -type PI PI
add mapped point activation[1][2] activation[1][2] -type PI PI
add mapped point activation[1][1] activation[1][1] -type PI PI
add mapped point activation[1][0] activation[1][0] -type PI PI
add mapped point activation[2][7] activation[2][7] -type PI PI
add mapped point activation[2][6] activation[2][6] -type PI PI
add mapped point activation[2][5] activation[2][5] -type PI PI
add mapped point activation[2][4] activation[2][4] -type PI PI
add mapped point activation[2][3] activation[2][3] -type PI PI
add mapped point activation[2][2] activation[2][2] -type PI PI
add mapped point activation[2][1] activation[2][1] -type PI PI
add mapped point activation[2][0] activation[2][0] -type PI PI
add mapped point activation[3][7] activation[3][7] -type PI PI
add mapped point activation[3][6] activation[3][6] -type PI PI
add mapped point activation[3][5] activation[3][5] -type PI PI
add mapped point activation[3][4] activation[3][4] -type PI PI
add mapped point activation[3][3] activation[3][3] -type PI PI
add mapped point activation[3][2] activation[3][2] -type PI PI
add mapped point activation[3][1] activation[3][1] -type PI PI
add mapped point activation[3][0] activation[3][0] -type PI PI
add mapped point activation[4][7] activation[4][7] -type PI PI
add mapped point activation[4][6] activation[4][6] -type PI PI
add mapped point activation[4][5] activation[4][5] -type PI PI
add mapped point activation[4][4] activation[4][4] -type PI PI
add mapped point activation[4][3] activation[4][3] -type PI PI
add mapped point activation[4][2] activation[4][2] -type PI PI
add mapped point activation[4][1] activation[4][1] -type PI PI
add mapped point activation[4][0] activation[4][0] -type PI PI
add mapped point activation[5][7] activation[5][7] -type PI PI
add mapped point activation[5][6] activation[5][6] -type PI PI
add mapped point activation[5][5] activation[5][5] -type PI PI
add mapped point activation[5][4] activation[5][4] -type PI PI
add mapped point activation[5][3] activation[5][3] -type PI PI
add mapped point activation[5][2] activation[5][2] -type PI PI
add mapped point activation[5][1] activation[5][1] -type PI PI
add mapped point activation[5][0] activation[5][0] -type PI PI
add mapped point start start -type PI PI
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI

//output ports
add mapped point en en -type PO PO
add mapped point z_p z_p -type PO PO
add mapped point z_n z_n -type PO PO

//inout ports




//Sequential Pins
add mapped point OGF/R3/q OGF_R3_reg/Q -type DFF DFF
add mapped point OGF/R2/q OGF_R2_reg/Q -type DFF DFF
add mapped point OGF/R1/q OGF_R1_reg/Q -type DFF DFF
add mapped point OGF/R0/q OGF_R0_reg/Q -type DFF DFF
add mapped point AT6/sum_out[3]/q AT6_sum_out_reg[3]/Q -type DFF DFF
add mapped point AT6/sum_out[2]/q AT6_sum_out_reg[2]/Q -type DFF DFF
add mapped point AT6/sum_out[1]/q AT6_sum_out_reg[1]/Q -type DFF DFF
add mapped point A6M/result[2][0]/q A6M_result_reg[2][0]/Q -type DFF DFF
add mapped point A6M/result[1][0]/q A6M_result_reg[1][0]/Q -type DFF DFF
add mapped point A6M/result[2][3]/q A6M_result_reg[2][3]/Q -type DFF DFF
add mapped point A6M/result[0][0]/q A6M_result_reg[0][0]/Q -type DFF DFF
add mapped point A6M/result[5][0]/q A6M_result_reg[5][0]/Q -type DFF DFF
add mapped point A6M/result[3][4]/q A6M_result_reg[3][4]/Q -type DFF DFF
add mapped point A6M/result[4][2]/q A6M_result_reg[4][2]/Q -type DFF DFF
add mapped point A6M/result[2][2]/q A6M_result_reg[2][2]/Q -type DFF DFF
add mapped point A6M/result[1][1]/q A6M_result_reg[1][1]/Q -type DFF DFF
add mapped point A6M/result[5][3]/q A6M_result_reg[5][3]/Q -type DFF DFF
add mapped point A6M/result[3][2]/q A6M_result_reg[3][2]/Q -type DFF DFF
add mapped point A6M/result[3][0]/q A6M_result_reg[3][0]/Q -type DFF DFF
add mapped point A6M/result[4][0]/q A6M_result_reg[4][0]/Q -type DFF DFF
add mapped point A6M/result[0][1]/q A6M_result_reg[0][1]/Q -type DFF DFF
add mapped point A6M/result[0][2]/q A6M_result_reg[0][2]/Q -type DFF DFF
add mapped point A6M/result[0][3]/q A6M_result_reg[0][3]/Q -type DFF DFF
add mapped point A6M/result[1][2]/q A6M_result_reg[1][2]/Q -type DFF DFF
add mapped point A6M/result[1][3]/q A6M_result_reg[1][3]/Q -type DFF DFF
add mapped point A6M/result[2][1]/q A6M_result_reg[2][1]/Q -type DFF DFF
add mapped point A6M/result[0][4]/q A6M_result_reg[0][4]/Q -type DFF DFF
add mapped point A6M/result[4][1]/q A6M_result_reg[4][1]/Q -type DFF DFF
add mapped point A6M/result[4][3]/q A6M_result_reg[4][3]/Q -type DFF DFF
add mapped point A6M/result[5][1]/q A6M_result_reg[5][1]/Q -type DFF DFF
add mapped point A6M/result[5][2]/q A6M_result_reg[5][2]/Q -type DFF DFF
add mapped point A6M/result[3][3]/q A6M_result_reg[3][3]/Q -type DFF DFF
add mapped point A6M/result[1][4]/q A6M_result_reg[1][4]/Q -type DFF DFF
add mapped point A6M/result[2][4]/q A6M_result_reg[2][4]/Q -type DFF DFF
add mapped point A6M/result[4][4]/q A6M_result_reg[4][4]/Q -type DFF DFF
add mapped point A6M/result[5][4]/q A6M_result_reg[5][4]/Q -type DFF DFF
add mapped point A6M/result[3][1]/q A6M_result_reg[3][1]/Q -type DFF DFF
add mapped point A6M/cycle_counter[3]/q A6M_cycle_counter_reg[3]/Q -type DFF DFF
add mapped point A6M/cycle_counter[2]/q A6M_cycle_counter_reg[2]/Q -type DFF DFF
add mapped point AT6/sum_out[0]/q AT6_sum_out_reg[0]/Q -type DFF DFF
add mapped point A6M/en/q A6M_en_reg/Q -type DFF DFF
add mapped point A6M/cycle_counter[1]/q A6M_cycle_counter_reg[1]/Q -type DFF DFF
add mapped point A6M/activation_reg[4][2]/q A6M_activation_reg_reg[4][2]/Q -type DFF DFF
add mapped point A6M/activation_reg[1][6]/q A6M_activation_reg_reg[1][6]/Q -type DFF DFF
add mapped point A6M/activation_reg[4][5]/q A6M_activation_reg_reg[4][5]/Q -type DFF DFF
add mapped point A6M/activation_reg[5][4]/q A6M_activation_reg_reg[5][4]/Q -type DFF DFF
add mapped point A6M/activation_reg[2][6]/q A6M_activation_reg_reg[2][6]/Q -type DFF DFF
add mapped point A6M/activation_reg[2][3]/q A6M_activation_reg_reg[2][3]/Q -type DFF DFF
add mapped point A6M/activation_reg[5][2]/q A6M_activation_reg_reg[5][2]/Q -type DFF DFF
add mapped point A6M/activation_reg[4][4]/q A6M_activation_reg_reg[4][4]/Q -type DFF DFF
add mapped point A6M/activation_reg[0][2]/q A6M_activation_reg_reg[0][2]/Q -type DFF DFF
add mapped point A6M/activation_reg[1][2]/q A6M_activation_reg_reg[1][2]/Q -type DFF DFF
add mapped point A6M/activation_reg[3][0]/q A6M_activation_reg_reg[3][0]/Q -type DFF DFF
add mapped point A6M/activation_reg[2][0]/q A6M_activation_reg_reg[2][0]/Q -type DFF DFF
add mapped point A6M/activation_reg[1][7]/q A6M_activation_reg_reg[1][7]/Q -type DFF DFF
add mapped point A6M/activation_reg[3][6]/q A6M_activation_reg_reg[3][6]/Q -type DFF DFF
add mapped point A6M/activation_reg[3][2]/q A6M_activation_reg_reg[3][2]/Q -type DFF DFF
add mapped point A6M/activation_reg[5][7]/q A6M_activation_reg_reg[5][7]/Q -type DFF DFF
add mapped point A6M/activation_reg[2][7]/q A6M_activation_reg_reg[2][7]/Q -type DFF DFF
add mapped point A6M/activation_reg[3][1]/q A6M_activation_reg_reg[3][1]/Q -type DFF DFF
add mapped point A6M/activation_reg[3][3]/q A6M_activation_reg_reg[3][3]/Q -type DFF DFF
add mapped point A6M/activation_reg[3][4]/q A6M_activation_reg_reg[3][4]/Q -type DFF DFF
add mapped point A6M/activation_reg[3][5]/q A6M_activation_reg_reg[3][5]/Q -type DFF DFF
add mapped point A6M/activation_reg[3][7]/q A6M_activation_reg_reg[3][7]/Q -type DFF DFF
add mapped point A6M/activation_reg[0][1]/q A6M_activation_reg_reg[0][1]/Q -type DFF DFF
add mapped point A6M/activation_reg[4][1]/q A6M_activation_reg_reg[4][1]/Q -type DFF DFF
add mapped point A6M/activation_reg[5][6]/q A6M_activation_reg_reg[5][6]/Q -type DFF DFF
add mapped point A6M/activation_reg[4][3]/q A6M_activation_reg_reg[4][3]/Q -type DFF DFF
add mapped point A6M/activation_reg[1][4]/q A6M_activation_reg_reg[1][4]/Q -type DFF DFF
add mapped point A6M/activation_reg[4][6]/q A6M_activation_reg_reg[4][6]/Q -type DFF DFF
add mapped point A6M/activation_reg[4][7]/q A6M_activation_reg_reg[4][7]/Q -type DFF DFF
add mapped point A6M/activation_reg[5][0]/q A6M_activation_reg_reg[5][0]/Q -type DFF DFF
add mapped point A6M/activation_reg[5][1]/q A6M_activation_reg_reg[5][1]/Q -type DFF DFF
add mapped point A6M/activation_reg[5][3]/q A6M_activation_reg_reg[5][3]/Q -type DFF DFF
add mapped point A6M/activation_reg[5][5]/q A6M_activation_reg_reg[5][5]/Q -type DFF DFF
add mapped point A6M/activation_reg[0][0]/q A6M_activation_reg_reg[0][0]/Q -type DFF DFF
add mapped point A6M/activation_reg[1][5]/q A6M_activation_reg_reg[1][5]/Q -type DFF DFF
add mapped point A6M/activation_reg[4][0]/q A6M_activation_reg_reg[4][0]/Q -type DFF DFF
add mapped point A6M/activation_reg[0][3]/q A6M_activation_reg_reg[0][3]/Q -type DFF DFF
add mapped point A6M/activation_reg[0][5]/q A6M_activation_reg_reg[0][5]/Q -type DFF DFF
add mapped point A6M/activation_reg[0][6]/q A6M_activation_reg_reg[0][6]/Q -type DFF DFF
add mapped point A6M/activation_reg[0][7]/q A6M_activation_reg_reg[0][7]/Q -type DFF DFF
add mapped point A6M/activation_reg[2][5]/q A6M_activation_reg_reg[2][5]/Q -type DFF DFF
add mapped point A6M/activation_reg[2][4]/q A6M_activation_reg_reg[2][4]/Q -type DFF DFF
add mapped point A6M/activation_reg[2][2]/q A6M_activation_reg_reg[2][2]/Q -type DFF DFF
add mapped point A6M/activation_reg[0][4]/q A6M_activation_reg_reg[0][4]/Q -type DFF DFF
add mapped point A6M/activation_reg[2][1]/q A6M_activation_reg_reg[2][1]/Q -type DFF DFF
add mapped point A6M/activation_reg[1][3]/q A6M_activation_reg_reg[1][3]/Q -type DFF DFF
add mapped point A6M/activation_reg[1][1]/q A6M_activation_reg_reg[1][1]/Q -type DFF DFF
add mapped point A6M/activation_reg[1][0]/q A6M_activation_reg_reg[1][0]/Q -type DFF DFF
add mapped point A6M/cycle_counter[0]/q A6M_cycle_counter_reg[0]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
