
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jul  7 2025 00:51:07 CEST (Jul  6 2025 22:51:07 UTC)

// Verification Directory fv/ADDF 

module ADDF(A, B, CI, CO, SUM);
  input [0:0] A, B, CI;
  output [0:0] CO, SUM;
  wire [0:0] A, B, CI;
  wire [0:0] CO, SUM;
  FAJIX0 g89__2398(.A (A), .B (B), .CI (CI), .CO (CO), .S (SUM));
endmodule

