
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Jun 25 2025 18:03:19 EDT (Jun 25 2025 22:03:19 UTC)

// Verification Directory fv/ADDF 

module ADDF(A, B, CI, CO, SUM);
  input [0:0] A, B, CI;
  output [0:0] CO, SUM;
  wire [0:0] A, B, CI;
  wire [0:0] CO, SUM;
  wire n_0, n_1, n_2;
  sg13g2_xnor2_1 g89__2398(.A (n_1), .B (CI), .Y (SUM));
  sg13g2_nand2_1 g90__5107(.A (n_2), .B (n_0), .Y (CO));
  sg13g2_o21ai_1 g91__6260(.A1 (B), .A2 (A), .B1 (CI), .Y (n_2));
  sg13g2_xnor2_1 g92__4319(.A (B), .B (A), .Y (n_1));
  sg13g2_nand2_1 g93__8428(.A (A), .B (B), .Y (n_0));
endmodule

