#TCLMODE
add_mapped_points {clk} {clk} -type PI PI
add_mapped_points {rst_n} {rst_n} -type PI PI
add_mapped_points {serial_in} {serial_in} -type PI PI
add_mapped_points {p_o[7]} {p_o[7]} -type PO PO
add_mapped_points {p_o[6]} {p_o[6]} -type PO PO
add_mapped_points {p_o[5]} {p_o[5]} -type PO PO
add_mapped_points {p_o[4]} {p_o[4]} -type PO PO
add_mapped_points {p_o[3]} {p_o[3]} -type PO PO
add_mapped_points {p_o[2]} {p_o[2]} -type PO PO
add_mapped_points {p_o[1]} {p_o[1]} -type PO PO
add_mapped_points {p_o[0]} {p_o[0]} -type PO PO
add_mapped_points {shift_reg_reg[7]/Q} {shift_reg_reg[7]/Q} -type DFF DFF
add_mapped_points {shift_reg_reg[6]/Q} {shift_reg_reg[6]/Q} -type DFF DFF
add_mapped_points {shift_reg_reg[5]/Q} {shift_reg_reg[5]/Q} -type DFF DFF
add_mapped_points {shift_reg_reg[4]/Q} {shift_reg_reg[4]/Q} -type DFF DFF
add_mapped_points {shift_reg_reg[3]/Q} {shift_reg_reg[3]/Q} -type DFF DFF
add_mapped_points {shift_reg_reg[2]/Q} {shift_reg_reg[2]/Q} -type DFF DFF
add_mapped_points {shift_reg_reg[1]/Q} {shift_reg_reg[1]/Q} -type DFF DFF
add_mapped_points {shift_reg_reg[0]/Q} {shift_reg_reg[0]/Q} -type DFF DFF
