
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jun 17 2025 00:38:31 CEST (Jun 16 2025 22:38:31 UTC)

// Verification Directory fv/dffsrq 

module dffsrq(SET, RST, CK, D, Q);
  input SET, RST, CK, D;
  output Q;
  wire SET, RST, CK, D;
  wire Q;
  wire UNCONNECTED, n_0, n_1;
  sg13g2_sdfbbp_1 q_reg_reg(.RESET_B (n_0), .SET_B (n_1), .CLK (CK), .D
       (D), .SCD (1'b0), .SCE (1'b0), .Q (Q), .Q_N (UNCONNECTED));
  sg13g2_nand2_1 g25__2398(.A (n_0), .B (SET), .Y (n_1));
  sg13g2_inv_1 g26(.A (RST), .Y (n_0));
endmodule

