
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jul  6 2025 22:39:04 CEST (Jul  6 2025 20:39:04 UTC)

// Verification Directory fv/DFFR 

module DFFR(RST, CK, D, Q, QN);
  input RST, CK, D;
  output Q, QN;
  wire RST, CK, D;
  wire Q, QN;
  wire n_0;
  INJIX0 g4(.A (Q), .Q (QN));
  DFRRQJIX1 q_reg_reg(.RN (n_0), .C (CK), .D (D), .Q (Q));
  INJIX0 g6(.A (RST), .Q (n_0));
endmodule

