
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jun 14 2025 16:42:19 CEST (Jun 14 2025 14:42:19 UTC)

// Verification Directory fv/DFFR1 

module DFFR(RST, CK, D, Q, QN);
  input RST, CK, D;
  output Q, QN;
  wire RST, CK, D;
  wire Q, QN;
  wire n_0;
  sg13g2_dfrbp_1 q_reg_reg(.RESET_B (n_0), .CLK (CK), .D (D), .Q (Q),
       .Q_N (QN));
  sg13g2_inv_1 g6(.A (RST), .Y (n_0));
endmodule

