
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Jun 25 2025 19:22:26 EDT (Jun 25 2025 23:22:26 UTC)

// Verification Directory fv/MULTI_MODE_DFFSRQ 

module DFFSRQ(SET, RST, CK, D, Q);
  input SET, RST, CK, D;
  output Q;
  wire SET, RST, CK, D;
  wire Q;
  wire UNCONNECTED, n_1, n_2;
  sg13g2_sdfbbp_1 q_reg_reg(.RESET_B (n_1), .SET_B (n_2), .CLK (CK), .D
       (D), .SCD (1'b0), .SCE (1'b0), .Q (Q), .Q_N (UNCONNECTED));
  sg13g2_nand2_1 g25__2398(.A (n_1), .B (SET), .Y (n_2));
  sg13g2_inv_1 g26(.A (RST), .Y (n_1));
endmodule

module MULTI_MODE_DFFSRQ(SET, RST, CK, D, Q, mode);
  input SET, RST, CK, D;
  input [0:1] mode;
  output Q;
  wire SET, RST, CK, D;
  wire [0:1] mode;
  wire Q;
  wire post_rst, post_set;
  DFFSRQ FF_CORE(.SET (post_set), .RST (post_rst), .CK (CK), .D (D), .Q
       (Q));
  sg13g2_xor2_1 g31__5107(.A (mode[1]), .B (SET), .X (post_set));
  sg13g2_xor2_1 g32__6260(.A (mode[0]), .B (RST), .X (post_rst));
endmodule

