
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jul  6 2025 23:05:42 CEST (Jul  6 2025 21:05:42 UTC)

// Verification Directory fv/MULTI_MODE_DFFSRQ 

module DFFSRQ(SET, RST, CK, D, Q);
  input SET, RST, CK, D;
  output Q;
  wire SET, RST, CK, D;
  wire Q;
  wire n_0, n_1;
  DFRRSQJIX1 q_reg_reg(.RN (n_0), .SN (n_1), .C (CK), .D (D), .Q (Q));
  INVJIX0 g25(.A (SET), .Q (n_1));
  INVJIX0 g26(.A (RST), .Q (n_0));
endmodule

module MULTI_MODE_DFFSRQ(SET, RST, CK, D, Q, mode);
  input SET, RST, CK, D;
  input [0:1] mode;
  output Q;
  wire SET, RST, CK, D;
  wire [0:1] mode;
  wire Q;
  wire post_rst, post_set;
  DFFSRQ FF_CORE(.SET (post_set), .RST (post_rst), .CK (CK), .D (D), .Q
       (Q));
  EO2JIX0 g31__2398(.A (SET), .B (mode[1]), .Q (post_set));
  EO2JIX0 g32__5107(.A (RST), .B (mode[0]), .Q (post_rst));
endmodule

