
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jul  4 2025 22:27:03 CEST (Jul  4 2025 20:27:03 UTC)

// Verification Directory fv/GPIO 

module GPIO(A, Y, PAD, DIR);
  input A, DIR;
  output Y;
  inout PAD;
  wire A, DIR;
  wire Y;
  wire PAD;
  wire n_4;
  bufif1 g1 (Y, PAD, DIR);
  bufif1 g2 (PAD, A, n_4);
  not g3 (n_4, DIR);
endmodule

