
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jun 13 2025 22:27:34 CEST (Jun 13 2025 20:27:34 UTC)

// Verification Directory fv/GPIO 
//use in opefpga simulation + Xcelium
//`include "../../../../../ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v"
//`include "../../../../../ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v"

// use in genus synthesis
//`include "../../ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v"


module GPIO(A, Y, PAD, DIR);
  input A, DIR;
  output Y;
  inout PAD;
  wire A, DIR;
  wire Y;
  wire PAD;
  wire c2p_en, p2c;
  sg13g2_IOPadInOut30mA pad_cell(.pad (PAD), .c2p (A), .c2p_en
       (c2p_en), .p2c (p2c));
  sg13g2_ebufn_2 g2__5107(.A (p2c), .TE_B (c2p_en), .Z (Y));
  sg13g2_inv_1 g7(.A (DIR), .Y (c2p_en));
endmodule

module GPIN (
  inout A, // External PAD signal
  output Y // Data input
);
  sg13g2_IOPadIn gpin(.pad(A), .p2c(Y));
endmodule

module GPOUT (
  inout Y, // External PAD signal
  input A // Data output
);
  sg13g2_IOPadOut30mA gpout(.pad(Y), .c2p(A));
endmodule
