
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Aug  7 2025 21:21:25 CEST (Aug  7 2025 19:21:25 UTC)

// Verification Directory fv/Main 

module
     ActivationMultiplier_6_IN_WIDTH8_NUM_UNITS6_ACTIVATION_WIDTH8(\activation[0]
     , \activation[1] , \activation[2] , \activation[3] ,
     \activation[4] , \activation[5] , \weight[0] , \weight[1] ,
     \weight[2] , \weight[3] , \weight[4] , \weight[5] , clk, rst,
     start, \result[0] , \result[1] , \result[2] , \result[3] ,
     \result[4] , \result[5] , en, \DFT_/sdi , \DFT_/sen );
  input [7:0] \activation[0] , \activation[1] , \activation[2] ,
       \activation[3] , \activation[4] , \activation[5] , \weight[0] ,
       \weight[1] , \weight[2] , \weight[3] , \weight[4] , \weight[5] ;
  input clk, rst, start, \DFT_/sdi , \DFT_/sen ;
  output [7:0] \result[0] , \result[1] , \result[2] , \result[3] ,
       \result[4] , \result[5] ;
  output en;
  wire [7:0] \activation[0] , \activation[1] , \activation[2] ,
       \activation[3] , \activation[4] , \activation[5] , \weight[0] ,
       \weight[1] , \weight[2] , \weight[3] , \weight[4] , \weight[5] ;
  wire clk, rst, start, \DFT_/sdi , \DFT_/sen ;
  wire [7:0] \result[0] , \result[1] , \result[2] , \result[3] ,
       \result[4] , \result[5] ;
  wire en;
  wire [7:0] \am_result[0] ;
  wire [7:0] \am_result[1] ;
  wire [7:0] \am_result[2] ;
  wire [7:0] \am_result[3] ;
  wire [7:0] \am_result[4] ;
  wire [7:0] \am_result[5] ;
  wire [7:0] \activation_reg[4] ;
  wire [7:0] \activation_reg[1] ;
  wire [7:0] \activation_reg[3] ;
  wire [7:0] \activation_reg[5] ;
  wire [7:0] \activation_reg[0] ;
  wire [7:0] \activation_reg[2] ;
  wire [3:0] cycle_counter;
  wire en_542, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192;
  assign \result[5] [5] = 1'b0;
  assign \result[5] [6] = 1'b0;
  assign \result[5] [7] = 1'b0;
  assign \result[4] [5] = 1'b0;
  assign \result[4] [6] = 1'b0;
  assign \result[4] [7] = 1'b0;
  assign \result[3] [5] = 1'b0;
  assign \result[3] [6] = 1'b0;
  assign \result[3] [7] = 1'b0;
  assign \result[2] [5] = 1'b0;
  assign \result[2] [6] = 1'b0;
  assign \result[2] [7] = 1'b0;
  assign \result[1] [5] = 1'b0;
  assign \result[1] [6] = 1'b0;
  assign \result[1] [7] = 1'b0;
  assign \result[0] [5] = 1'b0;
  assign \result[0] [6] = 1'b0;
  assign \result[0] [7] = 1'b0;
  ActivationMultiplier_IN_WIDTH8 \AM_INST[0].am (.weight (\weight[0] ),
       .activation (n_184), .en (en_542), .result (\am_result[0] ));
  ActivationMultiplier_IN_WIDTH8 \AM_INST[1].am (.weight (\weight[1] ),
       .activation (n_188), .en (en_542), .result (\am_result[1] ));
  ActivationMultiplier_IN_WIDTH8 \AM_INST[2].am (.weight (\weight[2] ),
       .activation (n_187), .en (en_542), .result (\am_result[2] ));
  ActivationMultiplier_IN_WIDTH8 \AM_INST[3].am (.weight (\weight[3] ),
       .activation (n_186), .en (en_542), .result (\am_result[3] ));
  ActivationMultiplier_IN_WIDTH8 \AM_INST[4].am (.weight (\weight[4] ),
       .activation (n_185), .en (en_542), .result (\am_result[4] ));
  ActivationMultiplier_IN_WIDTH8 \AM_INST[5].am (.weight (\weight[5] ),
       .activation (n_189), .en (en_542), .result (\am_result[5] ));
  BUFJIX1 g2407(.A (en_542), .Q (en));
  INJIX0 g2406(.A (rst), .Q (n_180));
  NA4JIX0 g3309__2398(.A (n_169), .B (n_171), .C (n_165), .D (n_160),
       .Q (n_184));
  NA4JIX0 g3310__5107(.A (n_167), .B (n_163), .C (n_179), .D (n_157),
       .Q (n_185));
  NA4JIX0 g3311__6260(.A (n_172), .B (n_175), .C (n_177), .D (n_159),
       .Q (n_186));
  NA4JIX0 g3312__4319(.A (n_173), .B (n_176), .C (n_174), .D (n_161),
       .Q (n_189));
  NA4JIX0 g3313__8428(.A (n_168), .B (n_162), .C (n_166), .D (n_158),
       .Q (n_187));
  NA4JIX0 g3314__5526(.A (n_164), .B (n_178), .C (n_170), .D (n_156),
       .Q (n_188));
  AN22JIX0 g3315__6783(.A (n_151), .B (\activation_reg[4] [1]), .C
       (n_147), .D (\activation_reg[4] [0]), .Q (n_179));
  AN22JIX0 g3316__3680(.A (n_152), .B (\activation_reg[1] [7]), .C
       (n_155), .D (\activation_reg[1] [3]), .Q (n_178));
  AN22JIX0 g3317__1617(.A (n_151), .B (\activation_reg[3] [1]), .C
       (n_147), .D (\activation_reg[3] [0]), .Q (n_177));
  AN22JIX0 g3318__2802(.A (n_152), .B (\activation_reg[5] [7]), .C
       (n_155), .D (\activation_reg[5] [3]), .Q (n_176));
  AN22JIX0 g3319__1705(.A (n_152), .B (\activation_reg[3] [7]), .C
       (n_155), .D (\activation_reg[3] [3]), .Q (n_175));
  AN22JIX0 g3320__5122(.A (n_151), .B (\activation_reg[5] [1]), .C
       (n_147), .D (\activation_reg[5] [0]), .Q (n_174));
  AN22JIX0 g3321__8246(.A (n_153), .B (\activation_reg[5] [6]), .C
       (n_154), .D (\activation_reg[5] [2]), .Q (n_173));
  AN22JIX0 g3322__7098(.A (n_153), .B (\activation_reg[3] [6]), .C
       (n_154), .D (\activation_reg[3] [2]), .Q (n_172));
  AN22JIX0 g3323__6131(.A (n_152), .B (\activation_reg[0] [7]), .C
       (n_155), .D (\activation_reg[0] [3]), .Q (n_171));
  AN22JIX0 g3324__1881(.A (n_151), .B (\activation_reg[1] [1]), .C
       (n_147), .D (\activation_reg[1] [0]), .Q (n_170));
  AN22JIX0 g3325__5115(.A (n_153), .B (\activation_reg[0] [6]), .C
       (n_154), .D (\activation_reg[0] [2]), .Q (n_169));
  AN22JIX0 g3326__7482(.A (n_153), .B (\activation_reg[2] [6]), .C
       (n_154), .D (\activation_reg[2] [2]), .Q (n_168));
  AN22JIX0 g3327__4733(.A (n_153), .B (\activation_reg[4] [6]), .C
       (n_154), .D (\activation_reg[4] [2]), .Q (n_167));
  AN22JIX0 g3328__6161(.A (n_151), .B (\activation_reg[2] [1]), .C
       (n_147), .D (\activation_reg[2] [0]), .Q (n_166));
  AN22JIX0 g3329__9315(.A (n_151), .B (\activation_reg[0] [1]), .C
       (n_147), .D (\activation_reg[0] [0]), .Q (n_165));
  AN22JIX0 g3330__9945(.A (n_153), .B (\activation_reg[1] [6]), .C
       (n_154), .D (\activation_reg[1] [2]), .Q (n_164));
  AN22JIX0 g3331__2883(.A (n_152), .B (\activation_reg[4] [7]), .C
       (n_155), .D (\activation_reg[4] [3]), .Q (n_163));
  AN22JIX0 g3332__2346(.A (n_152), .B (\activation_reg[2] [7]), .C
       (n_155), .D (\activation_reg[2] [3]), .Q (n_162));
  AN22JIX0 g3333__1666(.A (n_149), .B (\activation_reg[5] [5]), .C
       (n_146), .D (\activation_reg[5] [4]), .Q (n_161));
  AN22JIX0 g3334__7410(.A (n_149), .B (\activation_reg[0] [5]), .C
       (n_146), .D (\activation_reg[0] [4]), .Q (n_160));
  AN22JIX0 g3335__6417(.A (n_149), .B (\activation_reg[3] [5]), .C
       (n_146), .D (\activation_reg[3] [4]), .Q (n_159));
  AN22JIX0 g3336__5477(.A (n_149), .B (\activation_reg[2] [5]), .C
       (n_146), .D (\activation_reg[2] [4]), .Q (n_158));
  AN22JIX0 g3337__2398(.A (n_149), .B (\activation_reg[4] [5]), .C
       (n_146), .D (\activation_reg[4] [4]), .Q (n_157));
  AN22JIX0 g3338__5107(.A (n_149), .B (\activation_reg[1] [5]), .C
       (n_146), .D (\activation_reg[1] [4]), .Q (n_156));
  AND2JIX0 g3339__6260(.A (n_150), .B (cycle_counter[2]), .Q (n_155));
  AND2JIX0 g3340__4319(.A (n_148), .B (cycle_counter[2]), .Q (n_154));
  NO2I1JIX0 g3341__8428(.AN (n_148), .B (cycle_counter[2]), .Q (n_153));
  NO2I1JIX0 g3342__5526(.AN (n_150), .B (cycle_counter[2]), .Q (n_152));
  AND3JIX0 g3343__6783(.A (n_144), .B (cycle_counter[2]), .C
       (cycle_counter[1]), .Q (n_151));
  NO2I1JIX0 g3344__3680(.AN (n_144), .B (cycle_counter[1]), .Q (n_150));
  NO2I1JIX0 g3345__1617(.AN (n_144), .B (n_190), .Q (n_149));
  INVJIX0 g3346(.A (n_192), .Q (n_147));
  INVJIX0 g3347(.A (n_146), .Q (n_191));
  NO2JIX0 g3348__2802(.A (n_145), .B (cycle_counter[1]), .Q (n_148));
  NO2JIX0 g3350__1705(.A (n_145), .B (n_190), .Q (n_146));
  NA2I1JIX0 g3352__5122(.AN (cycle_counter[3]), .B (cycle_counter[0]),
       .Q (n_145));
  NO2JIX0 g3353__8246(.A (cycle_counter[3]), .B (cycle_counter[0]), .Q
       (n_144));
  NA2I1JIX0 g3354__7098(.AN (cycle_counter[2]), .B (cycle_counter[1]),
       .Q (n_190));
  NA3I1JIX0 g2__6131(.AN (n_145), .B (cycle_counter[1]), .C
       (cycle_counter[2]), .Q (n_192));
  SDFRRQJIX1 \activation_reg_reg[0][0] (.RN (n_180), .C (clk), .D
       (n_104), .SD (\DFT_/sdi ), .SE (\DFT_/sen ), .Q
       (\activation_reg[0] [0]));
  SDFRRQJIX1 \activation_reg_reg[0][1] (.RN (n_180), .C (clk), .D
       (n_109), .SD (\activation_reg[0] [0]), .SE (\DFT_/sen ), .Q
       (\activation_reg[0] [1]));
  SDFRRQJIX1 \activation_reg_reg[0][2] (.RN (n_180), .C (clk), .D
       (n_107), .SD (\activation_reg[0] [1]), .SE (\DFT_/sen ), .Q
       (\activation_reg[0] [2]));
  SDFRRQJIX1 \activation_reg_reg[0][3] (.RN (n_180), .C (clk), .D
       (n_106), .SD (\activation_reg[0] [2]), .SE (\DFT_/sen ), .Q
       (\activation_reg[0] [3]));
  SDFRRQJIX1 \activation_reg_reg[0][4] (.RN (n_180), .C (clk), .D
       (n_105), .SD (\activation_reg[0] [3]), .SE (\DFT_/sen ), .Q
       (\activation_reg[0] [4]));
  SDFRRQJIX1 \activation_reg_reg[0][5] (.RN (n_180), .C (clk), .D
       (n_103), .SD (\activation_reg[0] [4]), .SE (\DFT_/sen ), .Q
       (\activation_reg[0] [5]));
  SDFRRQJIX1 \activation_reg_reg[0][6] (.RN (n_180), .C (clk), .D
       (n_100), .SD (\activation_reg[0] [5]), .SE (\DFT_/sen ), .Q
       (\activation_reg[0] [6]));
  SDFRRQJIX1 \activation_reg_reg[0][7] (.RN (n_180), .C (clk), .D
       (n_102), .SD (\activation_reg[0] [6]), .SE (\DFT_/sen ), .Q
       (\activation_reg[0] [7]));
  SDFRRQJIX1 \activation_reg_reg[1][0] (.RN (n_180), .C (clk), .D
       (n_101), .SD (\activation_reg[0] [7]), .SE (\DFT_/sen ), .Q
       (\activation_reg[1] [0]));
  SDFRRQJIX1 \activation_reg_reg[1][1] (.RN (n_180), .C (clk), .D
       (n_99), .SD (\activation_reg[1] [0]), .SE (\DFT_/sen ), .Q
       (\activation_reg[1] [1]));
  SDFRRQJIX1 \activation_reg_reg[1][2] (.RN (n_180), .C (clk), .D
       (n_98), .SD (\activation_reg[1] [1]), .SE (\DFT_/sen ), .Q
       (\activation_reg[1] [2]));
  SDFRRQJIX1 \activation_reg_reg[1][3] (.RN (n_180), .C (clk), .D
       (n_97), .SD (\activation_reg[1] [2]), .SE (\DFT_/sen ), .Q
       (\activation_reg[1] [3]));
  SDFRRQJIX1 \activation_reg_reg[1][4] (.RN (n_180), .C (clk), .D
       (n_96), .SD (\activation_reg[1] [3]), .SE (\DFT_/sen ), .Q
       (\activation_reg[1] [4]));
  SDFRRQJIX1 \activation_reg_reg[1][5] (.RN (n_180), .C (clk), .D
       (n_95), .SD (\activation_reg[1] [4]), .SE (\DFT_/sen ), .Q
       (\activation_reg[1] [5]));
  SDFRRQJIX1 \activation_reg_reg[1][6] (.RN (n_180), .C (clk), .D
       (n_94), .SD (\activation_reg[1] [5]), .SE (\DFT_/sen ), .Q
       (\activation_reg[1] [6]));
  SDFRRQJIX1 \activation_reg_reg[1][7] (.RN (n_180), .C (clk), .D
       (n_93), .SD (\activation_reg[1] [6]), .SE (\DFT_/sen ), .Q
       (\activation_reg[1] [7]));
  SDFRRQJIX1 \activation_reg_reg[2][0] (.RN (n_180), .C (clk), .D
       (n_92), .SD (\activation_reg[1] [7]), .SE (\DFT_/sen ), .Q
       (\activation_reg[2] [0]));
  SDFRRQJIX1 \activation_reg_reg[2][1] (.RN (n_180), .C (clk), .D
       (n_91), .SD (\activation_reg[2] [0]), .SE (\DFT_/sen ), .Q
       (\activation_reg[2] [1]));
  SDFRRQJIX1 \activation_reg_reg[2][2] (.RN (n_180), .C (clk), .D
       (n_90), .SD (\activation_reg[2] [1]), .SE (\DFT_/sen ), .Q
       (\activation_reg[2] [2]));
  SDFRRQJIX1 \activation_reg_reg[2][3] (.RN (n_180), .C (clk), .D
       (n_89), .SD (\activation_reg[2] [2]), .SE (\DFT_/sen ), .Q
       (\activation_reg[2] [3]));
  SDFRRQJIX1 \activation_reg_reg[2][4] (.RN (n_180), .C (clk), .D
       (n_88), .SD (\activation_reg[2] [3]), .SE (\DFT_/sen ), .Q
       (\activation_reg[2] [4]));
  SDFRRQJIX1 \activation_reg_reg[2][5] (.RN (n_180), .C (clk), .D
       (n_87), .SD (\activation_reg[2] [4]), .SE (\DFT_/sen ), .Q
       (\activation_reg[2] [5]));
  SDFRRQJIX1 \activation_reg_reg[2][6] (.RN (n_180), .C (clk), .D
       (n_132), .SD (\activation_reg[2] [5]), .SE (\DFT_/sen ), .Q
       (\activation_reg[2] [6]));
  SDFRRQJIX1 \activation_reg_reg[2][7] (.RN (n_180), .C (clk), .D
       (n_134), .SD (\activation_reg[2] [6]), .SE (\DFT_/sen ), .Q
       (\activation_reg[2] [7]));
  SDFRRQJIX1 \activation_reg_reg[3][0] (.RN (n_180), .C (clk), .D
       (n_133), .SD (\activation_reg[2] [7]), .SE (\DFT_/sen ), .Q
       (\activation_reg[3] [0]));
  SDFRRQJIX1 \activation_reg_reg[3][1] (.RN (n_180), .C (clk), .D
       (n_131), .SD (\activation_reg[3] [0]), .SE (\DFT_/sen ), .Q
       (\activation_reg[3] [1]));
  SDFRRQJIX1 \activation_reg_reg[3][2] (.RN (n_180), .C (clk), .D
       (n_130), .SD (\activation_reg[3] [1]), .SE (\DFT_/sen ), .Q
       (\activation_reg[3] [2]));
  SDFRRQJIX1 \activation_reg_reg[3][3] (.RN (n_180), .C (clk), .D
       (n_129), .SD (\activation_reg[3] [2]), .SE (\DFT_/sen ), .Q
       (\activation_reg[3] [3]));
  SDFRRQJIX1 \activation_reg_reg[3][4] (.RN (n_180), .C (clk), .D
       (n_136), .SD (\activation_reg[3] [3]), .SE (\DFT_/sen ), .Q
       (\activation_reg[3] [4]));
  SDFRRQJIX1 \activation_reg_reg[3][5] (.RN (n_180), .C (clk), .D
       (n_127), .SD (\activation_reg[3] [4]), .SE (\DFT_/sen ), .Q
       (\activation_reg[3] [5]));
  SDFRRQJIX1 \activation_reg_reg[3][6] (.RN (n_180), .C (clk), .D
       (n_126), .SD (\activation_reg[3] [5]), .SE (\DFT_/sen ), .Q
       (\activation_reg[3] [6]));
  SDFRRQJIX1 \activation_reg_reg[3][7] (.RN (n_180), .C (clk), .D
       (n_125), .SD (\activation_reg[3] [6]), .SE (\DFT_/sen ), .Q
       (\activation_reg[3] [7]));
  SDFRRQJIX1 \activation_reg_reg[4][0] (.RN (n_180), .C (clk), .D
       (n_124), .SD (\activation_reg[3] [7]), .SE (\DFT_/sen ), .Q
       (\activation_reg[4] [0]));
  SDFRRQJIX1 \activation_reg_reg[4][1] (.RN (n_180), .C (clk), .D
       (n_123), .SD (\activation_reg[4] [0]), .SE (\DFT_/sen ), .Q
       (\activation_reg[4] [1]));
  SDFRRQJIX1 \activation_reg_reg[4][2] (.RN (n_180), .C (clk), .D
       (n_122), .SD (\activation_reg[4] [1]), .SE (\DFT_/sen ), .Q
       (\activation_reg[4] [2]));
  SDFRRQJIX1 \activation_reg_reg[4][3] (.RN (n_180), .C (clk), .D
       (n_121), .SD (\activation_reg[4] [2]), .SE (\DFT_/sen ), .Q
       (\activation_reg[4] [3]));
  SDFRRQJIX1 \activation_reg_reg[4][4] (.RN (n_180), .C (clk), .D
       (n_120), .SD (\activation_reg[4] [3]), .SE (\DFT_/sen ), .Q
       (\activation_reg[4] [4]));
  SDFRRQJIX1 \activation_reg_reg[4][5] (.RN (n_180), .C (clk), .D
       (n_119), .SD (\activation_reg[4] [4]), .SE (\DFT_/sen ), .Q
       (\activation_reg[4] [5]));
  SDFRRQJIX1 \activation_reg_reg[4][6] (.RN (n_180), .C (clk), .D
       (n_118), .SD (\activation_reg[4] [5]), .SE (\DFT_/sen ), .Q
       (\activation_reg[4] [6]));
  SDFRRQJIX1 \activation_reg_reg[4][7] (.RN (n_180), .C (clk), .D
       (n_117), .SD (\activation_reg[4] [6]), .SE (\DFT_/sen ), .Q
       (\activation_reg[4] [7]));
  SDFRRQJIX1 \activation_reg_reg[5][0] (.RN (n_180), .C (clk), .D
       (n_116), .SD (\activation_reg[4] [7]), .SE (\DFT_/sen ), .Q
       (\activation_reg[5] [0]));
  SDFRRQJIX1 \activation_reg_reg[5][1] (.RN (n_180), .C (clk), .D
       (n_115), .SD (\activation_reg[5] [0]), .SE (\DFT_/sen ), .Q
       (\activation_reg[5] [1]));
  SDFRRQJIX1 \activation_reg_reg[5][2] (.RN (n_180), .C (clk), .D
       (n_114), .SD (\activation_reg[5] [1]), .SE (\DFT_/sen ), .Q
       (\activation_reg[5] [2]));
  SDFRRQJIX1 \activation_reg_reg[5][3] (.RN (n_180), .C (clk), .D
       (n_113), .SD (\activation_reg[5] [2]), .SE (\DFT_/sen ), .Q
       (\activation_reg[5] [3]));
  SDFRRQJIX1 \activation_reg_reg[5][4] (.RN (n_180), .C (clk), .D
       (n_112), .SD (\activation_reg[5] [3]), .SE (\DFT_/sen ), .Q
       (\activation_reg[5] [4]));
  SDFRRQJIX1 \activation_reg_reg[5][5] (.RN (n_180), .C (clk), .D
       (n_111), .SD (\activation_reg[5] [4]), .SE (\DFT_/sen ), .Q
       (\activation_reg[5] [5]));
  SDFRRQJIX1 \activation_reg_reg[5][6] (.RN (n_180), .C (clk), .D
       (n_110), .SD (\activation_reg[5] [5]), .SE (\DFT_/sen ), .Q
       (\activation_reg[5] [6]));
  SDFRRQJIX1 \activation_reg_reg[5][7] (.RN (n_180), .C (clk), .D
       (n_108), .SD (\activation_reg[5] [6]), .SE (\DFT_/sen ), .Q
       (\activation_reg[5] [7]));
  SDFRRQJIX1 \cycle_counter_reg[0] (.RN (n_180), .C (clk), .D (n_128),
       .SD (\activation_reg[5] [7]), .SE (\DFT_/sen ), .Q
       (cycle_counter[0]));
  SDFRRQJIX1 \cycle_counter_reg[1] (.RN (n_180), .C (clk), .D (n_140),
       .SD (cycle_counter[0]), .SE (\DFT_/sen ), .Q (cycle_counter[1]));
  SDFRRQJIX1 \cycle_counter_reg[2] (.RN (n_180), .C (clk), .D (n_142),
       .SD (cycle_counter[1]), .SE (\DFT_/sen ), .Q (cycle_counter[2]));
  SDFRRQJIX1 \cycle_counter_reg[3] (.RN (n_180), .C (clk), .D (n_141),
       .SD (cycle_counter[2]), .SE (\DFT_/sen ), .Q (cycle_counter[3]));
  SDFRRQJIX1 en_reg(.RN (n_180), .C (clk), .D (n_143), .SD
       (cycle_counter[3]), .SE (\DFT_/sen ), .Q (en_542));
  SDFRRSJIX1 \result_reg[0][0] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_75), .SD (en_542), .SE (\DFT_/sen ), .Q (\result[0] [0]), .QN
       (n_17));
  SDFRRSJIX1 \result_reg[0][1] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_74), .SD (n_17), .SE (\DFT_/sen ), .Q (\result[0] [1]), .QN
       (n_16));
  SDFRRSJIX1 \result_reg[0][2] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_79), .SD (n_16), .SE (\DFT_/sen ), .Q (\result[0] [2]), .QN
       (n_15));
  SDFRRQJIX1 \result_reg[0][3] (.RN (n_180), .C (clk), .D (n_73), .SD
       (n_15), .SE (\DFT_/sen ), .Q (\result[0] [3]));
  SDFRRQJIX1 \result_reg[0][4] (.RN (n_180), .C (clk), .D (n_72), .SD
       (\result[0] [3]), .SE (\DFT_/sen ), .Q (\result[0] [4]));
  SDFRRSJIX1 \result_reg[1][0] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_78), .SD (\result[0] [4]), .SE (\DFT_/sen ), .Q
       (\result[1] [0]), .QN (n_14));
  SDFRRSJIX1 \result_reg[1][1] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_56), .SD (n_14), .SE (\DFT_/sen ), .Q (\result[1] [1]), .QN
       (n_13));
  SDFRRSJIX1 \result_reg[1][2] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_70), .SD (n_13), .SE (\DFT_/sen ), .Q (\result[1] [2]), .QN
       (n_12));
  SDFRRQJIX1 \result_reg[1][3] (.RN (n_180), .C (clk), .D (n_64), .SD
       (n_12), .SE (\DFT_/sen ), .Q (\result[1] [3]));
  SDFRRQJIX1 \result_reg[1][4] (.RN (n_180), .C (clk), .D (n_69), .SD
       (\result[1] [3]), .SE (\DFT_/sen ), .Q (\result[1] [4]));
  SDFRRSJIX1 \result_reg[2][0] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_57), .SD (\result[1] [4]), .SE (\DFT_/sen ), .Q
       (\result[2] [0]), .QN (n_11));
  SDFRRSJIX1 \result_reg[2][1] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_67), .SD (n_11), .SE (\DFT_/sen ), .Q (\result[2] [1]), .QN
       (n_10));
  SDFRRSJIX1 \result_reg[2][2] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_66), .SD (n_10), .SE (\DFT_/sen ), .Q (\result[2] [2]), .QN
       (n_9));
  SDFRRQJIX1 \result_reg[2][3] (.RN (n_180), .C (clk), .D (n_65), .SD
       (n_9), .SE (\DFT_/sen ), .Q (\result[2] [3]));
  SDFRRQJIX1 \result_reg[2][4] (.RN (n_180), .C (clk), .D (n_68), .SD
       (\result[2] [3]), .SE (\DFT_/sen ), .Q (\result[2] [4]));
  SDFRRSJIX1 \result_reg[3][0] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_63), .SD (\result[2] [4]), .SE (\DFT_/sen ), .Q
       (\result[3] [0]), .QN (n_8));
  SDFRRSJIX1 \result_reg[3][1] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_61), .SD (n_8), .SE (\DFT_/sen ), .Q (\result[3] [1]), .QN
       (n_7));
  SDFRRSJIX1 \result_reg[3][2] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_59), .SD (n_7), .SE (\DFT_/sen ), .Q (\result[3] [2]), .QN
       (n_6));
  SDFRRQJIX1 \result_reg[3][3] (.RN (n_180), .C (clk), .D (n_62), .SD
       (n_6), .SE (\DFT_/sen ), .Q (\result[3] [3]));
  SDFRRQJIX1 \result_reg[3][4] (.RN (n_180), .C (clk), .D (n_60), .SD
       (\result[3] [3]), .SE (\DFT_/sen ), .Q (\result[3] [4]));
  SDFRRSJIX1 \result_reg[4][0] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_80), .SD (\result[3] [4]), .SE (\DFT_/sen ), .Q
       (\result[4] [0]), .QN (n_5));
  SDFRRSJIX1 \result_reg[4][1] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_85), .SD (n_5), .SE (\DFT_/sen ), .Q (\result[4] [1]), .QN
       (n_4));
  SDFRRSJIX1 \result_reg[4][2] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_77), .SD (n_4), .SE (\DFT_/sen ), .Q (\result[4] [2]), .QN
       (n_3));
  SDFRRQJIX1 \result_reg[4][3] (.RN (n_180), .C (clk), .D (n_58), .SD
       (n_3), .SE (\DFT_/sen ), .Q (\result[4] [3]));
  SDFRRQJIX1 \result_reg[4][4] (.RN (n_180), .C (clk), .D (n_81), .SD
       (\result[4] [3]), .SE (\DFT_/sen ), .Q (\result[4] [4]));
  SDFRRSJIX1 \result_reg[5][0] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_83), .SD (\result[4] [4]), .SE (\DFT_/sen ), .Q
       (\result[5] [0]), .QN (n_2));
  SDFRRSJIX1 \result_reg[5][1] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_82), .SD (n_2), .SE (\DFT_/sen ), .Q (\result[5] [1]), .QN
       (n_1));
  SDFRRSJIX1 \result_reg[5][2] (.RN (n_180), .SN (1'b1), .C (clk), .D
       (n_71), .SD (n_1), .SE (\DFT_/sen ), .Q (\result[5] [2]), .QN
       (n_0));
  SDFRRQJIX1 \result_reg[5][3] (.RN (n_180), .C (clk), .D (n_84), .SD
       (n_0), .SE (\DFT_/sen ), .Q (\result[5] [3]));
  SDFRRQJIX1 \result_reg[5][4] (.RN (n_180), .C (clk), .D (n_76), .SD
       (\result[5] [3]), .SE (\DFT_/sen ), .Q (\result[5] [4]));
  AO21JIX0 g3409__1881(.A (n_135), .B (en_542), .C (n_40), .Q (n_143));
  ON21JIX0 g3411__5115(.A (n_191), .B (n_32), .C (n_139), .Q (n_142));
  ON21JIX0 g3412__7482(.A (n_192), .B (n_31), .C (n_138), .Q (n_141));
  AO32JIX0 g3439__4733(.A (n_35), .B (cycle_counter[0]), .C (n_49), .D
       (cycle_counter[1]), .E (n_86), .Q (n_140));
  NA2JIX0 g3440__6161(.A (n_137), .B (cycle_counter[2]), .Q (n_139));
  NA2JIX0 g3441__9315(.A (n_137), .B (cycle_counter[3]), .Q (n_138));
  AO22JIX0 g3465__9945(.A (n_40), .B (\activation[3] [4]), .C (n_51),
       .D (\activation_reg[3] [4]), .Q (n_136));
  NA4I1JIX0 g3466__2883(.AN (n_190), .B (cycle_counter[3]), .C
       (cycle_counter[0]), .D (1'b1), .Q (n_135));
  AO22JIX0 g3467__2346(.A (n_54), .B (\activation[2] [7]), .C (n_53),
       .D (\activation_reg[2] [7]), .Q (n_134));
  AO22JIX0 g3468__1666(.A (n_39), .B (\activation[3] [0]), .C (n_23),
       .D (\activation_reg[3] [0]), .Q (n_133));
  AO22JIX0 g3469__7410(.A (n_41), .B (\activation[2] [6]), .C (n_23),
       .D (\activation_reg[2] [6]), .Q (n_132));
  AO22JIX0 g3470__6417(.A (n_40), .B (\activation[3] [1]), .C (n_51),
       .D (\activation_reg[3] [1]), .Q (n_131));
  AO22JIX0 g3471__5477(.A (n_40), .B (\activation[3] [2]), .C (n_53),
       .D (\activation_reg[3] [2]), .Q (n_130));
  AO22JIX0 g3472__2398(.A (n_42), .B (\activation[3] [3]), .C (n_26),
       .D (\activation_reg[3] [3]), .Q (n_129));
  ON31JIX0 g3473__5107(.A (start), .B (n_35), .C (n_48), .D (n_55), .Q
       (n_128));
  AO21JIX0 g3495__6260(.A (n_49), .B (n_36), .C (n_86), .Q (n_137));
  AO22JIX0 g3505__4319(.A (n_39), .B (\activation[3] [5]), .C (n_51),
       .D (\activation_reg[3] [5]), .Q (n_127));
  AO22JIX0 g3506__8428(.A (n_54), .B (\activation[3] [6]), .C (n_23),
       .D (\activation_reg[3] [6]), .Q (n_126));
  AO22JIX0 g3507__5526(.A (n_43), .B (\activation[3] [7]), .C (n_52),
       .D (\activation_reg[3] [7]), .Q (n_125));
  AO22JIX0 g3508__6783(.A (n_42), .B (\activation[4] [0]), .C (n_50),
       .D (\activation_reg[4] [0]), .Q (n_124));
  AO22JIX0 g3509__3680(.A (n_41), .B (\activation[4] [1]), .C (n_23),
       .D (\activation_reg[4] [1]), .Q (n_123));
  AO22JIX0 g3510__1617(.A (n_45), .B (\activation[4] [2]), .C (n_23),
       .D (\activation_reg[4] [2]), .Q (n_122));
  AO22JIX0 g3511__2802(.A (n_45), .B (\activation[4] [3]), .C (n_23),
       .D (\activation_reg[4] [3]), .Q (n_121));
  AO22JIX0 g3512__1705(.A (n_42), .B (\activation[4] [4]), .C (n_51),
       .D (\activation_reg[4] [4]), .Q (n_120));
  AO22JIX0 g3513__5122(.A (n_39), .B (\activation[4] [5]), .C (n_53),
       .D (\activation_reg[4] [5]), .Q (n_119));
  AO22JIX0 g3514__8246(.A (n_41), .B (\activation[4] [6]), .C (n_26),
       .D (\activation_reg[4] [6]), .Q (n_118));
  AO22JIX0 g3515__7098(.A (n_44), .B (\activation[4] [7]), .C (n_23),
       .D (\activation_reg[4] [7]), .Q (n_117));
  AO22JIX0 g3516__6131(.A (n_44), .B (\activation[5] [0]), .C (n_51),
       .D (\activation_reg[5] [0]), .Q (n_116));
  AO22JIX0 g3517__1881(.A (n_43), .B (\activation[5] [1]), .C (n_25),
       .D (\activation_reg[5] [1]), .Q (n_115));
  AO22JIX0 g3518__5115(.A (n_42), .B (\activation[5] [2]), .C (n_52),
       .D (\activation_reg[5] [2]), .Q (n_114));
  AO22JIX0 g3519__7482(.A (n_42), .B (\activation[5] [3]), .C (n_25),
       .D (\activation_reg[5] [3]), .Q (n_113));
  AO22JIX0 g3520__4733(.A (n_39), .B (\activation[5] [4]), .C (n_27),
       .D (\activation_reg[5] [4]), .Q (n_112));
  AO22JIX0 g3521__6161(.A (n_42), .B (\activation[5] [5]), .C (n_27),
       .D (\activation_reg[5] [5]), .Q (n_111));
  AO22JIX0 g3522__9315(.A (n_43), .B (\activation[5] [6]), .C (n_52),
       .D (\activation_reg[5] [6]), .Q (n_110));
  AO22JIX0 g3523__9945(.A (n_44), .B (\activation[0] [1]), .C (n_51),
       .D (\activation_reg[0] [1]), .Q (n_109));
  AO22JIX0 g3524__2883(.A (n_43), .B (\activation[5] [7]), .C (n_51),
       .D (\activation_reg[5] [7]), .Q (n_108));
  AO22JIX0 g3525__2346(.A (n_40), .B (\activation[0] [2]), .C (n_25),
       .D (\activation_reg[0] [2]), .Q (n_107));
  AO22JIX0 g3526__1666(.A (n_54), .B (\activation[0] [3]), .C (n_26),
       .D (\activation_reg[0] [3]), .Q (n_106));
  AO22JIX0 g3527__7410(.A (n_45), .B (\activation[0] [4]), .C (n_50),
       .D (\activation_reg[0] [4]), .Q (n_105));
  AO22JIX0 g3528__6417(.A (n_41), .B (\activation[0] [0]), .C (n_27),
       .D (\activation_reg[0] [0]), .Q (n_104));
  AO22JIX0 g3529__5477(.A (n_54), .B (\activation[0] [5]), .C (n_27),
       .D (\activation_reg[0] [5]), .Q (n_103));
  AO22JIX0 g3530__2398(.A (n_44), .B (\activation[0] [7]), .C (n_25),
       .D (\activation_reg[0] [7]), .Q (n_102));
  AO22JIX0 g3531__5107(.A (n_45), .B (\activation[1] [0]), .C (n_26),
       .D (\activation_reg[1] [0]), .Q (n_101));
  AO22JIX0 g3532__6260(.A (n_41), .B (\activation[0] [6]), .C (n_52),
       .D (\activation_reg[0] [6]), .Q (n_100));
  AO22JIX0 g3533__4319(.A (n_44), .B (\activation[1] [1]), .C (n_53),
       .D (\activation_reg[1] [1]), .Q (n_99));
  AO22JIX0 g3534__8428(.A (n_43), .B (\activation[1] [2]), .C (n_52),
       .D (\activation_reg[1] [2]), .Q (n_98));
  AO22JIX0 g3535__5526(.A (n_39), .B (\activation[1] [3]), .C (n_27),
       .D (\activation_reg[1] [3]), .Q (n_97));
  AO22JIX0 g3536__6783(.A (n_40), .B (\activation[1] [4]), .C (n_25),
       .D (\activation_reg[1] [4]), .Q (n_96));
  AO22JIX0 g3537__3680(.A (n_41), .B (\activation[1] [5]), .C (n_53),
       .D (\activation_reg[1] [5]), .Q (n_95));
  AO22JIX0 g3538__1617(.A (n_42), .B (\activation[1] [6]), .C (n_52),
       .D (\activation_reg[1] [6]), .Q (n_94));
  AO22JIX0 g3539__2802(.A (n_43), .B (\activation[1] [7]), .C (n_26),
       .D (\activation_reg[1] [7]), .Q (n_93));
  AO22JIX0 g3540__1705(.A (n_39), .B (\activation[2] [0]), .C (n_26),
       .D (\activation_reg[2] [0]), .Q (n_92));
  AO22JIX0 g3541__5122(.A (n_39), .B (\activation[2] [1]), .C (n_52),
       .D (\activation_reg[2] [1]), .Q (n_91));
  AO22JIX0 g3542__8246(.A (n_41), .B (\activation[2] [2]), .C (n_52),
       .D (\activation_reg[2] [2]), .Q (n_90));
  AO22JIX0 g3543__7098(.A (n_40), .B (\activation[2] [3]), .C (n_25),
       .D (\activation_reg[2] [3]), .Q (n_89));
  AO22JIX0 g3544__6131(.A (n_54), .B (\activation[2] [4]), .C (n_27),
       .D (\activation_reg[2] [4]), .Q (n_88));
  AO22JIX0 g3545__1881(.A (n_45), .B (\activation[2] [5]), .C (n_53),
       .D (\activation_reg[2] [5]), .Q (n_87));
  AO22JIX0 g3546__5115(.A (n_29), .B (\result[4] [1]), .C (n_19), .D
       (\am_result[4] [1]), .Q (n_85));
  AO22JIX0 g3547__7482(.A (n_30), .B (\result[5] [3]), .C (n_34), .D
       (\am_result[5] [3]), .Q (n_84));
  AO22JIX0 g3548__4733(.A (n_21), .B (\result[5] [0]), .C (n_34), .D
       (\am_result[5] [0]), .Q (n_83));
  AO22JIX0 g3549__6161(.A (n_32), .B (\result[5] [1]), .C (n_37), .D
       (\am_result[5] [1]), .Q (n_82));
  AO22JIX0 g3550__9315(.A (n_29), .B (\result[4] [4]), .C (n_22), .D
       (\am_result[4] [4]), .Q (n_81));
  AO22JIX0 g3551__9945(.A (n_30), .B (\result[4] [0]), .C (n_34), .D
       (\am_result[4] [0]), .Q (n_80));
  AO22JIX0 g3552__2883(.A (n_31), .B (\result[0] [2]), .C (n_36), .D
       (\am_result[0] [2]), .Q (n_79));
  AO22JIX0 g3553__2346(.A (n_32), .B (\result[1] [0]), .C (n_37), .D
       (\am_result[1] [0]), .Q (n_78));
  AO22JIX0 g3554__1666(.A (n_29), .B (\result[4] [2]), .C (n_35), .D
       (\am_result[4] [2]), .Q (n_77));
  AO22JIX0 g3555__7410(.A (n_30), .B (\result[5] [4]), .C (n_34), .D
       (\am_result[5] [4]), .Q (n_76));
  AO22JIX0 g3556__6417(.A (n_31), .B (\result[0] [0]), .C (n_36), .D
       (\am_result[0] [0]), .Q (n_75));
  AO22JIX0 g3557__5477(.A (n_32), .B (\result[0] [1]), .C (n_37), .D
       (\am_result[0] [1]), .Q (n_74));
  AO22JIX0 g3558__2398(.A (n_29), .B (\result[0] [3]), .C (n_22), .D
       (\am_result[0] [3]), .Q (n_73));
  AO22JIX0 g3559__5107(.A (n_30), .B (\result[0] [4]), .C (n_18), .D
       (\am_result[0] [4]), .Q (n_72));
  ON21JIX0 g3560__6260(.A (n_34), .B (start), .C (n_55), .Q (n_86));
  AO22JIX0 g3561__4319(.A (n_31), .B (\result[5] [2]), .C (n_37), .D
       (\am_result[5] [2]), .Q (n_71));
  AO22JIX0 g3562__8428(.A (n_32), .B (\result[1] [2]), .C (n_35), .D
       (\am_result[1] [2]), .Q (n_70));
  AO22JIX0 g3563__5526(.A (n_29), .B (\result[1] [4]), .C (n_22), .D
       (\am_result[1] [4]), .Q (n_69));
  AO22JIX0 g3564__6783(.A (n_30), .B (\result[2] [4]), .C (n_18), .D
       (\am_result[2] [4]), .Q (n_68));
  AO22JIX0 g3565__3680(.A (n_31), .B (\result[2] [1]), .C (n_37), .D
       (\am_result[2] [1]), .Q (n_67));
  AO22JIX0 g3566__1617(.A (n_32), .B (\result[2] [2]), .C (n_35), .D
       (\am_result[2] [2]), .Q (n_66));
  AO22JIX0 g3567__2802(.A (n_29), .B (\result[2] [3]), .C (n_34), .D
       (\am_result[2] [3]), .Q (n_65));
  AO22JIX0 g3568__1705(.A (n_30), .B (\result[1] [3]), .C (n_36), .D
       (\am_result[1] [3]), .Q (n_64));
  AO22JIX0 g3569__5122(.A (n_31), .B (\result[3] [0]), .C (n_37), .D
       (\am_result[3] [0]), .Q (n_63));
  AO22JIX0 g3570__8246(.A (n_32), .B (\result[3] [3]), .C (n_22), .D
       (\am_result[3] [3]), .Q (n_62));
  AO22JIX0 g3571__7098(.A (n_29), .B (\result[3] [1]), .C (n_36), .D
       (\am_result[3] [1]), .Q (n_61));
  AO22JIX0 g3572__6131(.A (n_30), .B (\result[3] [4]), .C (n_20), .D
       (\am_result[3] [4]), .Q (n_60));
  AO22JIX0 g3573__1881(.A (n_31), .B (\result[3] [2]), .C (n_19), .D
       (\am_result[3] [2]), .Q (n_59));
  AO22JIX0 g3574__5115(.A (n_29), .B (\result[4] [3]), .C (n_22), .D
       (\am_result[4] [3]), .Q (n_58));
  AO22JIX0 g3575__7482(.A (n_30), .B (\result[2] [0]), .C (n_36), .D
       (\am_result[2] [0]), .Q (n_57));
  AO22JIX0 g3576__4733(.A (n_21), .B (\result[1] [1]), .C (n_20), .D
       (\am_result[1] [1]), .Q (n_56));
  NA2JIX0 g3577__6161(.A (n_48), .B (n_34), .Q (n_55));
  INVJIX2 g3578(.A (n_45), .Q (n_53));
  INVJIX0 g3579(.A (n_44), .Q (n_52));
  INVJIX2 g3580(.A (n_54), .Q (n_51));
  INVJIX0 g3581(.A (n_43), .Q (n_50));
  AND2JIX1 g3582__9315(.A (n_32), .B (start), .Q (n_54));
  INVJIX0 g3584(.A (cycle_counter[1]), .Q (n_49));
  INVJIX0 g3585(.A (cycle_counter[0]), .Q (n_48));
  INVJIX0 g3586(.A (n_37), .Q (n_47));
  INVJIX0 drc_bufs3587(.A (n_38), .Q (n_45));
  INVJIX0 drc_bufs3588(.A (n_38), .Q (n_44));
  INVJIX0 drc_bufs3589(.A (n_38), .Q (n_43));
  INVJIX0 drc_bufs3590(.A (n_38), .Q (n_42));
  INVJIX0 drc_bufs3591(.A (n_38), .Q (n_41));
  INVJIX0 drc_bufs3592(.A (n_38), .Q (n_40));
  INVJIX0 drc_bufs3593(.A (n_38), .Q (n_39));
  INVJIX1 drc_bufs3594(.A (n_54), .Q (n_38));
  INVJIX0 drc_bufs3600(.A (n_33), .Q (n_37));
  INVJIX0 drc_bufs3601(.A (n_33), .Q (n_36));
  INVJIX0 drc_bufs3602(.A (n_33), .Q (n_35));
  INVJIX0 drc_bufs3603(.A (n_33), .Q (n_34));
  INVJIX0 drc_bufs3604(.A (en_542), .Q (n_33));
  INVJIX0 drc_bufs3608(.A (n_28), .Q (n_32));
  INVJIX0 drc_bufs3609(.A (n_28), .Q (n_31));
  INVJIX0 drc_bufs3610(.A (n_28), .Q (n_30));
  INVJIX0 drc_bufs3611(.A (n_28), .Q (n_29));
  INVJIX0 drc_bufs3612(.A (n_47), .Q (n_28));
  INVJIX0 drc_bufs3617(.A (n_24), .Q (n_27));
  INVJIX0 drc_bufs3618(.A (n_24), .Q (n_26));
  INVJIX0 drc_bufs3619(.A (n_24), .Q (n_25));
  INVJIX0 drc_bufs3620(.A (n_53), .Q (n_24));
  INVJIX0 drc_bufs3625(.A (n_54), .Q (n_23));
  INVJIX0 drc_bufs3631(.A (n_33), .Q (n_22));
  BUJIX1 drc_bufs3639(.A (n_31), .Q (n_21));
  BUJIX1 drc_bufs3644(.A (n_34), .Q (n_20));
  BUJIX1 drc_bufs3649(.A (n_37), .Q (n_19));
  BUJIX1 drc_bufs3654(.A (n_36), .Q (n_18));
endmodule

module adder_nbit_N5(A, B, Sum);
  input [4:0] A, B;
  output [5:0] Sum;
  wire [4:0] A, B;
  wire [5:0] Sum;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_20, n_21, n_23, n_24, n_26;
  wire n_27, n_29, n_30;
  NA2JIX1 g294__9945(.A (n_30), .B (n_8), .Q (Sum[5]));
  EO2JIX2 g295__2883(.A (n_29), .B (n_15), .Q (Sum[4]));
  NA2JIX0 g296__2346(.A (n_29), .B (n_10), .Q (n_30));
  NA2JIX2 g297__1666(.A (n_27), .B (n_7), .Q (n_29));
  EO2JIX2 g298__7410(.A (n_26), .B (n_18), .Q (Sum[3]));
  NA2JIX1 g299__6417(.A (n_26), .B (n_11), .Q (n_27));
  NA2JIX2 g300__5477(.A (n_24), .B (n_5), .Q (n_26));
  EO2JIX2 g301__2398(.A (n_23), .B (n_17), .Q (Sum[2]));
  NA2JIX1 g302__5107(.A (n_23), .B (n_14), .Q (n_24));
  NA2JIX2 g303__6260(.A (n_21), .B (n_6), .Q (n_23));
  EO2JIX2 g304__4319(.A (n_16), .B (n_20), .Q (Sum[1]));
  NA2JIX2 g305__8428(.A (n_20), .B (n_13), .Q (n_21));
  INJIX2 g306(.A (n_9), .Q (n_20));
  NO2I1JIX1 g307__5526(.AN (n_9), .B (n_12), .Q (Sum[0]));
  EO2JIX0 g308__6783(.A (B[3]), .B (A[3]), .Q (n_18));
  EO2JIX1 g309__3680(.A (B[2]), .B (A[2]), .Q (n_17));
  EO2JIX2 g310__1617(.A (n_4), .B (n_1), .Q (n_16));
  EO2JIX0 g311__2802(.A (B[4]), .B (A[4]), .Q (n_15));
  OR2JIX0 g312__1705(.A (A[2]), .B (B[2]), .Q (n_14));
  NA2JIX1 g313__5122(.A (n_3), .B (n_2), .Q (n_13));
  NO2JIX0 g314__8246(.A (B[0]), .B (A[0]), .Q (n_12));
  OR2JIX0 g315__7098(.A (A[3]), .B (B[3]), .Q (n_11));
  OR2JIX0 g316__6131(.A (A[4]), .B (B[4]), .Q (n_10));
  NA2JIX0 g317__1881(.A (B[4]), .B (A[4]), .Q (n_8));
  NA2JIX0 g318__5115(.A (B[3]), .B (A[3]), .Q (n_7));
  NA2JIX1 g319__7482(.A (n_4), .B (n_0), .Q (n_6));
  NA2JIX0 g320__4733(.A (B[2]), .B (A[2]), .Q (n_5));
  NA2JIX1 g321__6161(.A (B[0]), .B (A[0]), .Q (n_9));
  INVJIX2 g322(.A (n_3), .Q (n_4));
  INVJIX2 g323(.A (B[1]), .Q (n_3));
  INVJIX2 g325(.A (A[1]), .Q (n_2));
  INVJIX2 fopt(.A (n_2), .Q (n_1));
  INVJIX0 fopt1(.A (n_2), .Q (n_0));
endmodule

module adder_nbit_N5_158(A, B, Sum);
  input [4:0] A, B;
  output [5:0] Sum;
  wire [4:0] A, B;
  wire [5:0] Sum;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_20, n_21, n_23, n_24, n_26;
  wire n_27, n_29, n_30;
  NA2JIX1 g294__9315(.A (n_30), .B (n_8), .Q (Sum[5]));
  EO2JIX2 g295__9945(.A (n_29), .B (n_15), .Q (Sum[4]));
  NA2JIX0 g296__2883(.A (n_29), .B (n_10), .Q (n_30));
  NA2JIX2 g297__2346(.A (n_27), .B (n_7), .Q (n_29));
  EO2JIX2 g298__1666(.A (n_26), .B (n_18), .Q (Sum[3]));
  NA2JIX1 g299__7410(.A (n_26), .B (n_11), .Q (n_27));
  NA2JIX2 g300__6417(.A (n_24), .B (n_5), .Q (n_26));
  EO2JIX2 g301__5477(.A (n_23), .B (n_17), .Q (Sum[2]));
  NA2JIX1 g302__2398(.A (n_23), .B (n_14), .Q (n_24));
  NA2JIX2 g303__5107(.A (n_21), .B (n_6), .Q (n_23));
  EO2JIX2 g304__6260(.A (n_16), .B (n_20), .Q (Sum[1]));
  NA2JIX2 g305__4319(.A (n_20), .B (n_13), .Q (n_21));
  INJIX2 g306(.A (n_9), .Q (n_20));
  NO2I1JIX1 g307__8428(.AN (n_9), .B (n_12), .Q (Sum[0]));
  EO2JIX0 g308__5526(.A (B[3]), .B (A[3]), .Q (n_18));
  EO2JIX1 g309__6783(.A (B[2]), .B (A[2]), .Q (n_17));
  EO2JIX2 g310__3680(.A (n_4), .B (n_1), .Q (n_16));
  EO2JIX0 g311__1617(.A (B[4]), .B (A[4]), .Q (n_15));
  OR2JIX0 g312__2802(.A (A[2]), .B (B[2]), .Q (n_14));
  NA2JIX1 g313__1705(.A (n_3), .B (n_2), .Q (n_13));
  NO2JIX0 g314__5122(.A (B[0]), .B (A[0]), .Q (n_12));
  OR2JIX0 g315__8246(.A (A[3]), .B (B[3]), .Q (n_11));
  OR2JIX0 g316__7098(.A (A[4]), .B (B[4]), .Q (n_10));
  NA2JIX0 g317__6131(.A (B[4]), .B (A[4]), .Q (n_8));
  NA2JIX0 g318__1881(.A (B[3]), .B (A[3]), .Q (n_7));
  NA2JIX1 g319__5115(.A (n_4), .B (n_0), .Q (n_6));
  NA2JIX0 g320__7482(.A (B[2]), .B (A[2]), .Q (n_5));
  NA2JIX1 g321__4733(.A (B[0]), .B (A[0]), .Q (n_9));
  INVJIX2 g322(.A (n_3), .Q (n_4));
  INVJIX2 g323(.A (B[1]), .Q (n_3));
  INVJIX2 g325(.A (A[1]), .Q (n_2));
  INVJIX2 fopt(.A (n_2), .Q (n_1));
  INVJIX0 fopt1(.A (n_2), .Q (n_0));
endmodule

module adder_nbit_N5_157(A, B, Sum);
  input [4:0] A, B;
  output [5:0] Sum;
  wire [4:0] A, B;
  wire [5:0] Sum;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_17;
  wire n_18, n_20, n_21, n_23;
  AO22JIX0 g294__6161(.A (n_23), .B (n_8), .C (B[4]), .D (A[4]), .Q
       (Sum[5]));
  EO2JIX2 g295__9315(.A (n_23), .B (n_13), .Q (Sum[4]));
  NA2JIX1 g296__9945(.A (n_21), .B (n_9), .Q (n_23));
  EO2JIX2 g297__2883(.A (n_20), .B (n_15), .Q (Sum[3]));
  NA2JIX1 g298__2346(.A (n_20), .B (n_11), .Q (n_21));
  NA2JIX1 g299__1666(.A (n_18), .B (n_7), .Q (n_20));
  EO2JIX1 g300__7410(.A (n_17), .B (n_14), .Q (Sum[2]));
  NA2JIX0 g301__6417(.A (n_17), .B (n_12), .Q (n_18));
  NA2JIX1 g302__5477(.A (n_3), .B (n_10), .Q (n_17));
  EO3JIX0 g303__2398(.A (n_4), .B (B[1]), .C (A[1]), .Q (Sum[1]));
  EO2JIX0 g307__5107(.A (B[3]), .B (A[3]), .Q (n_15));
  EO2JIX1 g308__6260(.A (n_6), .B (n_5), .Q (n_14));
  EO2JIX0 g309__4319(.A (B[4]), .B (A[4]), .Q (n_13));
  NA2JIX0 g311__8428(.A (n_5), .B (n_6), .Q (n_12));
  OR2JIX0 g312__5526(.A (A[3]), .B (B[3]), .Q (n_11));
  NA2JIX0 g313__6783(.A (B[1]), .B (A[1]), .Q (n_10));
  NA2JIX0 g314__3680(.A (B[3]), .B (A[3]), .Q (n_9));
  OR2JIX0 g315__1617(.A (A[4]), .B (B[4]), .Q (n_8));
  NA2JIX0 g316__2802(.A (B[2]), .B (A[2]), .Q (n_7));
  INVJIX1 g318(.A (A[2]), .Q (n_6));
  INVJIX1 g320(.A (B[2]), .Q (n_5));
  AND2JIX0 g2__1705(.A (B[0]), .B (A[0]), .Q (n_4));
  ON211JIX1 g323__5122(.A (B[1]), .B (A[1]), .C (B[0]), .D (A[0]), .Q
       (n_3));
  BUFJIX1 fopt(.A (A[0]), .Q (n_1));
  BUFJIX1 fopt331(.A (B[0]), .Q (n_0));
  EO2JIX1 g333__8246(.A (n_0), .B (n_1), .Q (Sum[0]));
endmodule

module adder_nbit_N6(A, B, Sum);
  input [5:0] A, B;
  output [6:0] Sum;
  wire [5:0] A, B;
  wire [6:0] Sum;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_24;
  wire n_25, n_27, n_28, n_30, n_31, n_33, n_34, n_36;
  wire n_37;
  NA2I1JIX1 g380__7098(.AN (n_10), .B (n_37), .Q (Sum[6]));
  EO2JIX2 g381__6131(.A (n_36), .B (n_22), .Q (Sum[5]));
  NA2JIX0 g382__1881(.A (n_36), .B (n_14), .Q (n_37));
  NA2JIX2 g383__5115(.A (n_34), .B (n_11), .Q (n_36));
  EO2JIX1 g384__7482(.A (n_21), .B (n_33), .Q (Sum[4]));
  NA2JIX1 g385__4733(.A (n_33), .B (n_16), .Q (n_34));
  NA2JIX2 g386__6161(.A (n_31), .B (n_13), .Q (n_33));
  EO2JIX1 g387__9315(.A (n_30), .B (n_20), .Q (Sum[3]));
  NA2JIX1 g388__9945(.A (n_30), .B (n_17), .Q (n_31));
  NA2JIX1 g389__2883(.A (n_28), .B (n_12), .Q (n_30));
  EO2JIX1 g390__2346(.A (n_27), .B (n_19), .Q (Sum[2]));
  NA2JIX1 g391__1666(.A (n_27), .B (n_15), .Q (n_28));
  NA2JIX2 g392__7410(.A (n_25), .B (n_0), .Q (n_27));
  EO2JIX1 g393__6417(.A (n_18), .B (n_24), .Q (Sum[1]));
  NA2JIX1 g394__5477(.A (n_1), .B (n_24), .Q (n_25));
  HAJIX1 g395__2398(.A (A[0]), .B (B[0]), .CO (n_24), .S (Sum[0]));
  EO2JIX0 g396__5107(.A (B[5]), .B (A[5]), .Q (n_22));
  EO2JIX1 g397__6260(.A (B[4]), .B (A[4]), .Q (n_21));
  EO2JIX2 g398__4319(.A (B[3]), .B (A[3]), .Q (n_20));
  EO2JIX2 g399__8428(.A (B[2]), .B (A[2]), .Q (n_19));
  EO2JIX2 g400__5526(.A (n_7), .B (n_9), .Q (n_18));
  NA2I1JIX1 g401__6783(.AN (B[3]), .B (n_4), .Q (n_17));
  NA2JIX0 g403__3680(.A (n_3), .B (n_5), .Q (n_16));
  NA2I1JIX1 g404__1617(.AN (B[2]), .B (n_2), .Q (n_15));
  OR2JIX0 g405__2802(.A (A[5]), .B (B[5]), .Q (n_14));
  NA2JIX0 g406__1705(.A (B[3]), .B (A[3]), .Q (n_13));
  NA2JIX0 g407__5122(.A (B[2]), .B (A[2]), .Q (n_12));
  NA2JIX0 g408__8246(.A (B[4]), .B (A[4]), .Q (n_11));
  AND2JIX0 g410__7098(.A (B[5]), .B (A[5]), .Q (n_10));
  INVJIX1 g413(.A (n_8), .Q (n_9));
  INVJIX1 g414(.A (A[1]), .Q (n_8));
  INJIX2 g415(.A (n_6), .Q (n_7));
  INVJIX1 g417(.A (B[1]), .Q (n_6));
  INVJIX0 g418(.A (A[4]), .Q (n_5));
  INVJIX0 g419(.A (A[3]), .Q (n_4));
  INVJIX0 g420(.A (B[4]), .Q (n_3));
  INVJIX0 g421(.A (A[2]), .Q (n_2));
  NA2I1JIX1 g2__6131(.AN (A[1]), .B (n_6), .Q (n_1));
  NA2I1JIX2 g422__1881(.AN (n_8), .B (n_7), .Q (n_0));
endmodule

module adder_nbit_N6_1(A, B, Sum);
  input [5:0] A, B;
  output [6:0] Sum;
  wire [5:0] A, B;
  wire [6:0] Sum;
  wire [6:0] Carry;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16;
  assign Sum[0] = 1'b0;
  BUJIX1 g66(.A (A[1]), .Q (n_15));
  EO2JIX1 g72__5115(.A (n_15), .B (B[1]), .Q (Sum[1]));
  EO2JIX2 g83__7482(.A (n_14), .B (n_13), .Q (Sum[2]));
  EN2JIX0 g84__4733(.A (A[2]), .B (B[2]), .Q (n_14));
  BUFJIX1 g85(.A (n_16), .Q (n_13));
  NA2JIX1 g86__6161(.A (A[1]), .B (B[1]), .Q (n_16));
  NA2JIX1 g156__9315(.A (n_3), .B (n_12), .Q (Sum[5]));
  BUFJIX1 g157(.A (n_3), .Q (Sum[6]));
  NA2JIX0 g159__9945(.A (n_11), .B (A[5]), .Q (n_12));
  NA2JIX0 g160__2883(.A (n_10), .B (n_4), .Q (n_11));
  EO2JIX2 g161__2346(.A (n_9), .B (n_6), .Q (Sum[4]));
  ON21JIX1 g162__1666(.A (A[4]), .B (B[4]), .C (n_8), .Q (n_10));
  BUFJIX2 g163(.A (n_8), .Q (n_9));
  NA2JIX1 g164__7410(.A (n_7), .B (n_5), .Q (n_8));
  ON21JIX1 g165__6417(.A (A[3]), .B (B[3]), .C (Carry[3]), .Q (n_7));
  EO2JIX2 g166__5477(.A (A[4]), .B (B[4]), .Q (n_6));
  NA2JIX0 g167__2398(.A (A[3]), .B (B[3]), .Q (n_5));
  NA2JIX0 g168__5107(.A (A[4]), .B (B[4]), .Q (n_4));
  NA3I1JIX0 g2__6260(.AN (A[5]), .B (n_10), .C (n_4), .Q (n_3));
  EO2JIX1 g109__4319(.A (n_2), .B (Carry[3]), .Q (Sum[3]));
  ON21JIX1 g111__8428(.A (n_1), .B (n_16), .C (n_0), .Q (Carry[3]));
  EO2JIX2 g112__5526(.A (A[3]), .B (B[3]), .Q (n_2));
  NO2JIX1 g113__6783(.A (A[2]), .B (B[2]), .Q (n_1));
  NA2JIX1 g114__3680(.A (A[2]), .B (B[2]), .Q (n_0));
endmodule

module adder_nbit_N7(A, B, Sum);
  input [6:0] A, B;
  output [7:0] Sum;
  wire [6:0] A, B;
  wire [7:0] Sum;
  wire [7:0] Carry;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24;
  EO2JIX0 g138__1617(.A (A[0]), .B (B[0]), .Q (Sum[0]));
  EN3JIX0 g149__2802(.A (A[1]), .B (B[1]), .C (n_24), .Q (Sum[1]));
  NA2JIX0 g150__1705(.A (A[0]), .B (B[0]), .Q (n_24));
  EO3JIX0 g175__5122(.A (n_23), .B (A[2]), .C (B[2]), .Q (Sum[2]));
  BUJIX1 g176(.A (Carry[2]), .Q (n_23));
  ON21JIX1 g177__8246(.A (n_22), .B (n_24), .C (n_21), .Q (Carry[2]));
  NO2JIX1 g178__7098(.A (B[1]), .B (A[1]), .Q (n_22));
  NA2JIX0 g179__6131(.A (A[1]), .B (B[1]), .Q (n_21));
  EO3JIX0 g180__1881(.A (Carry[3]), .B (A[3]), .C (B[3]), .Q (Sum[3]));
  NA2JIX2 g181__5115(.A (n_20), .B (n_19), .Q (Carry[3]));
  NA2JIX1 g182__7482(.A (n_18), .B (Carry[2]), .Q (n_20));
  NA2JIX0 g183__4733(.A (A[2]), .B (B[2]), .Q (n_19));
  OR2JIX0 g2__6161(.A (A[2]), .B (B[2]), .Q (n_18));
  NA2JIX1 g291__9315(.A (n_17), .B (n_5), .Q (Sum[7]));
  EO2JIX1 g292__9945(.A (n_16), .B (n_10), .Q (Sum[6]));
  NA2JIX0 g293__2883(.A (n_4), .B (n_16), .Q (n_17));
  NA2JIX1 g294__2346(.A (n_15), .B (n_3), .Q (n_16));
  EO2JIX0 g295__1666(.A (n_12), .B (n_14), .Q (Sum[5]));
  ON21JIX1 g296__7410(.A (B[5]), .B (A[5]), .C (n_14), .Q (n_15));
  ON21JIX2 g297__6417(.A (n_9), .B (n_13), .C (n_6), .Q (n_14));
  EN2JIX0 g298__5477(.A (n_11), .B (n_13), .Q (Sum[4]));
  AN21JIX2 g299__2398(.A (Carry[3]), .B (n_7), .C (n_8), .Q (n_13));
  EO2JIX0 g300__5107(.A (A[5]), .B (B[5]), .Q (n_12));
  EO2JIX0 g301__6260(.A (A[4]), .B (n_0), .Q (n_11));
  EO2JIX1 g302__4319(.A (A[6]), .B (B[6]), .Q (n_10));
  NO2JIX1 g303__8428(.A (A[4]), .B (B[4]), .Q (n_9));
  AND2JIX0 g304__5526(.A (A[3]), .B (B[3]), .Q (n_8));
  NA2JIX1 g305__6783(.A (n_1), .B (n_2), .Q (n_7));
  NA2JIX0 g306__3680(.A (A[4]), .B (B[4]), .Q (n_6));
  NA2JIX0 g307__1617(.A (A[6]), .B (B[6]), .Q (n_5));
  OR2JIX0 g308__2802(.A (A[6]), .B (B[6]), .Q (n_4));
  NA2JIX0 g309__1705(.A (A[5]), .B (B[5]), .Q (n_3));
  INVJIX0 g310(.A (B[3]), .Q (n_2));
  INVJIX0 g311(.A (A[3]), .Q (n_1));
  BUFJIX1 g312(.A (B[4]), .Q (n_0));
endmodule

module AdderTree_6_WEIGHT_WIDTH8_NUM_UNITS6(\input_data[0] ,
     \input_data[1] , \input_data[2] , \input_data[3] , \input_data[4]
     , \input_data[5] , clk, rst, sum_combinational, \DFT_/sen ,
     \DFT_/sdo );
  input [7:0] \input_data[0] , \input_data[1] , \input_data[2] ,
       \input_data[3] , \input_data[4] , \input_data[5] ;
  input clk, rst, \DFT_/sen ;
  output [10:0] sum_combinational;
  output \DFT_/sdo ;
  wire [7:0] \input_data[0] , \input_data[1] , \input_data[2] ,
       \input_data[3] , \input_data[4] , \input_data[5] ;
  wire clk, rst, \DFT_/sen ;
  wire [10:0] sum_combinational;
  wire \DFT_/sdo ;
  wire [5:0] \int_sum_L1[0] ;
  wire [5:0] \int_sum_L1[1] ;
  wire [5:0] \int_sum_L1[2] ;
  wire [6:0] \int_sum_L2[0] ;
  wire [10:0] sum_out;
  wire [6:0] \int_sum_L2[1] ;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_40, n_41, n_42;
  wire n_43;
  assign sum_combinational[0] = 1'b0;
  assign sum_combinational[1] = 1'b0;
  assign sum_combinational[2] = 1'b0;
  assign sum_combinational[3] = 1'b0;
  assign sum_combinational[8] = 1'b0;
  assign sum_combinational[9] = 1'b0;
  assign sum_combinational[10] = 1'b0;
  adder_nbit_N5 \L1_ADD[0].inst_L1 (\input_data[0] [4:0],
       \input_data[1] [4:0], \int_sum_L1[0] );
  adder_nbit_N5_158 \L1_ADD[1].inst_L1 (\input_data[2] [4:0],
       \input_data[3] [4:0], \int_sum_L1[1] );
  adder_nbit_N5_157 \L1_ADD[2].inst_L1 (\input_data[4] [4:0],
       \input_data[5] [4:0], \int_sum_L1[2] );
  adder_nbit_N6 inst_L2(\int_sum_L1[0] , \int_sum_L1[1] ,
       \int_sum_L2[0] );
  adder_nbit_N6_1 inst_L2_extra({\int_sum_L1[2] [5:1], 1'b0}, {1'b1,
       \DFT_/sdo , sum_out[2:0], 1'b0}, {\int_sum_L2[1] [6:1],
       UNCONNECTED});
  adder_nbit_N7 inst_L6_0(\int_sum_L2[0] , {\int_sum_L2[1] [6:1],
       \int_sum_L1[2] [0]}, {sum_combinational[7:4], n_40, n_41, n_42,
       n_43});
  SDFRQJIX1 \sum_out_reg[3] (.C (clk), .D (n_3), .SD (sum_out[2]), .SE
       (\DFT_/sen ), .Q (\DFT_/sdo ));
  NO2I1JIX0 g9__5122(.AN (n_40), .B (rst), .Q (n_3));
  SDFRQJIX1 \sum_out_reg[2] (.C (clk), .D (n_2), .SD (sum_out[1]), .SE
       (\DFT_/sen ), .Q (sum_out[2]));
  NO2I1JIX0 g11__8246(.AN (n_41), .B (rst), .Q (n_2));
  SDFRQJIX1 \sum_out_reg[1] (.C (clk), .D (n_1), .SD (sum_out[0]), .SE
       (\DFT_/sen ), .Q (sum_out[1]));
  NO2I1JIX0 g13__7098(.AN (n_42), .B (rst), .Q (n_1));
  SDFRQJIX1 \sum_out_reg[0] (.C (clk), .D (n_0), .SD (\input_data[5]
       [4]), .SE (\DFT_/sen ), .Q (sum_out[0]));
  NO2I1JIX0 g15__6131(.AN (n_43), .B (rst), .Q (n_0));
endmodule

module Out_Gen_Func(clk, reset, IN, z_p, z_n, \DFT_/sdi , \DFT_/sen );
  input clk, reset, \DFT_/sdi , \DFT_/sen ;
  input [3:0] IN;
  output z_p, z_n;
  wire clk, reset, \DFT_/sdi , \DFT_/sen ;
  wire [3:0] IN;
  wire z_p, z_n;
  wire R0, R1, R2, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13;
  SDFRRQJIX1 R3_reg(.RN (n_1), .C (clk), .D (n_13), .SD (R2), .SE
       (\DFT_/sen ), .Q (z_n));
  NA2JIX2 g253__1881(.A (n_12), .B (n_0), .Q (z_p));
  EO2JIX0 g254__5115(.A (n_9), .B (n_11), .Q (n_13));
  NA2JIX0 g255__7482(.A (n_9), .B (n_10), .Q (n_12));
  EO2JIX0 g256__4733(.A (IN[3]), .B (R2), .Q (n_11));
  NA2I1JIX0 g257__6161(.AN (R2), .B (n_2), .Q (n_10));
  SDFRRQJIX1 R2_reg(.RN (n_1), .C (clk), .D (n_8), .SD (R1), .SE
       (\DFT_/sen ), .Q (R2));
  ON21JIX1 g260__9315(.A (n_7), .B (n_3), .C (n_6), .Q (n_9));
  EN3JIX0 g261__9945(.A (n_3), .B (IN[2]), .C (R1), .Q (n_8));
  NO2JIX1 g262__2883(.A (IN[2]), .B (R1), .Q (n_7));
  NA2JIX0 g263__2346(.A (IN[2]), .B (R1), .Q (n_6));
  SDFRRQJIX1 R1_reg(.RN (n_1), .C (clk), .D (n_5), .SD (R0), .SE
       (\DFT_/sen ), .Q (R1));
  NO2I1JIX0 g265__1666(.AN (n_3), .B (n_4), .Q (n_5));
  NO2JIX0 g266__7410(.A (IN[1]), .B (R0), .Q (n_4));
  NA2JIX1 g267__6417(.A (IN[1]), .B (R0), .Q (n_3));
  SDFRRQJIX1 R0_reg(.RN (n_1), .C (clk), .D (IN[0]), .SD (\DFT_/sdi ),
       .SE (\DFT_/sen ), .Q (R0));
  INVJIX0 g270(.A (IN[3]), .Q (n_2));
  INVJIX0 g271(.A (reset), .Q (n_1));
  NA2I1JIX0 g2__5477(.AN (n_2), .B (R2), .Q (n_0));
endmodule

module Main(\weight[0] , \weight[1] , \weight[2] , \weight[3] ,
     \weight[4] , \weight[5] , \activation[0] , \activation[1] ,
     \activation[2] , \activation[3] , \activation[4] , \activation[5]
     , start, clk, rst, en, z_p, z_n, scan_en, scan_in, scan_out);
  input [7:0] \weight[0] , \weight[1] , \weight[2] , \weight[3] ,
       \weight[4] , \weight[5] , \activation[0] , \activation[1] ,
       \activation[2] , \activation[3] , \activation[4] ,
       \activation[5] ;
  input start, clk, rst, scan_en, scan_in;
  output en, z_p, z_n, scan_out;
  wire [7:0] \weight[0] , \weight[1] , \weight[2] , \weight[3] ,
       \weight[4] , \weight[5] , \activation[0] , \activation[1] ,
       \activation[2] , \activation[3] , \activation[4] ,
       \activation[5] ;
  wire start, clk, rst, scan_en, scan_in;
  wire en, z_p, z_n, scan_out;
  wire [7:0] \result[0] ;
  wire [7:0] \result[1] ;
  wire [7:0] \result[2] ;
  wire [7:0] \result[3] ;
  wire [7:0] \result[4] ;
  wire [7:0] \result[5] ;
  wire [10:0] sum_combinational;
  wire n_105;
  assign scan_out = z_n;
  ActivationMultiplier_6_IN_WIDTH8_NUM_UNITS6_ACTIVATION_WIDTH8
       A6M(.\activation[0]  (\activation[0] ), .\activation[1] 
       (\activation[1] ), .\activation[2]  (\activation[2] ),
       .\activation[3]  (\activation[3] ), .\activation[4] 
       (\activation[4] ), .\activation[5]  (\activation[5] ),
       .\weight[0]  (\weight[0] ), .\weight[1]  (\weight[1] ),
       .\weight[2]  (\weight[2] ), .\weight[3]  (\weight[3] ),
       .\weight[4]  (\weight[4] ), .\weight[5]  (\weight[5] ), .clk
       (clk), .rst (rst), .start (start), .\result[0]  (\result[0] ),
       .\result[1]  (\result[1] ), .\result[2]  (\result[2] ),
       .\result[3]  (\result[3] ), .\result[4]  (\result[4] ),
       .\result[5]  (\result[5] ), .en (en), .\DFT_/sdi  (scan_in),
       .\DFT_/sen  (scan_en));
  AdderTree_6_WEIGHT_WIDTH8_NUM_UNITS6 AT6(.\input_data[0]  ({3'b0,
       \result[0] [4:0]}), .\input_data[1]  ({3'b0, \result[1] [4:0]}),
       .\input_data[2]  ({3'b0, \result[2] [4:0]}), .\input_data[3] 
       ({3'b0, \result[3] [4:0]}), .\input_data[4]  ({3'b0,
       \result[4] [4:0]}), .\input_data[5]  ({3'b0, \result[5] [4:0]}),
       .clk (clk), .rst (rst), .sum_combinational (sum_combinational),
       .\DFT_/sen  (scan_en), .\DFT_/sdo  (n_105));
  Out_Gen_Func OGF(.clk (clk), .reset (rst), .IN
       (sum_combinational[7:4]), .z_p (z_p), .z_n (z_n), .\DFT_/sdi 
       (n_105), .\DFT_/sen  (scan_en));
endmodule

