
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: May 26 2025 19:15:14 CEST (May 26 2025 17:15:14 UTC)

// Verification Directory fv/serial_to_parallel 

module serial_to_parallel(clk, rst_n, serial_in, p_o);
  input clk, rst_n, serial_in;
  output [7:0] p_o;
  wire clk, rst_n, serial_in;
  wire [7:0] p_o;
  wire [7:0] shift_reg;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, n_16;
  wire n_50, n_54, n_58, n_62, n_63, n_64, n_65, n_66;
  wire n_67;
  sg13g2_inv_16 g4(.A (n_64), .Y (p_o[7]));
  sg13g2_dfrbp_2 \shift_reg_reg[7] (.RESET_B (rst_n), .CLK (clk), .D
       (n_62), .Q (n_16), .Q_N (n_63));
  sg13g2_dfrbp_2 \shift_reg_reg[6] (.RESET_B (rst_n), .CLK (clk), .D
       (n_65), .Q (UNCONNECTED), .Q_N (shift_reg[6]));
  sg13g2_dfrbp_2 \shift_reg_reg[5] (.RESET_B (rst_n), .CLK (clk), .D
       (n_58), .Q (UNCONNECTED0), .Q_N (shift_reg[5]));
  sg13g2_dfrbp_2 \shift_reg_reg[4] (.RESET_B (rst_n), .CLK (clk), .D
       (n_66), .Q (UNCONNECTED1), .Q_N (shift_reg[4]));
  sg13g2_dfrbp_2 \shift_reg_reg[3] (.RESET_B (rst_n), .CLK (clk), .D
       (n_54), .Q (UNCONNECTED2), .Q_N (shift_reg[3]));
  sg13g2_dfrbp_2 \shift_reg_reg[2] (.RESET_B (rst_n), .CLK (clk), .D
       (n_67), .Q (UNCONNECTED3), .Q_N (shift_reg[2]));
  sg13g2_dfrbp_2 \shift_reg_reg[1] (.RESET_B (rst_n), .CLK (clk), .D
       (n_50), .Q (UNCONNECTED4), .Q_N (shift_reg[1]));
  sg13g2_dfrbp_2 \shift_reg_reg[0] (.RESET_B (rst_n), .CLK (clk), .D
       (serial_in), .Q (UNCONNECTED5), .Q_N (shift_reg[0]));
  sg13g2_buf_16 fopt(.A (n_50), .X (p_o[0]));
  sg13g2_inv_4 fopt1(.A (shift_reg[0]), .Y (n_50));
  sg13g2_buf_16 fopt56(.A (n_67), .X (p_o[1]));
  sg13g2_buf_16 fopt58(.A (n_54), .X (p_o[2]));
  sg13g2_inv_4 fopt59(.A (shift_reg[2]), .Y (n_54));
  sg13g2_buf_16 fopt60(.A (n_65), .X (p_o[5]));
  sg13g2_buf_16 fopt62(.A (n_58), .X (p_o[4]));
  sg13g2_inv_4 fopt63(.A (shift_reg[4]), .Y (n_58));
  sg13g2_buf_16 fopt64(.A (n_66), .X (p_o[3]));
  sg13g2_buf_16 fopt66(.A (n_62), .X (p_o[6]));
  sg13g2_inv_4 fopt67(.A (shift_reg[6]), .Y (n_62));
  sg13g2_buf_8 g16(.A (n_63), .X (n_64));
  sg13g2_inv_4 g18(.A (shift_reg[5]), .Y (n_65));
  sg13g2_inv_4 g22(.A (shift_reg[3]), .Y (n_66));
  sg13g2_inv_4 g20(.A (shift_reg[1]), .Y (n_67));
endmodule

