
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jun 26 2025 21:45:23 CEST (Jun 26 2025 19:45:23 UTC)

// Verification Directory fv/TGATE 

module TGATE(in, sel, selb, out);
  input in, sel, selb;
  output out;
  wire in, sel, selb;
  wire out;
  wire n_0;
  sg13g2_ebufn_2 g3__2398(.A (in), .TE_B (n_0), .Z (out));
  sg13g2_nand2b_1 g16__5107(.A_N (selb), .B (sel), .Y (n_0));
endmodule

