###############################################################
#  Generated by:      Cadence Innovus 23.14-s088_1
#  OS:                Linux x86_64(Host ID ei-vm-018.othr.de)
#  Generated on:      Sat Jul 19 01:05:50 2025
#  Design:            fpga_top
#  Command:           create_ccopt_clock_tree_spec -file ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin {clk[0]} true
set_ccopt_property cts_is_sdc_clock_root -pin {prog_clk[0]} true

# Clocks present at pin prog_clk[0]
#   prog_clk[0] (period 7.000ns) in timing_config CONSTRAINTS([SDC/cbx_1__0_.sdc SDC/cbx_1__1_.sdc SDC/cbx_1__2_.sdc SDC/cby_0__1_.sdc SDC/cby_1__1_.sdc SDC/cby_2__1_.sdc SDC/disable_configurable_memory_outputs.sdc SDC/disable_configure_ports.sdc SDC/disable_routing_multiplexer_outputs.sdc SDC/disable_sb_outputs.sdc SDC/global_ports.sdc SDC/logical_tile_clb_mode_clb_.sdc SDC/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff.sdc SDC/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic.sdc SDC/logical_tile_clb_mode_default__fle_mode_physical__fabric.sdc SDC/logical_tile_clb_mode_default__fle.sdc SDC/logical_tile_io_mode_io_.sdc SDC/sb_0__0_.sdc SDC/sb_0__1_.sdc SDC/sb_0__2_.sdc SDC/sb_1__0_.sdc SDC/sb_1__1_.sdc SDC/sb_1__2_.sdc SDC/sb_2__0_.sdc SDC/sb_2__1_.sdc SDC/sb_2__2_.sdc])
create_ccopt_clock_tree -name {prog_clk[0]} -source {prog_clk[0]} -no_skew_group
# Clock period setting for source pin of prog_clk[0]
set_ccopt_property clock_period -pin {prog_clk[0]} 7

# Clocks present at pin clk[0]
#   clk[0] (period 7.000ns) in timing_config CONSTRAINTS([SDC/cbx_1__0_.sdc SDC/cbx_1__1_.sdc SDC/cbx_1__2_.sdc SDC/cby_0__1_.sdc SDC/cby_1__1_.sdc SDC/cby_2__1_.sdc SDC/disable_configurable_memory_outputs.sdc SDC/disable_configure_ports.sdc SDC/disable_routing_multiplexer_outputs.sdc SDC/disable_sb_outputs.sdc SDC/global_ports.sdc SDC/logical_tile_clb_mode_clb_.sdc SDC/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff.sdc SDC/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic.sdc SDC/logical_tile_clb_mode_default__fle_mode_physical__fabric.sdc SDC/logical_tile_clb_mode_default__fle.sdc SDC/logical_tile_io_mode_io_.sdc SDC/sb_0__0_.sdc SDC/sb_0__1_.sdc SDC/sb_0__2_.sdc SDC/sb_1__0_.sdc SDC/sb_1__1_.sdc SDC/sb_1__2_.sdc SDC/sb_2__0_.sdc SDC/sb_2__1_.sdc SDC/sb_2__2_.sdc])
create_ccopt_clock_tree -name {clk[0]} -source {clk[0]} -no_skew_group
# Clock period setting for source pin of clk[0]
set_ccopt_property clock_period -pin {clk[0]} 7

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk[0] in timing_config:CONSTRAINTS (sdc SDC/cbx_1__0_.sdc SDC/cbx_1__1_.sdc SDC/cbx_1__2_.sdc SDC/cby_0__1_.sdc SDC/cby_1__1_.sdc SDC/cby_2__1_.sdc SDC/disable_configurable_memory_outputs.sdc SDC/disable_configure_ports.sdc SDC/disable_routing_multiplexer_outputs.sdc SDC/disable_sb_outputs.sdc SDC/global_ports.sdc SDC/logical_tile_clb_mode_clb_.sdc SDC/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff.sdc SDC/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic.sdc SDC/logical_tile_clb_mode_default__fle_mode_physical__fabric.sdc SDC/logical_tile_clb_mode_default__fle.sdc SDC/logical_tile_io_mode_io_.sdc SDC/sb_0__0_.sdc SDC/sb_0__1_.sdc SDC/sb_0__2_.sdc SDC/sb_1__0_.sdc SDC/sb_1__1_.sdc SDC/sb_1__2_.sdc SDC/sb_2__0_.sdc SDC/sb_2__1_.sdc SDC/sb_2__2_.sdc)
create_ccopt_skew_group -name {clk[0]/CONSTRAINTS} -sources {clk[0]} -auto_sinks
set_ccopt_property include_source_latency -skew_group {clk[0]/CONSTRAINTS} true
set_ccopt_property extracted_from_clock_name -skew_group {clk[0]/CONSTRAINTS} {clk[0]}
set_ccopt_property extracted_from_constraint_mode_names -skew_group {clk[0]/CONSTRAINTS} {CONSTRAINTS  }
set_ccopt_property extracted_from_delay_corners -skew_group {clk[0]/CONSTRAINTS} {MAX_DEALY MIN_DEALY}

# Skew group to balance non generated clock:prog_clk[0] in timing_config:CONSTRAINTS (sdc SDC/cbx_1__0_.sdc SDC/cbx_1__1_.sdc SDC/cbx_1__2_.sdc SDC/cby_0__1_.sdc SDC/cby_1__1_.sdc SDC/cby_2__1_.sdc SDC/disable_configurable_memory_outputs.sdc SDC/disable_configure_ports.sdc SDC/disable_routing_multiplexer_outputs.sdc SDC/disable_sb_outputs.sdc SDC/global_ports.sdc SDC/logical_tile_clb_mode_clb_.sdc SDC/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__ff.sdc SDC/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic.sdc SDC/logical_tile_clb_mode_default__fle_mode_physical__fabric.sdc SDC/logical_tile_clb_mode_default__fle.sdc SDC/logical_tile_io_mode_io_.sdc SDC/sb_0__0_.sdc SDC/sb_0__1_.sdc SDC/sb_0__2_.sdc SDC/sb_1__0_.sdc SDC/sb_1__1_.sdc SDC/sb_1__2_.sdc SDC/sb_2__0_.sdc SDC/sb_2__1_.sdc SDC/sb_2__2_.sdc)
create_ccopt_skew_group -name {prog_clk[0]/CONSTRAINTS} -sources {prog_clk[0]} -auto_sinks
set_ccopt_property include_source_latency -skew_group {prog_clk[0]/CONSTRAINTS} true
set_ccopt_property extracted_from_clock_name -skew_group {prog_clk[0]/CONSTRAINTS} {prog_clk[0]}
set_ccopt_property extracted_from_constraint_mode_names -skew_group {prog_clk[0]/CONSTRAINTS} {CONSTRAINTS  }
set_ccopt_property extracted_from_delay_corners -skew_group {prog_clk[0]/CONSTRAINTS} {MAX_DEALY MIN_DEALY}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

