
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Aug 10 2025 17:29:46 CEST (Aug 10 2025 15:29:46 UTC)

// Verification Directory fv/Main 

module Main(\weight[0] , \weight[1] , \weight[2] , \weight[3] ,
     \weight[4] , \weight[5] , \activation[0] , \activation[1] ,
     \activation[2] , \activation[3] , \activation[4] , \activation[5]
     , start, clk, rst, en, z_p, z_n, scan_en, scan_in, scan_out);
  input [7:0] \weight[0] , \weight[1] , \weight[2] , \weight[3] ,
       \weight[4] , \weight[5] , \activation[0] , \activation[1] ,
       \activation[2] , \activation[3] , \activation[4] ,
       \activation[5] ;
  input start, clk, rst, scan_en, scan_in;
  output en, z_p, z_n, scan_out;
  wire [7:0] \weight[0] , \weight[1] , \weight[2] , \weight[3] ,
       \weight[4] , \weight[5] , \activation[0] , \activation[1] ,
       \activation[2] , \activation[3] , \activation[4] ,
       \activation[5] ;
  wire start, clk, rst, scan_en, scan_in;
  wire en, z_p, z_n, scan_out;
  wire [10:0] AT6_sum_out;
  wire [7:0] \result[4] ;
  wire [7:0] \result[5] ;
  wire [7:0] \result[2] ;
  wire [7:0] \result[3] ;
  wire [7:0] \result[0] ;
  wire [7:0] \result[1] ;
  wire [3:0] A6M_cycle_counter;
  wire [7:0] \A6M_activation_reg[4] ;
  wire [7:0] \A6M_activation_reg[1] ;
  wire [7:0] \A6M_activation_reg[5] ;
  wire [7:0] \A6M_activation_reg[2] ;
  wire [7:0] \A6M_activation_reg[0] ;
  wire [7:0] \A6M_activation_reg[3] ;
  wire OGF_R0, OGF_R1, OGF_R2, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_172;
  wire n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_197, n_198, n_199, n_200, n_201, n_202, n_203, n_204;
  wire n_205, n_206, n_207, n_208, n_209, n_210, n_211, n_212;
  wire n_213, n_214, n_215, n_216, n_217, n_218, n_219, n_220;
  wire n_221, n_222, n_223, n_224, n_225, n_226, n_227, n_228;
  wire n_229, n_230, n_231, n_232, n_233, n_234, n_235, n_236;
  wire n_237, n_238, n_239, n_240, n_241, n_242, n_243, n_244;
  wire n_245, n_246, n_247, n_248, n_249, n_250, n_251, n_253;
  assign scan_out = z_n;
  SDFFRHQX4 OGF_R3_reg(.RN (n_251), .CK (clk), .D (n_253), .SI
       (OGF_R2), .SE (scan_en), .Q (z_n));
  ADDFHX4 g6851__2398(.A (OGF_R2), .B (n_247), .CI (n_249), .CO (z_p),
       .S (n_253));
  SDFFRHQX1 OGF_R2_reg(.RN (n_251), .CK (clk), .D (n_250), .SI
       (OGF_R1), .SE (scan_en), .Q (OGF_R2));
  ADDFX1 g6853__5107(.A (OGF_R1), .B (n_248), .CI (n_245), .CO (n_249),
       .S (n_250));
  SDFFRHQX1 OGF_R1_reg(.RN (n_251), .CK (clk), .D (n_246), .SI
       (OGF_R0), .SE (scan_en), .Q (OGF_R1));
  ADDFX1 g6856__6260(.A (n_239), .B (n_226), .CI (n_243), .CO (n_247),
       .S (n_248));
  ADDHX1 g6855__4319(.A (OGF_R0), .B (n_244), .CO (n_245), .S (n_246));
  ADDFX1 g6857__8428(.A (n_240), .B (n_227), .CI (n_241), .CO (n_243),
       .S (n_244));
  SDFFRHQX1 OGF_R0_reg(.RN (n_251), .CK (clk), .D (n_242), .SI
       (AT6_sum_out[3]), .SE (scan_en), .Q (OGF_R0));
  ADDFX1 g6859__5526(.A (n_236), .B (n_223), .CI (n_233), .CO (n_241),
       .S (n_242));
  OAI2BB1X1 g6860__6783(.A0N (n_238), .A1N (n_237), .B0 (n_239), .Y
       (n_240));
  OR2X1 g6861__3680(.A (n_238), .B (n_237), .Y (n_239));
  ADDFX1 g6862__1617(.A (AT6_sum_out[3]), .B (n_221), .CI (n_231), .CO
       (n_237), .S (n_236));
  SDFFQX1 \AT6_sum_out_reg[3] (.CK (clk), .D (n_235), .SI
       (AT6_sum_out[2]), .SE (scan_en), .Q (AT6_sum_out[3]));
  NOR2BX1 g6864__2802(.AN (n_234), .B (rst), .Y (n_235));
  ADDFX1 g6865__1705(.A (n_232), .B (n_218), .CI (n_228), .CO (n_233),
       .S (n_234));
  ADDFX1 g6866__5122(.A (AT6_sum_out[2]), .B (n_209), .CI (n_224), .CO
       (n_231), .S (n_232));
  SDFFQX1 \AT6_sum_out_reg[2] (.CK (clk), .D (n_230), .SI
       (AT6_sum_out[1]), .SE (scan_en), .Q (AT6_sum_out[2]));
  NOR2BX1 g6868__8246(.AN (n_229), .B (rst), .Y (n_230));
  ADDFX1 g6869__7098(.A (n_225), .B (n_211), .CI (n_214), .CO (n_228),
       .S (n_229));
  ADDFX1 g6871__6131(.A (n_212), .B (n_219), .CI (n_222), .CO (n_226),
       .S (n_227));
  ADDFX1 g6870__1881(.A (AT6_sum_out[1]), .B (n_204), .CI (n_159), .CO
       (n_224), .S (n_225));
  ADDFX1 g6872__5115(.A (n_213), .B (n_220), .CI (n_217), .CO (n_222),
       .S (n_223));
  SDFFQX1 \AT6_sum_out_reg[1] (.CK (clk), .D (n_216), .SI
       (AT6_sum_out[0]), .SE (scan_en), .Q (AT6_sum_out[1]));
  ADDFX1 g6878__7482(.A (\result[4] [4]), .B (\result[5] [4]), .CI
       (n_208), .CO (n_238), .S (n_221));
  ADDFX1 g6879__4733(.A (\result[2] [4]), .B (\result[3] [4]), .CI
       (n_206), .CO (n_219), .S (n_220));
  ADDFX1 g6876__6161(.A (n_203), .B (n_207), .CI (n_210), .CO (n_217),
       .S (n_218));
  NOR2BX1 g6874__9315(.AN (n_215), .B (rst), .Y (n_216));
  ADDFX1 g6875__9945(.A (n_120), .B (n_205), .CI (n_163), .CO (n_214),
       .S (n_215));
  ADDFX1 g6877__2883(.A (\result[0] [4]), .B (\result[1] [4]), .CI
       (n_202), .CO (n_212), .S (n_213));
  ADDFX1 g6880__2346(.A (n_151), .B (n_161), .CI (n_162), .CO (n_210),
       .S (n_211));
  ADDFX1 g6883__1666(.A (\result[4] [3]), .B (\result[5] [3]), .CI
       (n_158), .CO (n_208), .S (n_209));
  ADDFX1 g6884__7410(.A (\result[2] [3]), .B (\result[3] [3]), .CI
       (n_160), .CO (n_206), .S (n_207));
  SDFFRHQX1 \A6M_result_reg[2][0] (.RN (n_251), .CK (clk), .D (n_197),
       .SI (\result[1] [4]), .SE (scan_en), .Q (\result[2] [0]));
  SDFFRHQX1 \A6M_result_reg[1][0] (.RN (n_251), .CK (clk), .D (n_198),
       .SI (\result[0] [4]), .SE (scan_en), .Q (\result[1] [0]));
  SDFFRHQX1 \A6M_result_reg[2][3] (.RN (n_251), .CK (clk), .D (n_201),
       .SI (\result[2] [2]), .SE (scan_en), .Q (\result[2] [3]));
  SDFFRHQX1 \A6M_result_reg[0][0] (.RN (n_251), .CK (clk), .D (n_200),
       .SI (en), .SE (scan_en), .Q (\result[0] [0]));
  SDFFRHQX1 \A6M_result_reg[5][0] (.RN (n_251), .CK (clk), .D (n_167),
       .SI (\result[4] [4]), .SE (scan_en), .Q (\result[5] [0]));
  SDFFRHQX1 \A6M_result_reg[3][4] (.RN (n_251), .CK (clk), .D (n_173),
       .SI (\result[3] [3]), .SE (scan_en), .Q (\result[3] [4]));
  SDFFRHQX1 \A6M_result_reg[4][2] (.RN (n_251), .CK (clk), .D (n_182),
       .SI (\result[4] [1]), .SE (scan_en), .Q (\result[4] [2]));
  SDFFRHQX1 \A6M_result_reg[2][2] (.RN (n_251), .CK (clk), .D (n_171),
       .SI (\result[2] [1]), .SE (scan_en), .Q (\result[2] [2]));
  SDFFRHQX1 \A6M_result_reg[1][1] (.RN (n_251), .CK (clk), .D (n_194),
       .SI (\result[1] [0]), .SE (scan_en), .Q (\result[1] [1]));
  SDFFRHQX1 \A6M_result_reg[5][3] (.RN (n_251), .CK (clk), .D (n_177),
       .SI (\result[5] [2]), .SE (scan_en), .Q (\result[5] [3]));
  SDFFRHQX1 \A6M_result_reg[3][2] (.RN (n_251), .CK (clk), .D (n_187),
       .SI (\result[3] [1]), .SE (scan_en), .Q (\result[3] [2]));
  SDFFRHQX1 \A6M_result_reg[3][0] (.RN (n_251), .CK (clk), .D (n_168),
       .SI (\result[2] [4]), .SE (scan_en), .Q (\result[3] [0]));
  SDFFRHQX1 \A6M_result_reg[4][0] (.RN (n_251), .CK (clk), .D (n_190),
       .SI (\result[3] [4]), .SE (scan_en), .Q (\result[4] [0]));
  SDFFRHQX1 \A6M_result_reg[0][1] (.RN (n_251), .CK (clk), .D (n_166),
       .SI (\result[0] [0]), .SE (scan_en), .Q (\result[0] [1]));
  SDFFRHQX1 \A6M_result_reg[0][2] (.RN (n_251), .CK (clk), .D (n_164),
       .SI (\result[0] [1]), .SE (scan_en), .Q (\result[0] [2]));
  SDFFRHQX1 \A6M_result_reg[0][3] (.RN (n_251), .CK (clk), .D (n_195),
       .SI (\result[0] [2]), .SE (scan_en), .Q (\result[0] [3]));
  SDFFRHQX1 \A6M_result_reg[1][2] (.RN (n_251), .CK (clk), .D (n_193),
       .SI (\result[1] [1]), .SE (scan_en), .Q (\result[1] [2]));
  SDFFRHQX1 \A6M_result_reg[1][3] (.RN (n_251), .CK (clk), .D (n_191),
       .SI (\result[1] [2]), .SE (scan_en), .Q (\result[1] [3]));
  SDFFRHQX1 \A6M_result_reg[2][1] (.RN (n_251), .CK (clk), .D (n_170),
       .SI (\result[2] [0]), .SE (scan_en), .Q (\result[2] [1]));
  SDFFRHQX1 \A6M_result_reg[0][4] (.RN (n_251), .CK (clk), .D (n_176),
       .SI (\result[0] [3]), .SE (scan_en), .Q (\result[0] [4]));
  SDFFRHQX1 \A6M_result_reg[4][1] (.RN (n_251), .CK (clk), .D (n_184),
       .SI (\result[4] [0]), .SE (scan_en), .Q (\result[4] [1]));
  SDFFRHQX1 \A6M_result_reg[4][3] (.RN (n_251), .CK (clk), .D (n_181),
       .SI (\result[4] [2]), .SE (scan_en), .Q (\result[4] [3]));
  SDFFRHQX1 \A6M_result_reg[5][1] (.RN (n_251), .CK (clk), .D (n_180),
       .SI (\result[5] [0]), .SE (scan_en), .Q (\result[5] [1]));
  SDFFRHQX1 \A6M_result_reg[5][2] (.RN (n_251), .CK (clk), .D (n_179),
       .SI (\result[5] [1]), .SE (scan_en), .Q (\result[5] [2]));
  SDFFRHQX1 \A6M_result_reg[3][3] (.RN (n_251), .CK (clk), .D (n_185),
       .SI (\result[3] [2]), .SE (scan_en), .Q (\result[3] [3]));
  SDFFRHQX1 \A6M_result_reg[1][4] (.RN (n_251), .CK (clk), .D (n_175),
       .SI (\result[1] [3]), .SE (scan_en), .Q (\result[1] [4]));
  SDFFRHQX1 \A6M_result_reg[2][4] (.RN (n_251), .CK (clk), .D (n_174),
       .SI (\result[2] [3]), .SE (scan_en), .Q (\result[2] [4]));
  SDFFRHQX1 \A6M_result_reg[4][4] (.RN (n_251), .CK (clk), .D (n_172),
       .SI (\result[4] [3]), .SE (scan_en), .Q (\result[4] [4]));
  SDFFRHQX1 \A6M_result_reg[5][4] (.RN (n_251), .CK (clk), .D (n_189),
       .SI (\result[5] [3]), .SE (scan_en), .Q (\result[5] [4]));
  SDFFRHQX1 \A6M_result_reg[3][1] (.RN (n_251), .CK (clk), .D (n_188),
       .SI (\result[3] [0]), .SE (scan_en), .Q (\result[3] [1]));
  ADDHX1 g6881__6417(.A (AT6_sum_out[0]), .B (n_132), .CO (n_204), .S
       (n_205));
  ADDFX1 g6882__5477(.A (\result[0] [3]), .B (\result[1] [3]), .CI
       (n_150), .CO (n_202), .S (n_203));
  SDFFRHQX1 \A6M_cycle_counter_reg[3] (.RN (n_251), .CK (clk), .D
       (n_156), .SI (A6M_cycle_counter[2]), .SE (scan_en), .Q
       (A6M_cycle_counter[3]));
  SDFFRHQX1 \A6M_cycle_counter_reg[2] (.RN (n_251), .CK (clk), .D
       (n_157), .SI (A6M_cycle_counter[1]), .SE (scan_en), .Q
       (A6M_cycle_counter[2]));
  AO22XL g6952__2398(.A0 (\weight[2] [3]), .A1 (n_196), .B0
       (\result[2] [3]), .B1 (n_199), .Y (n_201));
  AO22XL g6923__5107(.A0 (\weight[0] [0]), .A1 (n_152), .B0
       (\result[0] [0]), .B1 (n_199), .Y (n_200));
  AO22XL g6924__6260(.A0 (\weight[1] [0]), .A1 (n_153), .B0
       (\result[1] [0]), .B1 (n_199), .Y (n_198));
  AO22XL g6925__4319(.A0 (\weight[2] [0]), .A1 (n_196), .B0
       (\result[2] [0]), .B1 (n_199), .Y (n_197));
  OAI22X1 g6931__8428(.A0 (n_9), .A1 (n_165), .B0 (n_12), .B1 (en), .Y
       (n_195));
  OAI22X1 g6932__5526(.A0 (n_6), .A1 (n_192), .B0 (n_16), .B1 (en), .Y
       (n_194));
  OAI22X1 g6933__6783(.A0 (n_13), .A1 (n_192), .B0 (n_4), .B1 (en), .Y
       (n_193));
  OAI22X1 g6934__3680(.A0 (n_8), .A1 (n_192), .B0 (n_7), .B1 (en), .Y
       (n_191));
  AO22XL g6927__1617(.A0 (\weight[4] [0]), .A1 (n_183), .B0
       (\result[4] [0]), .B1 (n_199), .Y (n_190));
  MX2XL g6937__2802(.A (\result[5] [4]), .B (n_149), .S0 (en), .Y
       (n_189));
  AO22XL g6938__1705(.A0 (\weight[3] [1]), .A1 (n_186), .B0
       (\result[3] [1]), .B1 (n_199), .Y (n_188));
  AO22XL g6939__5122(.A0 (\weight[3] [2]), .A1 (n_186), .B0
       (\result[3] [2]), .B1 (n_199), .Y (n_187));
  AO22XL g6940__8246(.A0 (\weight[3] [3]), .A1 (n_186), .B0
       (\result[3] [3]), .B1 (n_199), .Y (n_185));
  AO22XL g6941__7098(.A0 (\weight[4] [1]), .A1 (n_183), .B0
       (\result[4] [1]), .B1 (n_199), .Y (n_184));
  AO22XL g6942__6131(.A0 (\weight[4] [2]), .A1 (n_183), .B0
       (\result[4] [2]), .B1 (n_199), .Y (n_182));
  AO22XL g6943__1881(.A0 (\weight[4] [3]), .A1 (n_183), .B0
       (\result[4] [3]), .B1 (n_199), .Y (n_181));
  AO22XL g6944__5115(.A0 (\weight[5] [1]), .A1 (n_178), .B0
       (\result[5] [1]), .B1 (n_199), .Y (n_180));
  AO22XL g6945__7482(.A0 (\weight[5] [2]), .A1 (n_178), .B0
       (\result[5] [2]), .B1 (n_199), .Y (n_179));
  AO22XL g6946__4733(.A0 (\weight[5] [3]), .A1 (n_178), .B0
       (\result[5] [3]), .B1 (n_199), .Y (n_177));
  MX2XL g6947__6161(.A (\result[0] [4]), .B (n_148), .S0 (en), .Y
       (n_176));
  MX2XL g6948__9315(.A (\result[1] [4]), .B (n_147), .S0 (en), .Y
       (n_175));
  MX2XL g6949__9945(.A (\result[2] [4]), .B (n_141), .S0 (en), .Y
       (n_174));
  MX2XL g6950__2883(.A (\result[3] [4]), .B (n_144), .S0 (en), .Y
       (n_173));
  MX2XL g6951__2346(.A (\result[4] [4]), .B (n_142), .S0 (en), .Y
       (n_172));
  OAI22X1 g6921__1666(.A0 (n_10), .A1 (n_169), .B0 (n_5), .B1 (en), .Y
       (n_171));
  OAI22X1 g6922__7410(.A0 (n_14), .A1 (n_169), .B0 (n_1), .B1 (en), .Y
       (n_170));
  AO22XL g6926__6417(.A0 (\weight[3] [0]), .A1 (n_186), .B0
       (\result[3] [0]), .B1 (n_199), .Y (n_168));
  AO22XL g6928__5477(.A0 (\weight[5] [0]), .A1 (n_178), .B0
       (\result[5] [0]), .B1 (n_199), .Y (n_167));
  OAI22X1 g6929__2398(.A0 (n_0), .A1 (n_165), .B0 (n_11), .B1 (en), .Y
       (n_166));
  OAI22X1 g6930__5107(.A0 (n_2), .A1 (n_165), .B0 (n_15), .B1 (en), .Y
       (n_164));
  ADDFX1 g6885__6260(.A (n_56), .B (n_96), .CI (n_134), .CO (n_162), .S
       (n_163));
  ADDFX1 g6918__4319(.A (\result[2] [2]), .B (\result[3] [2]), .CI
       (n_133), .CO (n_160), .S (n_161));
  ADDFX1 g6920__8428(.A (\result[4] [2]), .B (\result[5] [2]), .CI
       (n_131), .CO (n_158), .S (n_159));
  SDFFQX1 \AT6_sum_out_reg[0] (.CK (clk), .D (n_137), .SI
       (\result[5] [4]), .SE (scan_en), .Q (AT6_sum_out[0]));
  OAI22X1 g6954__5526(.A0 (n_20), .A1 (n_155), .B0 (n_93), .B1 (n_154),
       .Y (n_157));
  OAI22X1 g6955__6783(.A0 (n_94), .A1 (n_155), .B0 (n_91), .B1 (n_154),
       .Y (n_156));
  INVXL g6956(.A (n_192), .Y (n_153));
  INVXL g6957(.A (n_165), .Y (n_152));
  INVXL g6964(.A (n_169), .Y (n_196));
  ADDFX1 g6919__3680(.A (\result[0] [2]), .B (\result[1] [2]), .CI
       (n_95), .CO (n_150), .S (n_151));
  NAND2BXL g6958__1617(.AN (\weight[5] [4]), .B (n_139), .Y (n_149));
  NAND2BXL g6959__2802(.AN (\weight[0] [4]), .B (n_145), .Y (n_148));
  NAND2BXL g6960__1705(.AN (\weight[1] [4]), .B (n_146), .Y (n_147));
  NAND2X1 g6962__5122(.A (en), .B (n_146), .Y (n_192));
  NAND2X1 g6963__8246(.A (en), .B (n_145), .Y (n_165));
  AND2XL g6961__7098(.A (en), .B (n_143), .Y (n_186));
  NAND2BXL g6966__6131(.AN (\weight[3] [4]), .B (n_143), .Y (n_144));
  NAND2BXL g6967__1881(.AN (\weight[4] [4]), .B (n_138), .Y (n_142));
  NAND2BXL g6965__5115(.AN (\weight[2] [4]), .B (n_140), .Y (n_141));
  NAND2X1 g6971__7482(.A (en), .B (n_140), .Y (n_169));
  AND2XL g6968__4733(.A (en), .B (n_139), .Y (n_178));
  AND2XL g6969__6161(.A (en), .B (n_138), .Y (n_183));
  SDFFRHQX4 A6M_en_reg(.RN (n_251), .CK (clk), .D (n_129), .SI
       (A6M_cycle_counter[3]), .SE (scan_en), .Q (en));
  NOR2X1 g6902__9315(.A (rst), .B (n_130), .Y (n_137));
  NOR2X1 g6975__9945(.A (n_89), .B (n_128), .Y (n_155));
  OAI211X1 g6976__2883(.A0 (n_135), .A1 (n_124), .B0 (n_115), .C0
       (n_112), .Y (n_146));
  OAI211X1 g6979__2346(.A0 (n_136), .A1 (n_126), .B0 (n_110), .C0
       (n_122), .Y (n_145));
  OAI211X1 g6982__1666(.A0 (n_136), .A1 (n_127), .B0 (n_117), .C0
       (n_108), .Y (n_140));
  OAI211X1 g6981__7410(.A0 (n_135), .A1 (n_98), .B0 (n_121), .C0
       (n_99), .Y (n_143));
  OAI211X1 g6980__6417(.A0 (n_135), .A1 (n_111), .B0 (n_102), .C0
       (n_105), .Y (n_139));
  OAI211X1 g6983__5477(.A0 (n_136), .A1 (n_97), .B0 (n_100), .C0
       (n_101), .Y (n_138));
  SDFFRHQX1 \A6M_cycle_counter_reg[1] (.RN (n_251), .CK (clk), .D
       (n_90), .SI (A6M_cycle_counter[0]), .SE (scan_en), .Q
       (A6M_cycle_counter[1]));
  ADDFX1 g6973__2398(.A (\result[2] [1]), .B (\result[3] [1]), .CI
       (n_23), .CO (n_133), .S (n_134));
  ADDFX1 g6974__5107(.A (\result[4] [1]), .B (\result[5] [1]), .CI
       (n_22), .CO (n_131), .S (n_132));
  XNOR2X1 g6953__6260(.A (n_119), .B (n_118), .Y (n_130));
  OAI2BB1X1 g6984__4319(.A0N (en), .A1N (n_92), .B0 (n_87), .Y (n_129));
  AOI21XL g6985__8428(.A0 (A6M_cycle_counter[1]), .A1
       (A6M_cycle_counter[0]), .B0 (n_154), .Y (n_128));
  SDFFRHQX1 \A6M_activation_reg_reg[4][2] (.RN (n_251), .CK (clk), .D
       (n_67), .SI (\A6M_activation_reg[4] [1]), .SE (scan_en), .Q
       (\A6M_activation_reg[4] [2]));
  SDFFRHQX1 \A6M_activation_reg_reg[1][6] (.RN (n_251), .CK (clk), .D
       (n_86), .SI (\A6M_activation_reg[1] [5]), .SE (scan_en), .Q
       (\A6M_activation_reg[1] [6]));
  SDFFRHQX1 \A6M_activation_reg_reg[4][5] (.RN (n_251), .CK (clk), .D
       (n_64), .SI (\A6M_activation_reg[4] [4]), .SE (scan_en), .Q
       (\A6M_activation_reg[4] [5]));
  SDFFRHQX1 \A6M_activation_reg_reg[5][4] (.RN (n_251), .CK (clk), .D
       (n_57), .SI (\A6M_activation_reg[5] [3]), .SE (scan_en), .Q
       (\A6M_activation_reg[5] [4]));
  SDFFRHQX1 \A6M_activation_reg_reg[2][6] (.RN (n_251), .CK (clk), .D
       (n_31), .SI (\A6M_activation_reg[2] [5]), .SE (scan_en), .Q
       (\A6M_activation_reg[2] [6]));
  SDFFRHQX1 \A6M_activation_reg_reg[2][3] (.RN (n_251), .CK (clk), .D
       (n_34), .SI (\A6M_activation_reg[2] [2]), .SE (scan_en), .Q
       (\A6M_activation_reg[2] [3]));
  SDFFRHQX1 \A6M_activation_reg_reg[5][2] (.RN (n_251), .CK (clk), .D
       (n_58), .SI (\A6M_activation_reg[5] [1]), .SE (scan_en), .Q
       (\A6M_activation_reg[5] [2]));
  SDFFRHQX1 \A6M_activation_reg_reg[4][4] (.RN (n_251), .CK (clk), .D
       (n_65), .SI (\A6M_activation_reg[4] [3]), .SE (scan_en), .Q
       (\A6M_activation_reg[4] [4]));
  SDFFRHQX1 \A6M_activation_reg_reg[0][2] (.RN (n_251), .CK (clk), .D
       (n_48), .SI (\A6M_activation_reg[0] [1]), .SE (scan_en), .Q
       (\A6M_activation_reg[0] [2]));
  SDFFRHQX1 \A6M_activation_reg_reg[1][2] (.RN (n_251), .CK (clk), .D
       (n_47), .SI (\A6M_activation_reg[1] [1]), .SE (scan_en), .Q
       (\A6M_activation_reg[1] [2]));
  SDFFRHQX1 \A6M_activation_reg_reg[3][0] (.RN (n_251), .CK (clk), .D
       (n_77), .SI (\A6M_activation_reg[2] [7]), .SE (scan_en), .Q
       (\A6M_activation_reg[3] [0]));
  SDFFRHQX1 \A6M_activation_reg_reg[2][0] (.RN (n_251), .CK (clk), .D
       (n_88), .SI (\A6M_activation_reg[1] [7]), .SE (scan_en), .Q
       (\A6M_activation_reg[2] [0]));
  SDFFRHQX1 \A6M_activation_reg_reg[1][7] (.RN (n_251), .CK (clk), .D
       (n_38), .SI (\A6M_activation_reg[1] [6]), .SE (scan_en), .Q
       (\A6M_activation_reg[1] [7]));
  SDFFRHQX1 \A6M_activation_reg_reg[3][6] (.RN (n_251), .CK (clk), .D
       (n_71), .SI (\A6M_activation_reg[3] [5]), .SE (scan_en), .Q
       (\A6M_activation_reg[3] [6]));
  SDFFRHQX1 \A6M_activation_reg_reg[3][2] (.RN (n_251), .CK (clk), .D
       (n_75), .SI (\A6M_activation_reg[3] [1]), .SE (scan_en), .Q
       (\A6M_activation_reg[3] [2]));
  SDFFRHQX1 \A6M_activation_reg_reg[5][7] (.RN (n_251), .CK (clk), .D
       (n_51), .SI (\A6M_activation_reg[5] [6]), .SE (scan_en), .Q
       (\A6M_activation_reg[5] [7]));
  SDFFRHQX1 \A6M_activation_reg_reg[2][7] (.RN (n_251), .CK (clk), .D
       (n_30), .SI (\A6M_activation_reg[2] [6]), .SE (scan_en), .Q
       (\A6M_activation_reg[2] [7]));
  SDFFRHQX1 \A6M_activation_reg_reg[3][1] (.RN (n_251), .CK (clk), .D
       (n_76), .SI (\A6M_activation_reg[3] [0]), .SE (scan_en), .Q
       (\A6M_activation_reg[3] [1]));
  SDFFRHQX1 \A6M_activation_reg_reg[3][3] (.RN (n_251), .CK (clk), .D
       (n_74), .SI (\A6M_activation_reg[3] [2]), .SE (scan_en), .Q
       (\A6M_activation_reg[3] [3]));
  SDFFRHQX1 \A6M_activation_reg_reg[3][4] (.RN (n_251), .CK (clk), .D
       (n_73), .SI (\A6M_activation_reg[3] [3]), .SE (scan_en), .Q
       (\A6M_activation_reg[3] [4]));
  SDFFRHQX1 \A6M_activation_reg_reg[3][5] (.RN (n_251), .CK (clk), .D
       (n_72), .SI (\A6M_activation_reg[3] [4]), .SE (scan_en), .Q
       (\A6M_activation_reg[3] [5]));
  SDFFRHQX1 \A6M_activation_reg_reg[3][7] (.RN (n_251), .CK (clk), .D
       (n_70), .SI (\A6M_activation_reg[3] [6]), .SE (scan_en), .Q
       (\A6M_activation_reg[3] [7]));
  SDFFRHQX1 \A6M_activation_reg_reg[0][1] (.RN (n_251), .CK (clk), .D
       (n_49), .SI (\A6M_activation_reg[0] [0]), .SE (scan_en), .Q
       (\A6M_activation_reg[0] [1]));
  SDFFRHQX1 \A6M_activation_reg_reg[4][1] (.RN (n_251), .CK (clk), .D
       (n_68), .SI (\A6M_activation_reg[4] [0]), .SE (scan_en), .Q
       (\A6M_activation_reg[4] [1]));
  SDFFRHQX1 \A6M_activation_reg_reg[5][6] (.RN (n_251), .CK (clk), .D
       (n_52), .SI (\A6M_activation_reg[5] [5]), .SE (scan_en), .Q
       (\A6M_activation_reg[5] [6]));
  SDFFRHQX1 \A6M_activation_reg_reg[4][3] (.RN (n_251), .CK (clk), .D
       (n_66), .SI (\A6M_activation_reg[4] [2]), .SE (scan_en), .Q
       (\A6M_activation_reg[4] [3]));
  SDFFRHQX1 \A6M_activation_reg_reg[1][4] (.RN (n_251), .CK (clk), .D
       (n_39), .SI (\A6M_activation_reg[1] [3]), .SE (scan_en), .Q
       (\A6M_activation_reg[1] [4]));
  SDFFRHQX1 \A6M_activation_reg_reg[4][6] (.RN (n_251), .CK (clk), .D
       (n_63), .SI (\A6M_activation_reg[4] [5]), .SE (scan_en), .Q
       (\A6M_activation_reg[4] [6]));
  SDFFRHQX1 \A6M_activation_reg_reg[4][7] (.RN (n_251), .CK (clk), .D
       (n_61), .SI (\A6M_activation_reg[4] [6]), .SE (scan_en), .Q
       (\A6M_activation_reg[4] [7]));
  SDFFRHQX1 \A6M_activation_reg_reg[5][0] (.RN (n_251), .CK (clk), .D
       (n_60), .SI (\A6M_activation_reg[4] [7]), .SE (scan_en), .Q
       (\A6M_activation_reg[5] [0]));
  SDFFRHQX1 \A6M_activation_reg_reg[5][1] (.RN (n_251), .CK (clk), .D
       (n_59), .SI (\A6M_activation_reg[5] [0]), .SE (scan_en), .Q
       (\A6M_activation_reg[5] [1]));
  SDFFRHQX1 \A6M_activation_reg_reg[5][3] (.RN (n_251), .CK (clk), .D
       (n_29), .SI (\A6M_activation_reg[5] [2]), .SE (scan_en), .Q
       (\A6M_activation_reg[5] [3]));
  SDFFRHQX1 \A6M_activation_reg_reg[5][5] (.RN (n_251), .CK (clk), .D
       (n_53), .SI (\A6M_activation_reg[5] [4]), .SE (scan_en), .Q
       (\A6M_activation_reg[5] [5]));
  SDFFRHQX1 \A6M_activation_reg_reg[0][0] (.RN (n_251), .CK (clk), .D
       (n_50), .SI (scan_in), .SE (scan_en), .Q
       (\A6M_activation_reg[0] [0]));
  SDFFRHQX1 \A6M_activation_reg_reg[1][5] (.RN (n_251), .CK (clk), .D
       (n_40), .SI (\A6M_activation_reg[1] [4]), .SE (scan_en), .Q
       (\A6M_activation_reg[1] [5]));
  SDFFRHQX1 \A6M_activation_reg_reg[4][0] (.RN (n_251), .CK (clk), .D
       (n_69), .SI (\A6M_activation_reg[3] [7]), .SE (scan_en), .Q
       (\A6M_activation_reg[4] [0]));
  SDFFRHQX1 \A6M_activation_reg_reg[0][3] (.RN (n_251), .CK (clk), .D
       (n_43), .SI (\A6M_activation_reg[0] [2]), .SE (scan_en), .Q
       (\A6M_activation_reg[0] [3]));
  SDFFRHQX1 \A6M_activation_reg_reg[0][5] (.RN (n_251), .CK (clk), .D
       (n_62), .SI (\A6M_activation_reg[0] [4]), .SE (scan_en), .Q
       (\A6M_activation_reg[0] [5]));
  SDFFRHQX1 \A6M_activation_reg_reg[0][6] (.RN (n_251), .CK (clk), .D
       (n_46), .SI (\A6M_activation_reg[0] [5]), .SE (scan_en), .Q
       (\A6M_activation_reg[0] [6]));
  SDFFRHQX1 \A6M_activation_reg_reg[0][7] (.RN (n_251), .CK (clk), .D
       (n_44), .SI (\A6M_activation_reg[0] [6]), .SE (scan_en), .Q
       (\A6M_activation_reg[0] [7]));
  SDFFRHQX1 \A6M_activation_reg_reg[2][5] (.RN (n_251), .CK (clk), .D
       (n_32), .SI (\A6M_activation_reg[2] [4]), .SE (scan_en), .Q
       (\A6M_activation_reg[2] [5]));
  SDFFRHQX1 \A6M_activation_reg_reg[2][4] (.RN (n_251), .CK (clk), .D
       (n_33), .SI (\A6M_activation_reg[2] [3]), .SE (scan_en), .Q
       (\A6M_activation_reg[2] [4]));
  SDFFRHQX1 \A6M_activation_reg_reg[2][2] (.RN (n_251), .CK (clk), .D
       (n_35), .SI (\A6M_activation_reg[2] [1]), .SE (scan_en), .Q
       (\A6M_activation_reg[2] [2]));
  SDFFRHQX1 \A6M_activation_reg_reg[0][4] (.RN (n_251), .CK (clk), .D
       (n_45), .SI (\A6M_activation_reg[0] [3]), .SE (scan_en), .Q
       (\A6M_activation_reg[0] [4]));
  SDFFRHQX1 \A6M_activation_reg_reg[2][1] (.RN (n_251), .CK (clk), .D
       (n_36), .SI (\A6M_activation_reg[2] [0]), .SE (scan_en), .Q
       (\A6M_activation_reg[2] [1]));
  SDFFRHQX1 \A6M_activation_reg_reg[1][3] (.RN (n_251), .CK (clk), .D
       (n_37), .SI (\A6M_activation_reg[1] [2]), .SE (scan_en), .Q
       (\A6M_activation_reg[1] [3]));
  SDFFRHQX1 \A6M_activation_reg_reg[1][1] (.RN (n_251), .CK (clk), .D
       (n_41), .SI (\A6M_activation_reg[1] [0]), .SE (scan_en), .Q
       (\A6M_activation_reg[1] [1]));
  SDFFRHQX1 \A6M_activation_reg_reg[1][0] (.RN (n_251), .CK (clk), .D
       (n_42), .SI (\A6M_activation_reg[0] [7]), .SE (scan_en), .Q
       (\A6M_activation_reg[1] [0]));
  AOI221X1 g7037__5526(.A0 (\A6M_activation_reg[2] [1]), .A1 (n_123),
       .B0 (\A6M_activation_reg[2] [4]), .B1 (n_125), .C0 (n_81), .Y
       (n_127));
  AOI221X1 g7038__6783(.A0 (\A6M_activation_reg[0] [5]), .A1 (n_83),
       .B0 (\A6M_activation_reg[0] [4]), .B1 (n_125), .C0 (n_85), .Y
       (n_126));
  AOI221X1 g7039__3680(.A0 (\A6M_activation_reg[1] [3]), .A1 (n_123),
       .B0 (\A6M_activation_reg[1] [6]), .B1 (n_125), .C0 (n_84), .Y
       (n_124));
  AOI22X1 g7032__1617(.A0 (\A6M_activation_reg[0] [7]), .A1 (n_107),
       .B0 (\A6M_activation_reg[0] [3]), .B1 (n_116), .Y (n_122));
  AOI22X1 g7028__2802(.A0 (\A6M_activation_reg[3] [4]), .A1 (n_114),
       .B0 (\A6M_activation_reg[3] [0]), .B1 (n_113), .Y (n_121));
  AND2XL g6970__1705(.A (n_119), .B (n_118), .Y (n_120));
  AOI22X1 g7029__5122(.A0 (\A6M_activation_reg[2] [3]), .A1 (n_116),
       .B0 (\A6M_activation_reg[2] [2]), .B1 (n_109), .Y (n_117));
  AOI22X1 g7031__8246(.A0 (\A6M_activation_reg[1] [4]), .A1 (n_114),
       .B0 (\A6M_activation_reg[1] [0]), .B1 (n_113), .Y (n_115));
  AOI22X1 g7030__7098(.A0 (\A6M_activation_reg[1] [5]), .A1 (n_104),
       .B0 (\A6M_activation_reg[1] [1]), .B1 (n_103), .Y (n_112));
  AOI221X1 g7034__6131(.A0 (\A6M_activation_reg[5] [3]), .A1 (n_123),
       .B0 (\A6M_activation_reg[5] [6]), .B1 (n_125), .C0 (n_78), .Y
       (n_111));
  AOI22X1 g7033__1881(.A0 (\A6M_activation_reg[0] [6]), .A1 (n_106),
       .B0 (\A6M_activation_reg[0] [2]), .B1 (n_109), .Y (n_110));
  AOI22X1 g7022__5115(.A0 (\A6M_activation_reg[2] [7]), .A1 (n_107),
       .B0 (\A6M_activation_reg[2] [6]), .B1 (n_106), .Y (n_108));
  AOI22X1 g7023__7482(.A0 (\A6M_activation_reg[5] [5]), .A1 (n_104),
       .B0 (\A6M_activation_reg[5] [1]), .B1 (n_103), .Y (n_105));
  AOI22X1 g7024__4733(.A0 (\A6M_activation_reg[5] [4]), .A1 (n_114),
       .B0 (\A6M_activation_reg[5] [0]), .B1 (n_113), .Y (n_102));
  AOI22X1 g7025__6161(.A0 (\A6M_activation_reg[4] [7]), .A1 (n_107),
       .B0 (\A6M_activation_reg[4] [3]), .B1 (n_116), .Y (n_101));
  AOI22X1 g7026__9315(.A0 (\A6M_activation_reg[4] [6]), .A1 (n_106),
       .B0 (\A6M_activation_reg[4] [2]), .B1 (n_109), .Y (n_100));
  AOI22X1 g7027__9945(.A0 (\A6M_activation_reg[3] [5]), .A1 (n_104),
       .B0 (\A6M_activation_reg[3] [1]), .B1 (n_103), .Y (n_99));
  AOI221X1 g7036__2883(.A0 (\A6M_activation_reg[3] [3]), .A1 (n_123),
       .B0 (\A6M_activation_reg[3] [6]), .B1 (n_125), .C0 (n_80), .Y
       (n_98));
  AOI221X1 g7035__2346(.A0 (\A6M_activation_reg[4] [1]), .A1 (n_123),
       .B0 (\A6M_activation_reg[4] [4]), .B1 (n_125), .C0 (n_79), .Y
       (n_97));
  SDFFRHQX1 \A6M_cycle_counter_reg[0] (.RN (n_251), .CK (clk), .D
       (n_25), .SI (\A6M_activation_reg[5] [7]), .SE (scan_en), .Q
       (A6M_cycle_counter[0]));
  ADDFX1 g6972__1666(.A (\result[0] [1]), .B (\result[1] [1]), .CI
       (n_17), .CO (n_95), .S (n_96));
  OAI21X1 g7054__7410(.A0 (n_94), .A1 (n_93), .B0 (en), .Y (n_154));
  NAND3BXL g7086__6417(.AN (n_93), .B (1'b1), .C
       (A6M_cycle_counter[3]), .Y (n_92));
  INVXL g7120(.A (n_113), .Y (n_91));
  AO22XL g6986__5477(.A0 (en), .A1 (n_21), .B0 (n_89), .B1
       (A6M_cycle_counter[1]), .Y (n_90));
  XNOR2X1 g6987__2398(.A (n_55), .B (n_54), .Y (n_118));
  MX2XL g7089__5107(.A (\activation[2] [0]), .B
       (\A6M_activation_reg[2] [0]), .S0 (n_87), .Y (n_88));
  MX2XL g7059__6260(.A (\activation[1] [6]), .B
       (\A6M_activation_reg[1] [6]), .S0 (n_87), .Y (n_86));
  AO22XL g7060__4319(.A0 (\A6M_activation_reg[0] [1]), .A1 (n_123), .B0
       (\A6M_activation_reg[0] [0]), .B1 (n_82), .Y (n_85));
  AO22XL g7061__8428(.A0 (\A6M_activation_reg[1] [7]), .A1 (n_83), .B0
       (\A6M_activation_reg[1] [2]), .B1 (n_82), .Y (n_84));
  AO22XL g7062__5526(.A0 (\A6M_activation_reg[2] [5]), .A1 (n_83), .B0
       (\A6M_activation_reg[2] [0]), .B1 (n_82), .Y (n_81));
  AO22XL g7063__6783(.A0 (\A6M_activation_reg[3] [7]), .A1 (n_83), .B0
       (\A6M_activation_reg[3] [2]), .B1 (n_82), .Y (n_80));
  AO22XL g7064__3680(.A0 (\A6M_activation_reg[4] [5]), .A1 (n_83), .B0
       (\A6M_activation_reg[4] [0]), .B1 (n_82), .Y (n_79));
  AO22XL g7065__1617(.A0 (\A6M_activation_reg[5] [7]), .A1 (n_83), .B0
       (\A6M_activation_reg[5] [2]), .B1 (n_82), .Y (n_78));
  MX2XL g7066__2802(.A (\activation[3] [0]), .B
       (\A6M_activation_reg[3] [0]), .S0 (n_87), .Y (n_77));
  MX2XL g7067__1705(.A (\activation[3] [1]), .B
       (\A6M_activation_reg[3] [1]), .S0 (n_87), .Y (n_76));
  MX2XL g7068__5122(.A (\activation[3] [2]), .B
       (\A6M_activation_reg[3] [2]), .S0 (n_87), .Y (n_75));
  MX2XL g7069__8246(.A (\activation[3] [3]), .B
       (\A6M_activation_reg[3] [3]), .S0 (n_87), .Y (n_74));
  MX2XL g7070__7098(.A (\activation[3] [4]), .B
       (\A6M_activation_reg[3] [4]), .S0 (n_87), .Y (n_73));
  MX2XL g7071__6131(.A (\activation[3] [5]), .B
       (\A6M_activation_reg[3] [5]), .S0 (n_87), .Y (n_72));
  MX2XL g7072__1881(.A (\activation[3] [6]), .B
       (\A6M_activation_reg[3] [6]), .S0 (n_87), .Y (n_71));
  MX2XL g7073__5115(.A (\activation[3] [7]), .B
       (\A6M_activation_reg[3] [7]), .S0 (n_87), .Y (n_70));
  MX2XL g7074__7482(.A (\activation[4] [0]), .B
       (\A6M_activation_reg[4] [0]), .S0 (n_87), .Y (n_69));
  MX2XL g7075__4733(.A (\activation[4] [1]), .B
       (\A6M_activation_reg[4] [1]), .S0 (n_87), .Y (n_68));
  MX2XL g7076__6161(.A (\activation[4] [2]), .B
       (\A6M_activation_reg[4] [2]), .S0 (n_87), .Y (n_67));
  MX2XL g7077__9315(.A (\activation[4] [3]), .B
       (\A6M_activation_reg[4] [3]), .S0 (n_87), .Y (n_66));
  MX2XL g7078__9945(.A (\activation[4] [4]), .B
       (\A6M_activation_reg[4] [4]), .S0 (n_87), .Y (n_65));
  MX2XL g7079__2883(.A (\activation[4] [5]), .B
       (\A6M_activation_reg[4] [5]), .S0 (n_87), .Y (n_64));
  MX2XL g7080__2346(.A (\activation[4] [6]), .B
       (\A6M_activation_reg[4] [6]), .S0 (n_87), .Y (n_63));
  MX2XL g7081__1666(.A (\activation[0] [5]), .B
       (\A6M_activation_reg[0] [5]), .S0 (n_87), .Y (n_62));
  MX2XL g7082__7410(.A (\activation[4] [7]), .B
       (\A6M_activation_reg[4] [7]), .S0 (n_87), .Y (n_61));
  MX2XL g7083__6417(.A (\activation[5] [0]), .B
       (\A6M_activation_reg[5] [0]), .S0 (n_87), .Y (n_60));
  MX2XL g7084__5477(.A (\activation[5] [1]), .B
       (\A6M_activation_reg[5] [1]), .S0 (n_87), .Y (n_59));
  MX2XL g7085__2398(.A (\activation[5] [2]), .B
       (\A6M_activation_reg[5] [2]), .S0 (n_87), .Y (n_58));
  MX2XL g7088__5107(.A (\activation[5] [4]), .B
       (\A6M_activation_reg[5] [4]), .S0 (n_87), .Y (n_57));
  NOR2BX1 g7055__6260(.AN (n_55), .B (n_54), .Y (n_56));
  MX2XL g7090__4319(.A (\activation[5] [5]), .B
       (\A6M_activation_reg[5] [5]), .S0 (n_87), .Y (n_53));
  MX2XL g7091__8428(.A (\activation[5] [6]), .B
       (\A6M_activation_reg[5] [6]), .S0 (n_87), .Y (n_52));
  MX2XL g7092__5526(.A (\activation[5] [7]), .B
       (\A6M_activation_reg[5] [7]), .S0 (n_87), .Y (n_51));
  MX2XL g7093__6783(.A (\activation[0] [0]), .B
       (\A6M_activation_reg[0] [0]), .S0 (n_87), .Y (n_50));
  MX2XL g7094__3680(.A (\activation[0] [1]), .B
       (\A6M_activation_reg[0] [1]), .S0 (n_87), .Y (n_49));
  MX2XL g7095__1617(.A (\activation[0] [2]), .B
       (\A6M_activation_reg[0] [2]), .S0 (n_87), .Y (n_48));
  MX2XL g7096__2802(.A (\activation[1] [2]), .B
       (\A6M_activation_reg[1] [2]), .S0 (n_87), .Y (n_47));
  MX2XL g7097__1705(.A (\activation[0] [6]), .B
       (\A6M_activation_reg[0] [6]), .S0 (n_87), .Y (n_46));
  MX2XL g7098__5122(.A (\activation[0] [4]), .B
       (\A6M_activation_reg[0] [4]), .S0 (n_87), .Y (n_45));
  MX2XL g7099__8246(.A (\activation[0] [7]), .B
       (\A6M_activation_reg[0] [7]), .S0 (n_87), .Y (n_44));
  MX2XL g7100__7098(.A (\activation[0] [3]), .B
       (\A6M_activation_reg[0] [3]), .S0 (n_87), .Y (n_43));
  MX2XL g7101__6131(.A (\activation[1] [0]), .B
       (\A6M_activation_reg[1] [0]), .S0 (n_87), .Y (n_42));
  MX2XL g7102__1881(.A (\activation[1] [1]), .B
       (\A6M_activation_reg[1] [1]), .S0 (n_87), .Y (n_41));
  MX2XL g7103__5115(.A (\activation[1] [5]), .B
       (\A6M_activation_reg[1] [5]), .S0 (n_87), .Y (n_40));
  MX2XL g7104__7482(.A (\activation[1] [4]), .B
       (\A6M_activation_reg[1] [4]), .S0 (n_87), .Y (n_39));
  MX2XL g7105__4733(.A (\activation[1] [7]), .B
       (\A6M_activation_reg[1] [7]), .S0 (n_87), .Y (n_38));
  MX2XL g7106__6161(.A (\activation[1] [3]), .B
       (\A6M_activation_reg[1] [3]), .S0 (n_87), .Y (n_37));
  MX2XL g7107__9315(.A (\activation[2] [1]), .B
       (\A6M_activation_reg[2] [1]), .S0 (n_87), .Y (n_36));
  MX2XL g7108__9945(.A (\activation[2] [2]), .B
       (\A6M_activation_reg[2] [2]), .S0 (n_87), .Y (n_35));
  MX2XL g7109__2883(.A (\activation[2] [3]), .B
       (\A6M_activation_reg[2] [3]), .S0 (n_87), .Y (n_34));
  MX2XL g7110__2346(.A (\activation[2] [4]), .B
       (\A6M_activation_reg[2] [4]), .S0 (n_87), .Y (n_33));
  MX2XL g7111__1666(.A (\activation[2] [5]), .B
       (\A6M_activation_reg[2] [5]), .S0 (n_87), .Y (n_32));
  MX2XL g7112__7410(.A (\activation[2] [6]), .B
       (\A6M_activation_reg[2] [6]), .S0 (n_87), .Y (n_31));
  MX2XL g7113__6417(.A (\activation[2] [7]), .B
       (\A6M_activation_reg[2] [7]), .S0 (n_87), .Y (n_30));
  MX2XL g7114__5477(.A (\activation[5] [3]), .B
       (\A6M_activation_reg[5] [3]), .S0 (n_87), .Y (n_29));
  NOR2X1 g7119__2398(.A (n_26), .B (n_135), .Y (n_109));
  NOR2X1 g7123__5107(.A (n_136), .B (n_27), .Y (n_114));
  NOR2X1 g7124__6260(.A (n_136), .B (n_28), .Y (n_103));
  NOR2X1 g7125__4319(.A (n_28), .B (n_135), .Y (n_116));
  NOR2X1 g7115__8428(.A (n_135), .B (n_27), .Y (n_106));
  NOR2X1 g7126__5526(.A (n_26), .B (n_136), .Y (n_113));
  MX2XL g7087__6783(.A (en), .B (n_89), .S0 (A6M_cycle_counter[0]), .Y
       (n_25));
  NOR2X1 g7116__3680(.A (n_135), .B (n_24), .Y (n_107));
  NAND2X1 g7117__1617(.A (A6M_cycle_counter[1]), .B (n_125), .Y (n_93));
  NOR2X1 g7118__2802(.A (n_136), .B (n_24), .Y (n_104));
  ADDHX1 g7058__1705(.A (\result[2] [0]), .B (\result[3] [0]), .CO
       (n_23), .S (n_55));
  ADDHX1 g7057__5122(.A (\result[4] [0]), .B (\result[5] [0]), .CO
       (n_22), .S (n_119));
  OAI22XL g7121__8246(.A0 (A6M_cycle_counter[1]), .A1 (n_19), .B0
       (A6M_cycle_counter[0]), .B1 (n_18), .Y (n_21));
  INVX1 g7128(.A (n_123), .Y (n_28));
  INVX1 g7127(.A (n_82), .Y (n_26));
  INVX1 g7134(.A (n_125), .Y (n_27));
  XNOR2X1 g7122__7098(.A (\result[0] [0]), .B (\result[1] [0]), .Y
       (n_54));
  NOR2X1 g7131__6131(.A (n_20), .B (n_19), .Y (n_82));
  NAND2X1 g7130__1881(.A (A6M_cycle_counter[1]), .B (n_94), .Y (n_136));
  NOR2X1 g7132__5115(.A (A6M_cycle_counter[0]), .B (n_20), .Y (n_123));
  INVX1 g7133(.A (n_83), .Y (n_24));
  NAND2X1 g7136__7482(.A (n_18), .B (n_94), .Y (n_135));
  NOR2X1 g7138__4733(.A (A6M_cycle_counter[2]), .B (n_19), .Y (n_125));
  OR2X2 g7139__6161(.A (n_3), .B (en), .Y (n_87));
  NOR2X1 g7129__9315(.A (start), .B (en), .Y (n_89));
  AND2XL g7135__9945(.A (\result[1] [0]), .B (\result[0] [0]), .Y
       (n_17));
  NOR2X1 g7137__2883(.A (A6M_cycle_counter[0]), .B
       (A6M_cycle_counter[2]), .Y (n_83));
  INVXL g7148(.A (\result[1] [1]), .Y (n_16));
  INVXL g7146(.A (\result[0] [2]), .Y (n_15));
  INVX1 g7156(.A (\weight[2] [1]), .Y (n_14));
  INVX1 g7140(.A (\weight[1] [2]), .Y (n_13));
  INVXL g7160(.A (\result[0] [3]), .Y (n_12));
  INVXL g7161(.A (\result[0] [1]), .Y (n_11));
  INVX1 g7154(.A (\weight[2] [2]), .Y (n_10));
  INVX1 g7141(.A (\weight[0] [3]), .Y (n_9));
  INVX1 g7150(.A (A6M_cycle_counter[0]), .Y (n_19));
  INVX1 g7158(.A (A6M_cycle_counter[2]), .Y (n_20));
  INVX1 g7159(.A (A6M_cycle_counter[3]), .Y (n_94));
  INVX1 g7153(.A (\weight[1] [3]), .Y (n_8));
  INVXL g7147(.A (\result[1] [3]), .Y (n_7));
  INVX1 g7142(.A (\weight[1] [1]), .Y (n_6));
  INVXL g7144(.A (\result[2] [2]), .Y (n_5));
  INVXL g7149(.A (\result[1] [2]), .Y (n_4));
  INVX1 g7157(.A (start), .Y (n_3));
  INVX1 g7155(.A (\weight[0] [2]), .Y (n_2));
  INVXL g7145(.A (\result[2] [1]), .Y (n_1));
  INVX1 g7143(.A (\weight[0] [1]), .Y (n_0));
  INVX1 g7162(.A (A6M_cycle_counter[1]), .Y (n_18));
  INVX1 g7151(.A (en), .Y (n_199));
  INVXL g7152(.A (rst), .Y (n_251));
endmodule

