#==============================================================================
# Hierarchical dofile generated by Conformal LEC
# Version: 24.10-p100 (30-May-2024) (64 bit executable)
#------------------------------------------------------------------------------
# Hierarchical dofile is generated by following configuration:
# write_hier_compare_dofile
#     -NOExact_pin_match
#     -Constraints
#     -INPUT_OUTPUT_Pin_equivalence
#     -BALANCED_EXTractions
#     -PREPEND_String 'report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -flowgraph -verbose'
#     -Usage
#     -Replace
#     -VERbose
#     'hier_tmp3.lec.do'
#------------------------------------------------------------------------------
# For additional reporting on 'not written' modules, see the 'VERBOSE REPORTING'
# section at the end of the hierarchical dofile
#------------------------------------------------------------------------------
# The command 'set module property' sets the instance context for the current
# root module. It is intended only for hierarchical comparison, and should
# not be modified by the user.
#------------------------------------------------------------------------------
# TERMS AND NOTATIONS USED
#------------------------------------------------------------------------------
# Module Instantiation Ratio: Average number of instantiations per matching module
# Wrapper size: Logic gates enclosing the module's instance, and bounded by key-points
# Periphery size: Logic gates in the fanin and fanout cone of instance's input and output boundary, and bounded by key-points
# 0: Indicates pin is constant zero
# 1: Indicates pin is constant one
# X: Indicates pin is full DC
# U: Indicates pin is unreachable
# Z: Indicates pin is floating
# KP<--: Indicates pin's fanin is directly connected to key-point (ignores buffers/inverters)
# -->KP: Indicates pin's fanout is directly connected to key-point (ignores buffers/inverters)
# REP: Indicates pin is representative pin
# EQ_REP: <polarity> rep_pinname>: Indicates pin is a member EQ pin with
# 'rep_pinname' specifying the representative, and 'polarity' specifying
# if it is positive or negative equivalent
# = : Indicates that the pins on LHS and RHS are mapped
# + : Indicates positive polarity for pin mapping
# - : Indicates negative polarity for pin mapping
# ? : Indicates unknown polarity for pin mapping
# G: Indicates that the pin belongs to Golden
# R: Indicates that the pin belongs to Revised
# IN: Indicates that the pin is an Input pin
# OUT: Indicates that the pin is an Output pin
# IO: Indicates that the pin is an Inout pin. Polarity of Inout pin is
#     always '?' because of name-only mapping
#==============================================================================

set_system_mode setup
# Root Modules
# Comparing
#-------------------------------------------------------------------------------
# MODULE serial_to_parallel (G) INSTANCE / (G)
# MODULE serial_to_parallel (R) INSTANCE / (R)
# Primitive count:  (G) = 25  (R) = 32
# Wrapper size: (G) = 0  (R) = 0
# Periphery size: (G) = 0  (R) = 0
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk (REP)  =   (R) clk (REP) (by name)
# IN (G) rst_n (REP)  =   (R) rst_n (REP) (by name)
# IN (G) serial_in (REP)  =   (R) serial_in (REP) (by name)
# RESOLVED Constraints
# OUT (G) p_o[7] (REP)  =   (R) p_o[7] (REP) (by name)
# OUT (G) p_o[6] (REP)  =   (R) p_o[6] (REP) (by name)
# OUT (G) p_o[5] (REP)  =   (R) p_o[5] (REP) (by name)
# OUT (G) p_o[4] (REP)  =   (R) p_o[4] (REP) (by name)
# OUT (G) p_o[3] (REP)  =   (R) p_o[3] (REP) (by name)
# OUT (G) p_o[2] (REP)  =   (R) p_o[2] (REP) (by name)
# OUT (G) p_o[1] (REP)  =   (R) p_o[1] (REP) (by name)
# OUT (G) p_o[0] (REP)  =   (R) p_o[0] (REP) (by name)
set_root_module serial_to_parallel -Golden
set_root_module serial_to_parallel -Revised
set_module_property -instance / -Golden
set_module_property -instance / -Revised
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -flowgraph -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
usage
report_hier_compare_result
report_hier_compare_result -Nonequivalent
report_hier_compare_result -Abort
report_hier_compare_result -Uncompared
# _END_OF_LEC_HIERARCHICAL_DOFILE_
