/*
###############################################################
#  Generated by:      Cadence Innovus 23.31-s109_1
#  OS:                Linux x86_64(Host ID ei-vm-018.othr.de)
#  Generated on:      Sat Sep 27 22:59:42 2025
#  Design:            Main
#  Command:           saveNetlist pnr_outputs/post_layout_main.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Aug 10 2025 17:29:46 CEST (Aug 10 2025 15:29:46 UTC)
// Verification Directory fv/Main 
module Main (
	\weight[0] , 
	\weight[1] , 
	\weight[2] , 
	\weight[3] , 
	\weight[4] , 
	\weight[5] , 
	\activation[0] , 
	\activation[1] , 
	\activation[2] , 
	\activation[3] , 
	\activation[4] , 
	\activation[5] , 
	start, 
	clk, 
	rst, 
	en, 
	z_p, 
	z_n, 
	scan_en, 
	scan_in, 
	scan_out);
   input [7:0] \weight[0] ;
   input [7:0] \weight[1] ;
   input [7:0] \weight[2] ;
   input [7:0] \weight[3] ;
   input [7:0] \weight[4] ;
   input [7:0] \weight[5] ;
   input [7:0] \activation[0] ;
   input [7:0] \activation[1] ;
   input [7:0] \activation[2] ;
   input [7:0] \activation[3] ;
   input [7:0] \activation[4] ;
   input [7:0] \activation[5] ;
   input start;
   input clk;
   input rst;
   output en;
   output z_p;
   output z_n;
   input scan_en;
   input scan_in;
   output scan_out;

   // Internal wires
   wire FE_OCPN256_n_218;
   wire FE_OFN255_n_146;
   wire FE_RN_155_0;
   wire FE_RN_154_0;
   wire FE_OCPN253_result_4__1;
   wire FE_RN_152_0;
   wire FE_RN_151_0;
   wire FE_RN_150_0;
   wire FE_RN_148_0;
   wire FE_RN_147_0;
   wire FE_RN_146_0;
   wire FE_RN_144_0;
   wire FE_RN_143_0;
   wire FE_RN_142_0;
   wire FE_RN_141_0;
   wire FE_RN_140_0;
   wire FE_RN_139_0;
   wire FE_RN_138_0;
   wire FE_RN_137_0;
   wire FE_RN_136_0;
   wire FE_RN_135_0;
   wire FE_RN_134_0;
   wire FE_RN_133_0;
   wire FE_RN_132_0;
   wire FE_RN_131_0;
   wire FE_RN_128_0;
   wire FE_RN_126_0;
   wire FE_RN_125_0;
   wire FE_RN_124_0;
   wire FE_RN_122_0;
   wire FE_RN_121_0;
   wire FE_RN_120_0;
   wire FE_RN_119_0;
   wire FE_RN_118_0;
   wire FE_RN_117_0;
   wire FE_RN_116_0;
   wire FE_RN_115_0;
   wire FE_RN_114_0;
   wire FE_RN_112_0;
   wire FE_RN_111_0;
   wire FE_RN_110_0;
   wire FE_RN_109_0;
   wire FE_RN_108_0;
   wire FE_RN_107_0;
   wire FE_RN_105_0;
   wire FE_RN_104_0;
   wire FE_RN_103_0;
   wire FE_RN_102_0;
   wire FE_RN_101_0;
   wire FE_RN_100_0;
   wire FE_RN_99_0;
   wire FE_RN_98_0;
   wire FE_RN_96_0;
   wire FE_RN_95_0;
   wire FE_RN_94_0;
   wire FE_RN_91_0;
   wire FE_RN_90_0;
   wire FE_RN_88_0;
   wire FE_RN_87_0;
   wire FE_RN_86_0;
   wire FE_RN_84_0;
   wire FE_RN_83_0;
   wire FE_RN_82_0;
   wire FE_RN_81_0;
   wire FE_RN_80_0;
   wire FE_RN_79_0;
   wire FE_RN_78_0;
   wire FE_RN_77_0;
   wire FE_RN_76_0;
   wire FE_RN_75_0;
   wire FE_RN_74_0;
   wire FE_RN_72_0;
   wire FE_RN_70_0;
   wire FE_RN_69_0;
   wire FE_RN_68_0;
   wire FE_RN_67_0;
   wire FE_RN_66_0;
   wire FE_RN_65_0;
   wire FE_RN_64_0;
   wire FE_RN_63_0;
   wire FE_RN_62_0;
   wire FE_RN_61_0;
   wire FE_RN_60_0;
   wire FE_RN_59_0;
   wire FE_RN_58_0;
   wire FE_RN_57_0;
   wire FE_RN_56_0;
   wire FE_RN_55_0;
   wire FE_RN_54_0;
   wire FE_RN_53_0;
   wire FE_RN_52_0;
   wire FE_RN_51_0;
   wire FE_RN_50_0;
   wire FE_RN_49_0;
   wire FE_RN_48_0;
   wire FE_RN_47_0;
   wire FE_RN_46_0;
   wire FE_RN_45_0;
   wire FE_RN_44_0;
   wire FE_RN_43_0;
   wire FE_RN_42_0;
   wire FE_RN_41_0;
   wire FE_RN_40_0;
   wire FE_RN_38_0;
   wire FE_RN_37_0;
   wire FE_RN_34_0;
   wire FE_RN_33_0;
   wire FE_RN_32_0;
   wire FE_RN_31_0;
   wire FE_RN_29_0;
   wire FE_RN_24_0;
   wire FE_RN_23_0;
   wire FE_RN_20_0;
   wire FE_RN_19_0;
   wire FE_RN_18_0;
   wire FE_RN_17_0;
   wire FE_RN_16_0;
   wire FE_RN_15_0;
   wire FE_RN_14_0;
   wire FE_RN_13_0;
   wire FE_RN_12_0;
   wire FE_RN_11_0;
   wire FE_RN_10_0;
   wire FE_RN_8_0;
   wire FE_RN_7_0;
   wire FE_RN_6_0;
   wire FE_RN_5_0;
   wire FE_RN_4_0;
   wire FE_RN_1_0;
   wire FE_OFN19_n_146;
   wire FE_OFN18_n_146;
   wire FE_OFN17_n_143;
   wire FE_OFN16_n_143;
   wire FE_OFN15_n_139;
   wire FE_OFN14_n_139;
   wire FE_OFN13_n_145;
   wire FE_OFN12_n_140;
   wire FE_OFN11_n_140;
   wire FE_OFN10_n_138;
   wire FE_OFN9_n_251;
   wire FE_OFN8_n_251;
   wire FE_OFN7_n_125;
   wire FE_OFN6_n_123;
   wire FE_OFN5_n_83;
   wire FE_OFN4_n_82;
   wire FE_RN_1;
   wire FE_OFN2_scan_en;
   wire FE_OFN0_en;
   wire [10:0] AT6_sum_out;
   wire [7:0] \result[4] ;
   wire [7:0] \result[5] ;
   wire [7:0] \result[2] ;
   wire [7:0] \result[3] ;
   wire [7:0] \result[0] ;
   wire [7:0] \result[1] ;
   wire [3:0] A6M_cycle_counter;
   wire [7:0] \A6M_activation_reg[4] ;
   wire [7:0] \A6M_activation_reg[1] ;
   wire [7:0] \A6M_activation_reg[5] ;
   wire [7:0] \A6M_activation_reg[2] ;
   wire [7:0] \A6M_activation_reg[0] ;
   wire [7:0] \A6M_activation_reg[3] ;
   wire OGF_R0;
   wire OGF_R1;
   wire OGF_R2;
   wire n_0;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_253;

   assign scan_out = FE_RN_1 ;

   CLKXOR2X1 FE_RC_226_0 (.Y(n_134),
	.A(n_23),
	.B(FE_RN_29_0));
   CLKBUFX2 FE_OCPC29_n_218 (.Y(FE_OCPN256_n_218),
	.A(n_218));
   OAI21X2 FE_RC_225_0 (.Y(FE_RN_131_0),
	.A0(n_223),
	.A1(n_236),
	.B0(n_233));
   CLKXOR2X1 FE_RC_222_0 (.Y(n_242),
	.A(n_233),
	.B(FE_RN_126_0));
   CLKXOR2X1 FE_RC_221_0 (.Y(n_234),
	.A(n_228),
	.B(FE_RN_148_0));
   BUFX2 FE_OFC28_n_146 (.Y(FE_OFN255_n_146),
	.A(n_146));
   NAND2BX4 FE_RC_220_0 (.Y(FE_RN_155_0),
	.AN(FE_RN_23_0),
	.B(n_222));
   OAI21X4 FE_RC_219_0 (.Y(n_227),
	.A0(n_222),
	.A1(FE_RN_24_0),
	.B0(FE_RN_155_0));
   CLKINVX20 FE_RC_218_0 (.Y(z_p),
	.A(FE_RN_154_0));
   NOR2X4 FE_RC_217_0 (.Y(FE_RN_154_0),
	.A(FE_RN_121_0),
	.B(FE_RN_120_0));
   CLKBUFX2 FE_OCPC26_result_4__1 (.Y(FE_OCPN253_result_4__1),
	.A(\result[4] [1]));
   MXI2X1 FE_RC_216_0 (.Y(FE_RN_38_0),
	.A(FE_RN_37_0),
	.B(\result[4] [1]),
	.S0(\result[5] [1]));
   NAND2BX1 FE_RC_212_0 (.Y(FE_RN_146_0),
	.AN(n_232),
	.B(FE_OCPN256_n_218));
   INVX1 FE_RC_211_0 (.Y(FE_RN_147_0),
	.A(n_232));
   OAI21X1 FE_RC_210_0 (.Y(FE_RN_148_0),
	.A0(FE_OCPN256_n_218),
	.A1(FE_RN_147_0),
	.B0(FE_RN_146_0));
   NAND2X1 FE_RC_207_0 (.Y(FE_RN_150_0),
	.A(n_218),
	.B(n_232));
   NOR2X2 FE_RC_206_0 (.Y(FE_RN_151_0),
	.A(n_232),
	.B(n_218));
   INVX1 FE_RC_205_0 (.Y(FE_RN_152_0),
	.A(n_228));
   OAI21X2 FE_RC_204_0 (.Y(n_233),
	.A0(FE_RN_152_0),
	.A1(FE_RN_151_0),
	.B0(FE_RN_150_0));
   NOR2X2 FE_RC_203_0 (.Y(FE_RN_144_0),
	.A(FE_RN_54_0),
	.B(n_202));
   NAND2BX4 FE_RC_202_0 (.Y(n_213),
	.AN(FE_RN_144_0),
	.B(FE_RN_52_0));
   NAND2X1 FE_RC_201_0 (.Y(FE_RN_132_0),
	.A(\result[0] [1]),
	.B(\result[1] [1]));
   INVX1 FE_RC_200_0 (.Y(FE_RN_133_0),
	.A(\result[1] [1]));
   NAND2BX1 FE_RC_199_0 (.Y(FE_RN_134_0),
	.AN(\result[0] [1]),
	.B(FE_RN_133_0));
   NAND2X2 FE_RC_198_0 (.Y(FE_RN_135_0),
	.A(n_17),
	.B(FE_RN_134_0));
   NAND2X2 FE_RC_197_0 (.Y(n_95),
	.A(FE_RN_132_0),
	.B(FE_RN_135_0));
   INVX1 FE_RC_196_0 (.Y(FE_RN_136_0),
	.A(n_17));
   NAND2X1 FE_RC_195_0 (.Y(FE_RN_137_0),
	.A(FE_RN_136_0),
	.B(FE_RN_141_0));
   INVX1 FE_RC_194_0 (.Y(FE_RN_138_0),
	.A(\result[1] [1]));
   NAND2X2 FE_RC_193_0 (.Y(FE_RN_139_0),
	.A(\result[0] [1]),
	.B(FE_RN_138_0));
   NAND2BX1 FE_RC_192_0 (.Y(FE_RN_140_0),
	.AN(\result[0] [1]),
	.B(\result[1] [1]));
   NAND2X2 FE_RC_191_0 (.Y(FE_RN_141_0),
	.A(FE_RN_139_0),
	.B(FE_RN_140_0));
   INVX1 FE_RC_190_0 (.Y(FE_RN_142_0),
	.A(FE_RN_141_0));
   NAND2X2 FE_RC_189_0 (.Y(FE_RN_143_0),
	.A(n_17),
	.B(FE_RN_142_0));
   NAND2X2 FE_RC_188_0 (.Y(n_96),
	.A(FE_RN_137_0),
	.B(FE_RN_143_0));
   NAND2BX1 FE_RC_186_0 (.Y(FE_RN_124_0),
	.AN(n_236),
	.B(n_223));
   INVX1 FE_RC_185_0 (.Y(FE_RN_125_0),
	.A(n_236));
   OAI21X1 FE_RC_184_0 (.Y(FE_RN_126_0),
	.A0(n_223),
	.A1(FE_RN_125_0),
	.B0(FE_RN_124_0));
   NAND2X1 FE_RC_181_0 (.Y(FE_RN_128_0),
	.A(n_236),
	.B(n_223));
   NAND2X2 FE_RC_177_0 (.Y(n_241),
	.A(FE_RN_128_0),
	.B(FE_RN_131_0));
   CLKXOR2X1 FE_RC_176_0 (.Y(FE_RN_23_0),
	.A(n_219),
	.B(n_212));
   CLKXOR2X1 FE_RC_175_0 (.Y(n_209),
	.A(FE_RN_72_0),
	.B(n_158));
   XOR2XL FE_RC_174_0 (.Y(n_132),
	.A(n_22),
	.B(FE_RN_38_0));
   CLKXOR2X1 FE_RC_173_0 (.Y(FE_RN_29_0),
	.A(\result[3] [1]),
	.B(\result[2] [1]));
   CLKXOR2X1 FE_RC_172_0 (.Y(n_223),
	.A(FE_RN_88_0),
	.B(n_217));
   MXI2X1 FE_RC_171_0 (.Y(n_244),
	.A(FE_RN_114_0),
	.B(n_241),
	.S0(FE_RN_96_0));
   CLKAND2X2 FE_RC_170_0 (.Y(n_23),
	.A(\result[3] [0]),
	.B(\result[2] [0]));
   INVX1 FE_RC_169_0 (.Y(FE_RN_122_0),
	.A(n_55));
   NOR2X2 FE_RC_168_0 (.Y(n_56),
	.A(FE_RN_122_0),
	.B(n_54));
   AND2X1 FE_RC_167_0 (.Y(FE_RN_121_0),
	.A(n_247),
	.B(OGF_R2));
   AND2X1 FE_RC_164_0 (.Y(FE_RN_120_0),
	.A(FE_RN_115_0),
	.B(n_249));
   NAND2BX1 FE_RC_162_0 (.Y(FE_RN_119_0),
	.AN(FE_RN_34_0),
	.B(FE_RN_32_0));
   OR2X1 FE_RC_161_0 (.Y(FE_RN_116_0),
	.A(\result[3] [2]),
	.B(\result[2] [2]));
   ADDHX1 FE_RC_160_0 (.CO(FE_RN_118_0),
	.S(FE_RN_117_0),
	.A(\result[3] [2]),
	.B(\result[2] [2]));
   AO21X1 FE_RC_159_0 (.Y(n_160),
	.A0(FE_RN_116_0),
	.A1(FE_RN_119_0),
	.B0(FE_RN_118_0));
   CLKXOR2X1 FE_RC_158_0 (.Y(n_161),
	.A(FE_RN_117_0),
	.B(FE_RN_119_0));
   INVX1 FE_RC_157_0 (.Y(FE_RN_115_0),
	.A(FE_RN_1_0));
   CLKAND2X2 FE_RC_155_0 (.Y(n_22),
	.A(\result[4] [0]),
	.B(\result[5] [0]));
   CLKXOR2X1 FE_RC_154_0 (.Y(n_119),
	.A(\result[4] [0]),
	.B(\result[5] [0]));
   NAND2BX2 FE_RC_153_0 (.Y(FE_RN_42_0),
	.AN(FE_RN_41_0),
	.B(n_22));
   INVX2 FE_RC_152_0 (.Y(FE_RN_114_0),
	.A(n_241));
   OAI21X4 FE_RC_151_0 (.Y(n_243),
	.A0(FE_RN_91_0),
	.A1(FE_RN_114_0),
	.B0(FE_RN_90_0));
   XOR2XL FE_RC_149_0 (.Y(n_55),
	.A(\result[2] [0]),
	.B(\result[3] [0]));
   MXI2XL FE_RC_147_0 (.Y(n_253),
	.A(FE_RN_7_0),
	.B(FE_RN_6_0),
	.S0(n_249));
   INVX1 FE_RC_146_0 (.Y(FE_RN_107_0),
	.A(FE_RN_67_0));
   INVX1 FE_RC_145_0 (.Y(FE_RN_111_0),
	.A(n_160));
   NOR2X1 FE_RC_144_0 (.Y(FE_RN_112_0),
	.A(\result[3] [3]),
	.B(\result[2] [3]));
   NAND2X1 FE_RC_143_0 (.Y(FE_RN_110_0),
	.A(\result[3] [3]),
	.B(\result[2] [3]));
   CLKXOR2X1 FE_RC_142_0 (.Y(FE_RN_108_0),
	.A(\result[3] [3]),
	.B(\result[2] [3]));
   OAI211X1 FE_RC_141_0 (.Y(FE_RN_109_0),
	.A0(FE_RN_112_0),
	.A1(FE_RN_111_0),
	.B0(FE_RN_110_0),
	.C0(FE_RN_107_0));
   OAI21X2 FE_RC_140_0 (.Y(n_206),
	.A0(FE_RN_112_0),
	.A1(FE_RN_111_0),
	.B0(FE_RN_110_0));
   CLKXOR2X1 FE_RC_139_0 (.Y(n_207),
	.A(FE_RN_108_0),
	.B(n_160));
   NAND2X2 FE_RC_138_0 (.Y(n_220),
	.A(FE_RN_65_0),
	.B(FE_RN_109_0));
   CLKXOR2X1 FE_RC_137_0 (.Y(n_246),
	.A(OGF_R0),
	.B(n_244));
   CLKAND2X2 FE_RC_136_0 (.Y(n_245),
	.A(OGF_R0),
	.B(n_244));
   NAND2X1 FE_RC_135_0 (.Y(FE_RN_98_0),
	.A(\result[0] [2]),
	.B(\result[1] [2]));
   NOR2X1 FE_RC_134_0 (.Y(FE_RN_99_0),
	.A(\result[0] [2]),
	.B(\result[1] [2]));
   NAND2BX1 FE_RC_133_0 (.Y(FE_RN_100_0),
	.AN(FE_RN_99_0),
	.B(n_95));
   NAND2X2 FE_RC_132_0 (.Y(n_150),
	.A(FE_RN_98_0),
	.B(FE_RN_100_0));
   INVX1 FE_RC_131_0 (.Y(FE_RN_101_0),
	.A(FE_RN_105_0));
   NAND2X1 FE_RC_130_0 (.Y(FE_RN_102_0),
	.A(n_95),
	.B(FE_RN_101_0));
   NAND2BX1 FE_RC_129_0 (.Y(FE_RN_103_0),
	.AN(\result[1] [2]),
	.B(\result[0] [2]));
   NAND2BX1 FE_RC_128_0 (.Y(FE_RN_104_0),
	.AN(\result[0] [2]),
	.B(\result[1] [2]));
   NAND2X1 FE_RC_127_0 (.Y(FE_RN_105_0),
	.A(FE_RN_103_0),
	.B(FE_RN_104_0));
   OAI21X1 FE_RC_125_0 (.Y(n_151),
	.A0(n_95),
	.A1(FE_RN_101_0),
	.B0(FE_RN_102_0));
   NAND2X1 FE_RC_124_0 (.Y(FE_RN_90_0),
	.A(n_227),
	.B(n_240));
   NOR2X1 FE_RC_123_0 (.Y(FE_RN_91_0),
	.A(n_227),
	.B(n_240));
   NAND2BX1 FE_RC_119_0 (.Y(FE_RN_94_0),
	.AN(n_240),
	.B(n_227));
   INVX1 FE_RC_118_0 (.Y(FE_RN_95_0),
	.A(n_240));
   OAI21X1 FE_RC_117_0 (.Y(FE_RN_96_0),
	.A0(n_227),
	.A1(FE_RN_95_0),
	.B0(FE_RN_94_0));
   NAND2X1 FE_RC_114_0 (.Y(FE_RN_82_0),
	.A(n_220),
	.B(n_213));
   NOR2X1 FE_RC_113_0 (.Y(FE_RN_83_0),
	.A(n_220),
	.B(n_213));
   NAND2BX2 FE_RC_112_0 (.Y(FE_RN_84_0),
	.AN(FE_RN_83_0),
	.B(n_217));
   NAND2X4 FE_RC_111_0 (.Y(n_222),
	.A(FE_RN_82_0),
	.B(FE_RN_84_0));
   NAND2BX1 FE_RC_109_0 (.Y(FE_RN_86_0),
	.AN(n_213),
	.B(n_220));
   INVX1 FE_RC_108_0 (.Y(FE_RN_87_0),
	.A(n_213));
   OAI21X1 FE_RC_107_0 (.Y(FE_RN_88_0),
	.A0(n_220),
	.A1(FE_RN_87_0),
	.B0(FE_RN_86_0));
   NAND2X1 FE_RC_104_0 (.Y(FE_RN_74_0),
	.A(\result[5] [2]),
	.B(\result[4] [2]));
   OR2X1 FE_RC_103_0 (.Y(FE_RN_75_0),
	.A(\result[5] [2]),
	.B(\result[4] [2]));
   NAND2X1 FE_RC_102_0 (.Y(FE_RN_76_0),
	.A(FE_RN_75_0),
	.B(n_131));
   NAND2X1 FE_RC_101_0 (.Y(n_158),
	.A(FE_RN_74_0),
	.B(FE_RN_76_0));
   NAND2BX1 FE_RC_100_0 (.Y(FE_RN_77_0),
	.AN(n_131),
	.B(FE_RN_80_0));
   NAND2BX1 FE_RC_99_0 (.Y(FE_RN_78_0),
	.AN(\result[4] [2]),
	.B(\result[5] [2]));
   NAND2BX1 FE_RC_98_0 (.Y(FE_RN_79_0),
	.AN(\result[5] [2]),
	.B(\result[4] [2]));
   NAND2X1 FE_RC_97_0 (.Y(FE_RN_80_0),
	.A(FE_RN_78_0),
	.B(FE_RN_79_0));
   INVX1 FE_RC_96_0 (.Y(FE_RN_81_0),
	.A(n_131));
   OAI21X2 FE_RC_95_0 (.Y(n_159),
	.A0(FE_RN_81_0),
	.A1(FE_RN_80_0),
	.B0(FE_RN_77_0));
   NAND2X1 FE_RC_94_0 (.Y(FE_RN_68_0),
	.A(\result[5] [3]),
	.B(\result[4] [3]));
   OR2X1 FE_RC_93_0 (.Y(FE_RN_69_0),
	.A(\result[5] [3]),
	.B(\result[4] [3]));
   NAND2X1 FE_RC_92_0 (.Y(FE_RN_70_0),
	.A(FE_RN_69_0),
	.B(n_158));
   NAND2X1 FE_RC_91_0 (.Y(n_208),
	.A(FE_RN_68_0),
	.B(FE_RN_70_0));
   CLKXOR2X1 FE_RC_89_0 (.Y(FE_RN_72_0),
	.A(\result[5] [3]),
	.B(\result[4] [3]));
   NAND2X1 FE_RC_86_0 (.Y(FE_RN_62_0),
	.A(\result[2] [4]),
	.B(\result[3] [4]));
   OR2X1 FE_RC_85_0 (.Y(FE_RN_63_0),
	.A(\result[2] [4]),
	.B(\result[3] [4]));
   NAND2X1 FE_RC_84_0 (.Y(FE_RN_64_0),
	.A(FE_RN_63_0),
	.B(n_206));
   NAND2X1 FE_RC_83_0 (.Y(n_219),
	.A(FE_RN_62_0),
	.B(FE_RN_64_0));
   NAND2BX1 FE_RC_82_0 (.Y(FE_RN_65_0),
	.AN(FE_RN_66_0),
	.B(n_206));
   CLKXOR2X1 FE_RC_81_0 (.Y(FE_RN_66_0),
	.A(\result[2] [4]),
	.B(\result[3] [4]));
   INVX1 FE_RC_80_0 (.Y(FE_RN_67_0),
	.A(FE_RN_66_0));
   NAND2X1 FE_RC_78_0 (.Y(FE_RN_56_0),
	.A(\result[0] [3]),
	.B(\result[1] [3]));
   OR2X1 FE_RC_77_0 (.Y(FE_RN_57_0),
	.A(\result[0] [3]),
	.B(\result[1] [3]));
   NAND2X2 FE_RC_76_0 (.Y(FE_RN_58_0),
	.A(FE_RN_57_0),
	.B(n_150));
   NAND2X2 FE_RC_75_0 (.Y(n_202),
	.A(FE_RN_56_0),
	.B(FE_RN_58_0));
   NAND2BX1 FE_RC_74_0 (.Y(FE_RN_59_0),
	.AN(FE_RN_60_0),
	.B(n_150));
   CLKXOR2X1 FE_RC_73_0 (.Y(FE_RN_60_0),
	.A(\result[0] [3]),
	.B(\result[1] [3]));
   INVX1 FE_RC_72_0 (.Y(FE_RN_61_0),
	.A(FE_RN_60_0));
   OAI21X1 FE_RC_71_0 (.Y(n_203),
	.A0(n_150),
	.A1(FE_RN_61_0),
	.B0(FE_RN_59_0));
   NAND2X1 FE_RC_70_0 (.Y(FE_RN_55_0),
	.A(n_238),
	.B(n_237));
   NAND2X2 FE_RC_69_0 (.Y(n_240),
	.A(FE_RN_55_0),
	.B(n_239));
   NAND2X1 FE_RC_68_0 (.Y(FE_RN_49_0),
	.A(\result[0] [4]),
	.B(\result[1] [4]));
   OR2X1 FE_RC_67_0 (.Y(FE_RN_50_0),
	.A(\result[0] [4]),
	.B(\result[1] [4]));
   NAND2X1 FE_RC_66_0 (.Y(FE_RN_51_0),
	.A(FE_RN_50_0),
	.B(n_202));
   NAND2X1 FE_RC_65_0 (.Y(n_212),
	.A(FE_RN_49_0),
	.B(FE_RN_51_0));
   NAND2BX1 FE_RC_64_0 (.Y(FE_RN_52_0),
	.AN(FE_RN_53_0),
	.B(n_202));
   CLKXOR2X1 FE_RC_63_0 (.Y(FE_RN_53_0),
	.A(\result[0] [4]),
	.B(\result[1] [4]));
   INVX1 FE_RC_62_0 (.Y(FE_RN_54_0),
	.A(FE_RN_53_0));
   NAND2X1 FE_RC_60_0 (.Y(FE_RN_43_0),
	.A(\result[4] [4]),
	.B(\result[5] [4]));
   OR2X1 FE_RC_59_0 (.Y(FE_RN_44_0),
	.A(\result[4] [4]),
	.B(\result[5] [4]));
   NAND2X1 FE_RC_58_0 (.Y(FE_RN_45_0),
	.A(FE_RN_44_0),
	.B(n_208));
   NAND2X1 FE_RC_57_0 (.Y(n_238),
	.A(FE_RN_43_0),
	.B(FE_RN_45_0));
   NAND2BX1 FE_RC_56_0 (.Y(FE_RN_46_0),
	.AN(FE_RN_47_0),
	.B(n_208));
   CLKXOR2X1 FE_RC_55_0 (.Y(FE_RN_47_0),
	.A(\result[4] [4]),
	.B(\result[5] [4]));
   INVX1 FE_RC_54_0 (.Y(FE_RN_48_0),
	.A(FE_RN_47_0));
   OAI21X1 FE_RC_53_0 (.Y(n_221),
	.A0(n_208),
	.A1(FE_RN_48_0),
	.B0(FE_RN_46_0));
   INVX1 FE_RC_50_0 (.Y(FE_RN_37_0),
	.A(\result[4] [1]));
   NAND2X1 FE_RC_46_0 (.Y(FE_RN_40_0),
	.A(\result[5] [1]),
	.B(\result[4] [1]));
   NOR2X1 FE_RC_45_0 (.Y(FE_RN_41_0),
	.A(\result[4] [1]),
	.B(\result[5] [1]));
   NAND2X2 FE_RC_43_0 (.Y(n_131),
	.A(FE_RN_40_0),
	.B(FE_RN_42_0));
   NOR2X1 FE_RC_35_0 (.Y(FE_RN_31_0),
	.A(\result[3] [1]),
	.B(\result[2] [1]));
   NAND2BX1 FE_RC_34_0 (.Y(FE_RN_32_0),
	.AN(FE_RN_31_0),
	.B(n_23));
   INVX1 FE_RC_33_0 (.Y(FE_RN_33_0),
	.A(\result[2] [1]));
   NOR2BX1 FE_RC_32_0 (.Y(FE_RN_34_0),
	.AN(\result[3] [1]),
	.B(FE_RN_33_0));
   INVX1 FE_RC_30_0 (.Y(FE_RN_17_0),
	.A(n_222));
   NOR2X1 FE_RC_29_0 (.Y(FE_RN_18_0),
	.A(n_219),
	.B(n_212));
   INVX1 FE_RC_28_0 (.Y(FE_RN_19_0),
	.A(n_212));
   INVX1 FE_RC_27_0 (.Y(FE_RN_20_0),
	.A(n_219));
   OAI22X2 FE_RC_26_0 (.Y(n_226),
	.A0(FE_RN_20_0),
	.A1(FE_RN_19_0),
	.B0(FE_RN_18_0),
	.B1(FE_RN_17_0));
   INVX1 FE_RC_22_0 (.Y(FE_RN_24_0),
	.A(FE_RN_23_0));
   NAND2X1 FE_RC_20_0 (.Y(FE_RN_8_0),
	.A(n_226),
	.B(n_239));
   NAND2BX1 FE_RC_18_0 (.Y(FE_RN_10_0),
	.AN(n_226),
	.B(FE_RN_14_0));
   NAND2X1 FE_RC_17_0 (.Y(FE_RN_11_0),
	.A(FE_RN_10_0),
	.B(n_243));
   NAND2X2 FE_RC_16_0 (.Y(n_247),
	.A(FE_RN_8_0),
	.B(FE_RN_11_0));
   NAND2BX2 FE_RC_15_0 (.Y(FE_RN_12_0),
	.AN(FE_RN_15_0),
	.B(n_243));
   NAND2BX1 FE_RC_14_0 (.Y(FE_RN_13_0),
	.AN(n_239),
	.B(n_226));
   INVX1 FE_RC_13_0 (.Y(FE_RN_14_0),
	.A(n_239));
   OAI21X1 FE_RC_12_0 (.Y(FE_RN_15_0),
	.A0(n_226),
	.A1(FE_RN_14_0),
	.B0(FE_RN_13_0));
   INVX1 FE_RC_11_0 (.Y(FE_RN_16_0),
	.A(FE_RN_15_0));
   OAI21X2 FE_RC_10_0 (.Y(n_248),
	.A0(n_243),
	.A1(FE_RN_16_0),
	.B0(FE_RN_12_0));
   NOR2BX1 FE_RC_8_0 (.Y(FE_RN_1_0),
	.AN(FE_RN_5_0),
	.B(n_247));
   NAND2BX1 FE_RC_4_0 (.Y(FE_RN_4_0),
	.AN(OGF_R2),
	.B(n_247));
   INVX1 FE_RC_3_0 (.Y(FE_RN_5_0),
	.A(OGF_R2));
   OAI21X1 FE_RC_2_0 (.Y(FE_RN_6_0),
	.A0(n_247),
	.A1(FE_RN_5_0),
	.B0(FE_RN_4_0));
   INVX1 FE_RC_1_0 (.Y(FE_RN_7_0),
	.A(FE_RN_6_0));
   INVXL FE_OFC19_n_146 (.Y(FE_OFN19_n_146),
	.A(FE_OFN18_n_146));
   INVXL FE_OFC18_n_146 (.Y(FE_OFN18_n_146),
	.A(FE_OFN255_n_146));
   INVXL FE_OFC17_n_143 (.Y(FE_OFN17_n_143),
	.A(FE_OFN16_n_143));
   INVXL FE_OFC16_n_143 (.Y(FE_OFN16_n_143),
	.A(n_143));
   INVXL FE_OFC15_n_139 (.Y(FE_OFN15_n_139),
	.A(FE_OFN14_n_139));
   INVXL FE_OFC14_n_139 (.Y(FE_OFN14_n_139),
	.A(n_139));
   BUFX2 FE_OFC13_n_145 (.Y(FE_OFN13_n_145),
	.A(n_145));
   INVXL FE_OFC12_n_140 (.Y(FE_OFN12_n_140),
	.A(FE_OFN11_n_140));
   INVXL FE_OFC11_n_140 (.Y(FE_OFN11_n_140),
	.A(n_140));
   BUFX2 FE_OFC10_n_138 (.Y(FE_OFN10_n_138),
	.A(n_138));
   BUFX3 FE_OFC9_n_251 (.Y(FE_OFN9_n_251),
	.A(n_251));
   BUFX3 FE_OFC8_n_251 (.Y(FE_OFN8_n_251),
	.A(n_251));
   BUFX2 FE_OFC7_n_125 (.Y(FE_OFN7_n_125),
	.A(n_125));
   BUFX2 FE_OFC6_n_123 (.Y(FE_OFN6_n_123),
	.A(n_123));
   BUFX2 FE_OFC5_n_83 (.Y(FE_OFN5_n_83),
	.A(n_83));
   BUFX2 FE_OFC4_n_82 (.Y(FE_OFN4_n_82),
	.A(n_82));
   CLKBUFX8 FE_OFC3_scan_out (.Y(z_n),
	.A(scan_out));
   BUFX3 FE_OFC2_scan_en (.Y(FE_OFN2_scan_en),
	.A(scan_en));
   CLKBUFX8 FE_OFC0_en (.Y(en),
	.A(FE_OFN0_en));
   SDFFRHQX2 OGF_R3_reg (.Q(FE_RN_1),
	.D(n_253),
	.SE(scan_en),
	.SI(OGF_R0),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 OGF_R2_reg (.Q(OGF_R2),
	.D(n_250),
	.SE(FE_OFN2_scan_en),
	.SI(A6M_cycle_counter[3]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   ADDFHX1 g6853__5107 (.CO(n_249),
	.S(n_250),
	.A(OGF_R1),
	.B(n_248),
	.CI(n_245));
   SDFFRHQX1 OGF_R1_reg (.Q(OGF_R1),
	.D(n_246),
	.SE(FE_OFN2_scan_en),
	.SI(FE_OFN0_en),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 OGF_R0_reg (.Q(OGF_R0),
	.D(n_242),
	.SE(FE_OFN2_scan_en),
	.SI(AT6_sum_out[0]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   OR2X4 g6861__3680 (.Y(n_239),
	.A(n_238),
	.B(n_237));
   ADDFHXL g6862__1617 (.CO(n_237),
	.S(n_236),
	.A(AT6_sum_out[3]),
	.B(n_221),
	.CI(n_231));
   SDFFQX1 \AT6_sum_out_reg[3]  (.Q(AT6_sum_out[3]),
	.D(n_235),
	.SE(scan_en),
	.SI(\result[4] [4]),
	.CK(clk));
   NOR2BX1 g6864__2802 (.Y(n_235),
	.AN(n_234),
	.B(rst));
   ADDFX1 g6866__5122 (.CO(n_231),
	.S(n_232),
	.A(AT6_sum_out[2]),
	.B(n_209),
	.CI(n_224));
   SDFFQX1 \AT6_sum_out_reg[2]  (.Q(AT6_sum_out[2]),
	.D(n_230),
	.SE(FE_OFN2_scan_en),
	.SI(\result[5] [4]),
	.CK(clk));
   NOR2BX1 g6868__8246 (.Y(n_230),
	.AN(n_229),
	.B(rst));
   ADDFX1 g6869__7098 (.CO(n_228),
	.S(n_229),
	.A(n_225),
	.B(n_211),
	.CI(n_214));
   ADDFXL g6870__1881 (.CO(n_224),
	.S(n_225),
	.A(AT6_sum_out[1]),
	.B(n_204),
	.CI(n_159));
   SDFFQX1 \AT6_sum_out_reg[1]  (.Q(AT6_sum_out[1]),
	.D(n_216),
	.SE(FE_OFN2_scan_en),
	.SI(AT6_sum_out[2]),
	.CK(clk));
   ADDFHX1 g6876__6161 (.CO(n_217),
	.S(n_218),
	.A(n_203),
	.B(n_207),
	.CI(n_210));
   NOR2BX1 g6874__9315 (.Y(n_216),
	.AN(n_215),
	.B(rst));
   ADDFX1 g6875__9945 (.CO(n_214),
	.S(n_215),
	.A(n_120),
	.B(n_205),
	.CI(n_163));
   ADDFHXL g6880__2346 (.CO(n_210),
	.S(n_211),
	.A(n_151),
	.B(n_161),
	.CI(n_162));
   SDFFRHQX1 \A6M_result_reg[2][0]  (.Q(\result[2] [0]),
	.D(n_197),
	.SE(scan_en),
	.SI(\result[2] [1]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[1][0]  (.Q(\result[1] [0]),
	.D(n_198),
	.SE(scan_en),
	.SI(\result[0] [0]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[2][3]  (.Q(\result[2] [3]),
	.D(n_201),
	.SE(FE_OFN2_scan_en),
	.SI(\result[2] [2]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[0][0]  (.Q(\result[0] [0]),
	.D(n_200),
	.SE(scan_en),
	.SI(\result[0] [3]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX4 \A6M_result_reg[5][0]  (.Q(\result[5] [0]),
	.D(n_167),
	.SE(scan_en),
	.SI(\result[4] [3]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[3][4]  (.Q(\result[3] [4]),
	.D(n_173),
	.SE(FE_OFN2_scan_en),
	.SI(\result[3] [3]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[4][2]  (.Q(\result[4] [2]),
	.D(n_182),
	.SE(FE_OFN2_scan_en),
	.SI(FE_OCPN253_result_4__1),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[2][2]  (.Q(\result[2] [2]),
	.D(n_171),
	.SE(scan_en),
	.SI(\result[2] [0]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX4 \A6M_result_reg[1][1]  (.Q(\result[1] [1]),
	.D(n_194),
	.SE(scan_en),
	.SI(\result[1] [0]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[5][3]  (.Q(\result[5] [3]),
	.D(n_177),
	.SE(scan_en),
	.SI(\result[5] [2]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[3][2]  (.Q(\result[3] [2]),
	.D(n_187),
	.SE(FE_OFN2_scan_en),
	.SI(\result[2] [3]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[3][0]  (.Q(\result[3] [0]),
	.D(n_168),
	.SE(FE_OFN2_scan_en),
	.SI(\result[3] [1]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[4][0]  (.Q(\result[4] [0]),
	.D(n_190),
	.SE(FE_OFN2_scan_en),
	.SI(\result[3] [4]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX4 \A6M_result_reg[0][1]  (.Q(\result[0] [1]),
	.D(n_166),
	.SE(scan_en),
	.SI(\A6M_activation_reg[5] [7]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[0][2]  (.Q(\result[0] [2]),
	.D(n_164),
	.SE(scan_en),
	.SI(\result[0] [1]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[0][3]  (.Q(\result[0] [3]),
	.D(n_195),
	.SE(scan_en),
	.SI(\result[0] [2]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[1][2]  (.Q(\result[1] [2]),
	.D(n_193),
	.SE(scan_en),
	.SI(\result[1] [1]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[1][3]  (.Q(\result[1] [3]),
	.D(n_191),
	.SE(scan_en),
	.SI(\result[1] [2]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[2][1]  (.Q(\result[2] [1]),
	.D(n_170),
	.SE(scan_en),
	.SI(\result[1] [3]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[0][4]  (.Q(\result[0] [4]),
	.D(n_176),
	.SE(scan_en),
	.SI(\result[1] [4]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX4 \A6M_result_reg[4][1]  (.Q(\result[4] [1]),
	.D(n_184),
	.SE(FE_OFN2_scan_en),
	.SI(\result[4] [0]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[4][3]  (.Q(\result[4] [3]),
	.D(n_181),
	.SE(scan_en),
	.SI(\result[4] [2]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX4 \A6M_result_reg[5][1]  (.Q(\result[5] [1]),
	.D(n_180),
	.SE(scan_en),
	.SI(\result[5] [0]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[5][2]  (.Q(\result[5] [2]),
	.D(n_179),
	.SE(scan_en),
	.SI(\A6M_activation_reg[0] [3]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[3][3]  (.Q(\result[3] [3]),
	.D(n_185),
	.SE(FE_OFN2_scan_en),
	.SI(\result[3] [0]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[1][4]  (.Q(\result[1] [4]),
	.D(n_175),
	.SE(scan_en),
	.SI(\result[2] [4]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[2][4]  (.Q(\result[2] [4]),
	.D(n_174),
	.SE(scan_en),
	.SI(OGF_R2),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[4][4]  (.Q(\result[4] [4]),
	.D(n_172),
	.SE(scan_en),
	.SI(\result[5] [1]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[5][4]  (.Q(\result[5] [4]),
	.D(n_189),
	.SE(scan_en),
	.SI(\A6M_activation_reg[0] [7]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_result_reg[3][1]  (.Q(\result[3] [1]),
	.D(n_188),
	.SE(FE_OFN2_scan_en),
	.SI(\result[3] [2]),
	.RN(n_251),
	.CK(clk));
   ADDHX1 g6881__6417 (.CO(n_204),
	.S(n_205),
	.A(AT6_sum_out[0]),
	.B(n_132));
   SDFFRHQX1 \A6M_cycle_counter_reg[3]  (.Q(A6M_cycle_counter[3]),
	.D(n_156),
	.SE(scan_en),
	.SI(OGF_R1),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_cycle_counter_reg[2]  (.Q(A6M_cycle_counter[2]),
	.D(n_157),
	.SE(scan_en),
	.SI(A6M_cycle_counter[0]),
	.RN(n_251),
	.CK(clk));
   AO22XL g6952__2398 (.Y(n_201),
	.A0(\weight[2] [3]),
	.A1(n_196),
	.B0(\result[2] [3]),
	.B1(n_199));
   AO22XL g6923__5107 (.Y(n_200),
	.A0(\weight[0] [0]),
	.A1(n_152),
	.B0(\result[0] [0]),
	.B1(n_199));
   AO22XL g6924__6260 (.Y(n_198),
	.A0(\weight[1] [0]),
	.A1(n_153),
	.B0(\result[1] [0]),
	.B1(n_199));
   AO22XL g6925__4319 (.Y(n_197),
	.A0(\weight[2] [0]),
	.A1(n_196),
	.B0(\result[2] [0]),
	.B1(n_199));
   OAI22X1 g6931__8428 (.Y(n_195),
	.A0(n_9),
	.A1(n_165),
	.B0(n_12),
	.B1(FE_OFN0_en));
   OAI22X1 g6932__5526 (.Y(n_194),
	.A0(n_6),
	.A1(n_192),
	.B0(n_16),
	.B1(FE_OFN0_en));
   OAI22X1 g6933__6783 (.Y(n_193),
	.A0(n_13),
	.A1(n_192),
	.B0(n_4),
	.B1(FE_OFN0_en));
   OAI22X1 g6934__3680 (.Y(n_191),
	.A0(n_8),
	.A1(n_192),
	.B0(n_7),
	.B1(FE_OFN0_en));
   AO22XL g6927__1617 (.Y(n_190),
	.A0(\weight[4] [0]),
	.A1(n_183),
	.B0(\result[4] [0]),
	.B1(n_199));
   MX2XL g6937__2802 (.Y(n_189),
	.A(\result[5] [4]),
	.B(n_149),
	.S0(FE_OFN0_en));
   AO22XL g6938__1705 (.Y(n_188),
	.A0(\weight[3] [1]),
	.A1(n_186),
	.B0(\result[3] [1]),
	.B1(n_199));
   AO22XL g6939__5122 (.Y(n_187),
	.A0(\weight[3] [2]),
	.A1(n_186),
	.B0(\result[3] [2]),
	.B1(n_199));
   AO22XL g6940__8246 (.Y(n_185),
	.A0(\weight[3] [3]),
	.A1(n_186),
	.B0(\result[3] [3]),
	.B1(n_199));
   AO22XL g6941__7098 (.Y(n_184),
	.A0(\weight[4] [1]),
	.A1(n_183),
	.B0(FE_OCPN253_result_4__1),
	.B1(n_199));
   AO22XL g6942__6131 (.Y(n_182),
	.A0(\weight[4] [2]),
	.A1(n_183),
	.B0(\result[4] [2]),
	.B1(n_199));
   AO22XL g6943__1881 (.Y(n_181),
	.A0(\weight[4] [3]),
	.A1(n_183),
	.B0(\result[4] [3]),
	.B1(n_199));
   AO22XL g6944__5115 (.Y(n_180),
	.A0(\weight[5] [1]),
	.A1(n_178),
	.B0(\result[5] [1]),
	.B1(n_199));
   AO22XL g6945__7482 (.Y(n_179),
	.A0(\weight[5] [2]),
	.A1(n_178),
	.B0(\result[5] [2]),
	.B1(n_199));
   AO22XL g6946__4733 (.Y(n_177),
	.A0(\weight[5] [3]),
	.A1(n_178),
	.B0(\result[5] [3]),
	.B1(n_199));
   MX2XL g6947__6161 (.Y(n_176),
	.A(\result[0] [4]),
	.B(n_148),
	.S0(FE_OFN0_en));
   MX2XL g6948__9315 (.Y(n_175),
	.A(\result[1] [4]),
	.B(n_147),
	.S0(FE_OFN0_en));
   MX2XL g6949__9945 (.Y(n_174),
	.A(\result[2] [4]),
	.B(n_141),
	.S0(FE_OFN0_en));
   MX2XL g6950__2883 (.Y(n_173),
	.A(\result[3] [4]),
	.B(n_144),
	.S0(FE_OFN0_en));
   MX2XL g6951__2346 (.Y(n_172),
	.A(\result[4] [4]),
	.B(n_142),
	.S0(FE_OFN0_en));
   OAI22X1 g6921__1666 (.Y(n_171),
	.A0(n_10),
	.A1(n_169),
	.B0(n_5),
	.B1(FE_OFN0_en));
   OAI22X1 g6922__7410 (.Y(n_170),
	.A0(n_14),
	.A1(n_169),
	.B0(FE_RN_33_0),
	.B1(FE_OFN0_en));
   AO22XL g6926__6417 (.Y(n_168),
	.A0(\weight[3] [0]),
	.A1(n_186),
	.B0(\result[3] [0]),
	.B1(n_199));
   AO22XL g6928__5477 (.Y(n_167),
	.A0(\weight[5] [0]),
	.A1(n_178),
	.B0(\result[5] [0]),
	.B1(n_199));
   OAI22X1 g6929__2398 (.Y(n_166),
	.A0(n_0),
	.A1(n_165),
	.B0(n_11),
	.B1(FE_OFN0_en));
   OAI22X1 g6930__5107 (.Y(n_164),
	.A0(n_2),
	.A1(n_165),
	.B0(n_15),
	.B1(FE_OFN0_en));
   ADDFHXL g6885__6260 (.CO(n_162),
	.S(n_163),
	.A(n_56),
	.B(n_96),
	.CI(n_134));
   SDFFQX1 \AT6_sum_out_reg[0]  (.Q(AT6_sum_out[0]),
	.D(n_137),
	.SE(FE_OFN2_scan_en),
	.SI(AT6_sum_out[1]),
	.CK(clk));
   OAI22X1 g6954__5526 (.Y(n_157),
	.A0(n_20),
	.A1(n_155),
	.B0(n_93),
	.B1(n_154));
   OAI22X1 g6955__6783 (.Y(n_156),
	.A0(n_94),
	.A1(n_155),
	.B0(n_91),
	.B1(n_154));
   INVXL g6956 (.Y(n_153),
	.A(n_192));
   INVXL g6957 (.Y(n_152),
	.A(n_165));
   INVXL g6964 (.Y(n_196),
	.A(n_169));
   NAND2BXL g6958__1617 (.Y(n_149),
	.AN(\weight[5] [4]),
	.B(FE_OFN15_n_139));
   NAND2BXL g6959__2802 (.Y(n_148),
	.AN(\weight[0] [4]),
	.B(FE_OFN13_n_145));
   NAND2BXL g6960__1705 (.Y(n_147),
	.AN(\weight[1] [4]),
	.B(FE_OFN19_n_146));
   NAND2X1 g6962__5122 (.Y(n_192),
	.A(FE_OFN0_en),
	.B(FE_OFN19_n_146));
   NAND2X1 g6963__8246 (.Y(n_165),
	.A(FE_OFN0_en),
	.B(FE_OFN13_n_145));
   AND2XL g6961__7098 (.Y(n_186),
	.A(FE_OFN0_en),
	.B(FE_OFN17_n_143));
   NAND2BXL g6966__6131 (.Y(n_144),
	.AN(\weight[3] [4]),
	.B(FE_OFN17_n_143));
   NAND2BXL g6967__1881 (.Y(n_142),
	.AN(\weight[4] [4]),
	.B(FE_OFN10_n_138));
   NAND2BXL g6965__5115 (.Y(n_141),
	.AN(\weight[2] [4]),
	.B(FE_OFN12_n_140));
   NAND2X1 g6971__7482 (.Y(n_169),
	.A(FE_OFN0_en),
	.B(FE_OFN12_n_140));
   AND2XL g6968__4733 (.Y(n_178),
	.A(FE_OFN0_en),
	.B(FE_OFN15_n_139));
   AND2XL g6969__6161 (.Y(n_183),
	.A(FE_OFN0_en),
	.B(FE_OFN10_n_138));
   SDFFRHQX4 A6M_en_reg (.Q(FE_OFN0_en),
	.D(n_129),
	.SE(FE_OFN2_scan_en),
	.SI(\A6M_activation_reg[4] [6]),
	.RN(n_251),
	.CK(clk));
   NOR2X1 g6902__9315 (.Y(n_137),
	.A(rst),
	.B(n_130));
   NOR2X1 g6975__9945 (.Y(n_155),
	.A(n_89),
	.B(n_128));
   OAI211X1 g6976__2883 (.Y(n_146),
	.A0(n_135),
	.A1(n_124),
	.B0(n_115),
	.C0(n_112));
   OAI211X1 g6979__2346 (.Y(n_145),
	.A0(n_136),
	.A1(n_126),
	.B0(n_110),
	.C0(n_122));
   OAI211X1 g6982__1666 (.Y(n_140),
	.A0(n_136),
	.A1(n_127),
	.B0(n_117),
	.C0(n_108));
   OAI211X1 g6981__7410 (.Y(n_143),
	.A0(n_135),
	.A1(n_98),
	.B0(n_121),
	.C0(n_99));
   OAI211X1 g6980__6417 (.Y(n_139),
	.A0(n_135),
	.A1(n_111),
	.B0(n_102),
	.C0(n_105));
   OAI211X1 g6983__5477 (.Y(n_138),
	.A0(n_136),
	.A1(n_97),
	.B0(n_100),
	.C0(n_101));
   SDFFRHQX1 \A6M_cycle_counter_reg[1]  (.Q(A6M_cycle_counter[1]),
	.D(n_90),
	.SE(scan_en),
	.SI(A6M_cycle_counter[2]),
	.RN(n_251),
	.CK(clk));
   XNOR2X1 g6953__6260 (.Y(n_130),
	.A(n_119),
	.B(n_118));
   OAI2BB1X1 g6984__4319 (.Y(n_129),
	.A0N(FE_OFN0_en),
	.A1N(n_92),
	.B0(n_87));
   AOI21XL g6985__8428 (.Y(n_128),
	.A0(A6M_cycle_counter[1]),
	.A1(A6M_cycle_counter[0]),
	.B0(n_154));
   SDFFRHQX1 \A6M_activation_reg_reg[4][2]  (.Q(\A6M_activation_reg[4] [2]),
	.D(n_67),
	.SE(scan_en),
	.SI(\A6M_activation_reg[3] [5]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[1][6]  (.Q(\A6M_activation_reg[1] [6]),
	.D(n_86),
	.SE(scan_en),
	.SI(\A6M_activation_reg[2] [2]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[4][5]  (.Q(\A6M_activation_reg[4] [5]),
	.D(n_64),
	.SE(scan_en),
	.SI(\A6M_activation_reg[4] [4]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[5][4]  (.Q(\A6M_activation_reg[5] [4]),
	.D(n_57),
	.SE(scan_en),
	.SI(\A6M_activation_reg[5] [2]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[2][6]  (.Q(\A6M_activation_reg[2] [6]),
	.D(n_31),
	.SE(scan_en),
	.SI(\A6M_activation_reg[2] [5]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[2][3]  (.Q(\A6M_activation_reg[2] [3]),
	.D(n_34),
	.SE(scan_en),
	.SI(\A6M_activation_reg[2] [6]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[5][2]  (.Q(\A6M_activation_reg[5] [2]),
	.D(n_58),
	.SE(scan_en),
	.SI(\A6M_activation_reg[5] [1]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[4][4]  (.Q(\A6M_activation_reg[4] [4]),
	.D(n_65),
	.SE(scan_en),
	.SI(\A6M_activation_reg[4] [0]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[0][2]  (.Q(\A6M_activation_reg[0] [2]),
	.D(n_48),
	.SE(scan_en),
	.SI(\A6M_activation_reg[0] [1]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[1][2]  (.Q(\A6M_activation_reg[1] [2]),
	.D(n_47),
	.SE(scan_en),
	.SI(\A6M_activation_reg[1] [0]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[3][0]  (.Q(\A6M_activation_reg[3] [0]),
	.D(n_77),
	.SE(scan_en),
	.SI(\A6M_activation_reg[3] [3]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[2][0]  (.Q(\A6M_activation_reg[2] [0]),
	.D(n_88),
	.SE(scan_en),
	.SI(\A6M_activation_reg[1] [6]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[1][7]  (.Q(\A6M_activation_reg[1] [7]),
	.D(n_38),
	.SE(scan_en),
	.SI(\A6M_activation_reg[1] [3]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[3][6]  (.Q(\A6M_activation_reg[3] [6]),
	.D(n_71),
	.SE(scan_en),
	.SI(\A6M_activation_reg[2] [4]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[3][2]  (.Q(\A6M_activation_reg[3] [2]),
	.D(n_75),
	.SE(scan_en),
	.SI(scan_in),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[5][7]  (.Q(\A6M_activation_reg[5] [7]),
	.D(n_51),
	.SE(scan_en),
	.SI(\A6M_activation_reg[5] [3]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[2][7]  (.Q(\A6M_activation_reg[2] [7]),
	.D(n_30),
	.SE(scan_en),
	.SI(\A6M_activation_reg[3] [0]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[3][1]  (.Q(\A6M_activation_reg[3] [1]),
	.D(n_76),
	.SE(FE_OFN2_scan_en),
	.SI(\A6M_activation_reg[4] [5]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[3][3]  (.Q(\A6M_activation_reg[3] [3]),
	.D(n_74),
	.SE(scan_en),
	.SI(\A6M_activation_reg[3] [2]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[3][4]  (.Q(\A6M_activation_reg[3] [4]),
	.D(n_73),
	.SE(scan_en),
	.SI(\A6M_activation_reg[3] [7]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[3][5]  (.Q(\A6M_activation_reg[3] [5]),
	.D(n_72),
	.SE(FE_OFN2_scan_en),
	.SI(\A6M_activation_reg[3] [1]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[3][7]  (.Q(\A6M_activation_reg[3] [7]),
	.D(n_70),
	.SE(scan_en),
	.SI(\A6M_activation_reg[3] [6]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[0][1]  (.Q(\A6M_activation_reg[0] [1]),
	.D(n_49),
	.SE(scan_en),
	.SI(\A6M_activation_reg[0] [4]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[4][1]  (.Q(\A6M_activation_reg[4] [1]),
	.D(n_68),
	.SE(scan_en),
	.SI(\A6M_activation_reg[3] [4]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[5][6]  (.Q(\A6M_activation_reg[5] [6]),
	.D(n_52),
	.SE(scan_en),
	.SI(\A6M_activation_reg[5] [5]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[4][3]  (.Q(\A6M_activation_reg[4] [3]),
	.D(n_66),
	.SE(FE_OFN2_scan_en),
	.SI(\A6M_activation_reg[4] [2]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[1][4]  (.Q(\A6M_activation_reg[1] [4]),
	.D(n_39),
	.SE(scan_en),
	.SI(\A6M_activation_reg[1] [1]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[4][6]  (.Q(\A6M_activation_reg[4] [6]),
	.D(n_63),
	.SE(FE_OFN2_scan_en),
	.SI(\A6M_activation_reg[4] [3]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[4][7]  (.Q(\A6M_activation_reg[4] [7]),
	.D(n_61),
	.SE(scan_en),
	.SI(A6M_cycle_counter[1]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[5][0]  (.Q(\A6M_activation_reg[5] [0]),
	.D(n_60),
	.SE(scan_en),
	.SI(\A6M_activation_reg[4] [7]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[5][1]  (.Q(\A6M_activation_reg[5] [1]),
	.D(n_59),
	.SE(scan_en),
	.SI(\A6M_activation_reg[5] [0]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[5][3]  (.Q(\A6M_activation_reg[5] [3]),
	.D(n_29),
	.SE(scan_en),
	.SI(\A6M_activation_reg[5] [6]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[5][5]  (.Q(\A6M_activation_reg[5] [5]),
	.D(n_53),
	.SE(scan_en),
	.SI(\A6M_activation_reg[5] [4]),
	.RN(n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[0][0]  (.Q(\A6M_activation_reg[0] [0]),
	.D(n_50),
	.SE(scan_en),
	.SI(\A6M_activation_reg[1] [7]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[1][5]  (.Q(\A6M_activation_reg[1] [5]),
	.D(n_40),
	.SE(scan_en),
	.SI(\A6M_activation_reg[1] [4]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[4][0]  (.Q(\A6M_activation_reg[4] [0]),
	.D(n_69),
	.SE(scan_en),
	.SI(\A6M_activation_reg[4] [1]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[0][3]  (.Q(\A6M_activation_reg[0] [3]),
	.D(n_43),
	.SE(scan_en),
	.SI(\A6M_activation_reg[0] [2]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[0][5]  (.Q(\A6M_activation_reg[0] [5]),
	.D(n_62),
	.SE(scan_en),
	.SI(\A6M_activation_reg[0] [0]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[0][6]  (.Q(\A6M_activation_reg[0] [6]),
	.D(n_46),
	.SE(scan_en),
	.SI(\result[5] [3]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[0][7]  (.Q(\A6M_activation_reg[0] [7]),
	.D(n_44),
	.SE(scan_en),
	.SI(\A6M_activation_reg[0] [6]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[2][5]  (.Q(\A6M_activation_reg[2] [5]),
	.D(n_32),
	.SE(scan_en),
	.SI(\A6M_activation_reg[2] [7]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[2][4]  (.Q(\A6M_activation_reg[2] [4]),
	.D(n_33),
	.SE(scan_en),
	.SI(\A6M_activation_reg[2] [1]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[2][2]  (.Q(\A6M_activation_reg[2] [2]),
	.D(n_35),
	.SE(scan_en),
	.SI(\A6M_activation_reg[2] [3]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[0][4]  (.Q(\A6M_activation_reg[0] [4]),
	.D(n_45),
	.SE(scan_en),
	.SI(\A6M_activation_reg[0] [5]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[2][1]  (.Q(\A6M_activation_reg[2] [1]),
	.D(n_36),
	.SE(scan_en),
	.SI(\A6M_activation_reg[2] [0]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[1][3]  (.Q(\A6M_activation_reg[1] [3]),
	.D(n_37),
	.SE(scan_en),
	.SI(\A6M_activation_reg[1] [2]),
	.RN(FE_OFN8_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[1][1]  (.Q(\A6M_activation_reg[1] [1]),
	.D(n_41),
	.SE(scan_en),
	.SI(AT6_sum_out[3]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   SDFFRHQX1 \A6M_activation_reg_reg[1][0]  (.Q(\A6M_activation_reg[1] [0]),
	.D(n_42),
	.SE(scan_en),
	.SI(\A6M_activation_reg[1] [5]),
	.RN(FE_OFN9_n_251),
	.CK(clk));
   AOI221X1 g7037__5526 (.Y(n_127),
	.A0(\A6M_activation_reg[2] [1]),
	.A1(FE_OFN6_n_123),
	.B0(\A6M_activation_reg[2] [4]),
	.B1(FE_OFN7_n_125),
	.C0(n_81));
   AOI221X1 g7038__6783 (.Y(n_126),
	.A0(\A6M_activation_reg[0] [5]),
	.A1(FE_OFN5_n_83),
	.B0(\A6M_activation_reg[0] [4]),
	.B1(FE_OFN7_n_125),
	.C0(n_85));
   AOI221X1 g7039__3680 (.Y(n_124),
	.A0(\A6M_activation_reg[1] [3]),
	.A1(FE_OFN6_n_123),
	.B0(\A6M_activation_reg[1] [6]),
	.B1(FE_OFN7_n_125),
	.C0(n_84));
   AOI22X1 g7032__1617 (.Y(n_122),
	.A0(\A6M_activation_reg[0] [7]),
	.A1(n_107),
	.B0(\A6M_activation_reg[0] [3]),
	.B1(n_116));
   AOI22X1 g7028__2802 (.Y(n_121),
	.A0(\A6M_activation_reg[3] [4]),
	.A1(n_114),
	.B0(\A6M_activation_reg[3] [0]),
	.B1(n_113));
   AND2XL g6970__1705 (.Y(n_120),
	.A(n_119),
	.B(n_118));
   AOI22X1 g7029__5122 (.Y(n_117),
	.A0(\A6M_activation_reg[2] [3]),
	.A1(n_116),
	.B0(\A6M_activation_reg[2] [2]),
	.B1(n_109));
   AOI22X1 g7031__8246 (.Y(n_115),
	.A0(\A6M_activation_reg[1] [4]),
	.A1(n_114),
	.B0(\A6M_activation_reg[1] [0]),
	.B1(n_113));
   AOI22X1 g7030__7098 (.Y(n_112),
	.A0(\A6M_activation_reg[1] [5]),
	.A1(n_104),
	.B0(\A6M_activation_reg[1] [1]),
	.B1(n_103));
   AOI221X1 g7034__6131 (.Y(n_111),
	.A0(\A6M_activation_reg[5] [3]),
	.A1(FE_OFN6_n_123),
	.B0(\A6M_activation_reg[5] [6]),
	.B1(FE_OFN7_n_125),
	.C0(n_78));
   AOI22X1 g7033__1881 (.Y(n_110),
	.A0(\A6M_activation_reg[0] [6]),
	.A1(n_106),
	.B0(\A6M_activation_reg[0] [2]),
	.B1(n_109));
   AOI22X1 g7022__5115 (.Y(n_108),
	.A0(\A6M_activation_reg[2] [7]),
	.A1(n_107),
	.B0(\A6M_activation_reg[2] [6]),
	.B1(n_106));
   AOI22X1 g7023__7482 (.Y(n_105),
	.A0(\A6M_activation_reg[5] [5]),
	.A1(n_104),
	.B0(\A6M_activation_reg[5] [1]),
	.B1(n_103));
   AOI22X1 g7024__4733 (.Y(n_102),
	.A0(\A6M_activation_reg[5] [4]),
	.A1(n_114),
	.B0(\A6M_activation_reg[5] [0]),
	.B1(n_113));
   AOI22X1 g7025__6161 (.Y(n_101),
	.A0(\A6M_activation_reg[4] [7]),
	.A1(n_107),
	.B0(\A6M_activation_reg[4] [3]),
	.B1(n_116));
   AOI22X1 g7026__9315 (.Y(n_100),
	.A0(\A6M_activation_reg[4] [6]),
	.A1(n_106),
	.B0(\A6M_activation_reg[4] [2]),
	.B1(n_109));
   AOI22X1 g7027__9945 (.Y(n_99),
	.A0(\A6M_activation_reg[3] [5]),
	.A1(n_104),
	.B0(\A6M_activation_reg[3] [1]),
	.B1(n_103));
   AOI221X1 g7036__2883 (.Y(n_98),
	.A0(\A6M_activation_reg[3] [3]),
	.A1(FE_OFN6_n_123),
	.B0(\A6M_activation_reg[3] [6]),
	.B1(FE_OFN7_n_125),
	.C0(n_80));
   AOI221X1 g7035__2346 (.Y(n_97),
	.A0(\A6M_activation_reg[4] [1]),
	.A1(FE_OFN6_n_123),
	.B0(\A6M_activation_reg[4] [4]),
	.B1(FE_OFN7_n_125),
	.C0(n_79));
   SDFFRHQX1 \A6M_cycle_counter_reg[0]  (.Q(A6M_cycle_counter[0]),
	.D(n_25),
	.SE(scan_en),
	.SI(\result[0] [4]),
	.RN(n_251),
	.CK(clk));
   OAI21X1 g7054__7410 (.Y(n_154),
	.A0(n_94),
	.A1(n_93),
	.B0(FE_OFN0_en));
   NAND3BXL g7086__6417 (.Y(n_92),
	.AN(n_93),
	.B(1'b1),
	.C(A6M_cycle_counter[3]));
   INVXL g7120 (.Y(n_91),
	.A(n_113));
   AO22XL g6986__5477 (.Y(n_90),
	.A0(FE_OFN0_en),
	.A1(n_21),
	.B0(n_89),
	.B1(A6M_cycle_counter[1]));
   XNOR2X1 g6987__2398 (.Y(n_118),
	.A(n_55),
	.B(n_54));
   MX2XL g7089__5107 (.Y(n_88),
	.A(\activation[2] [0]),
	.B(\A6M_activation_reg[2] [0]),
	.S0(n_87));
   MX2XL g7059__6260 (.Y(n_86),
	.A(\activation[1] [6]),
	.B(\A6M_activation_reg[1] [6]),
	.S0(n_87));
   AO22XL g7060__4319 (.Y(n_85),
	.A0(\A6M_activation_reg[0] [1]),
	.A1(FE_OFN6_n_123),
	.B0(\A6M_activation_reg[0] [0]),
	.B1(FE_OFN4_n_82));
   AO22XL g7061__8428 (.Y(n_84),
	.A0(\A6M_activation_reg[1] [7]),
	.A1(FE_OFN5_n_83),
	.B0(\A6M_activation_reg[1] [2]),
	.B1(FE_OFN4_n_82));
   AO22XL g7062__5526 (.Y(n_81),
	.A0(\A6M_activation_reg[2] [5]),
	.A1(FE_OFN5_n_83),
	.B0(\A6M_activation_reg[2] [0]),
	.B1(FE_OFN4_n_82));
   AO22XL g7063__6783 (.Y(n_80),
	.A0(\A6M_activation_reg[3] [7]),
	.A1(FE_OFN5_n_83),
	.B0(\A6M_activation_reg[3] [2]),
	.B1(FE_OFN4_n_82));
   AO22XL g7064__3680 (.Y(n_79),
	.A0(\A6M_activation_reg[4] [5]),
	.A1(FE_OFN5_n_83),
	.B0(\A6M_activation_reg[4] [0]),
	.B1(FE_OFN4_n_82));
   AO22XL g7065__1617 (.Y(n_78),
	.A0(\A6M_activation_reg[5] [7]),
	.A1(FE_OFN5_n_83),
	.B0(\A6M_activation_reg[5] [2]),
	.B1(FE_OFN4_n_82));
   MX2XL g7066__2802 (.Y(n_77),
	.A(\activation[3] [0]),
	.B(\A6M_activation_reg[3] [0]),
	.S0(n_87));
   MX2XL g7067__1705 (.Y(n_76),
	.A(\activation[3] [1]),
	.B(\A6M_activation_reg[3] [1]),
	.S0(n_87));
   MX2XL g7068__5122 (.Y(n_75),
	.A(\activation[3] [2]),
	.B(\A6M_activation_reg[3] [2]),
	.S0(n_87));
   MX2XL g7069__8246 (.Y(n_74),
	.A(\activation[3] [3]),
	.B(\A6M_activation_reg[3] [3]),
	.S0(n_87));
   MX2XL g7070__7098 (.Y(n_73),
	.A(\activation[3] [4]),
	.B(\A6M_activation_reg[3] [4]),
	.S0(n_87));
   MX2XL g7071__6131 (.Y(n_72),
	.A(\activation[3] [5]),
	.B(\A6M_activation_reg[3] [5]),
	.S0(n_87));
   MX2XL g7072__1881 (.Y(n_71),
	.A(\activation[3] [6]),
	.B(\A6M_activation_reg[3] [6]),
	.S0(n_87));
   MX2XL g7073__5115 (.Y(n_70),
	.A(\activation[3] [7]),
	.B(\A6M_activation_reg[3] [7]),
	.S0(n_87));
   MX2XL g7074__7482 (.Y(n_69),
	.A(\activation[4] [0]),
	.B(\A6M_activation_reg[4] [0]),
	.S0(n_87));
   MX2XL g7075__4733 (.Y(n_68),
	.A(\activation[4] [1]),
	.B(\A6M_activation_reg[4] [1]),
	.S0(n_87));
   MX2XL g7076__6161 (.Y(n_67),
	.A(\activation[4] [2]),
	.B(\A6M_activation_reg[4] [2]),
	.S0(n_87));
   MX2XL g7077__9315 (.Y(n_66),
	.A(\activation[4] [3]),
	.B(\A6M_activation_reg[4] [3]),
	.S0(n_87));
   MX2XL g7078__9945 (.Y(n_65),
	.A(\activation[4] [4]),
	.B(\A6M_activation_reg[4] [4]),
	.S0(n_87));
   MX2XL g7079__2883 (.Y(n_64),
	.A(\activation[4] [5]),
	.B(\A6M_activation_reg[4] [5]),
	.S0(n_87));
   MX2XL g7080__2346 (.Y(n_63),
	.A(\activation[4] [6]),
	.B(\A6M_activation_reg[4] [6]),
	.S0(n_87));
   MX2XL g7081__1666 (.Y(n_62),
	.A(\activation[0] [5]),
	.B(\A6M_activation_reg[0] [5]),
	.S0(n_87));
   MX2XL g7082__7410 (.Y(n_61),
	.A(\activation[4] [7]),
	.B(\A6M_activation_reg[4] [7]),
	.S0(n_87));
   MX2XL g7083__6417 (.Y(n_60),
	.A(\activation[5] [0]),
	.B(\A6M_activation_reg[5] [0]),
	.S0(n_87));
   MX2XL g7084__5477 (.Y(n_59),
	.A(\activation[5] [1]),
	.B(\A6M_activation_reg[5] [1]),
	.S0(n_87));
   MX2XL g7085__2398 (.Y(n_58),
	.A(\activation[5] [2]),
	.B(\A6M_activation_reg[5] [2]),
	.S0(n_87));
   MX2XL g7088__5107 (.Y(n_57),
	.A(\activation[5] [4]),
	.B(\A6M_activation_reg[5] [4]),
	.S0(n_87));
   MX2XL g7090__4319 (.Y(n_53),
	.A(\activation[5] [5]),
	.B(\A6M_activation_reg[5] [5]),
	.S0(n_87));
   MX2XL g7091__8428 (.Y(n_52),
	.A(\activation[5] [6]),
	.B(\A6M_activation_reg[5] [6]),
	.S0(n_87));
   MX2XL g7092__5526 (.Y(n_51),
	.A(\activation[5] [7]),
	.B(\A6M_activation_reg[5] [7]),
	.S0(n_87));
   MX2XL g7093__6783 (.Y(n_50),
	.A(\activation[0] [0]),
	.B(\A6M_activation_reg[0] [0]),
	.S0(n_87));
   MX2XL g7094__3680 (.Y(n_49),
	.A(\activation[0] [1]),
	.B(\A6M_activation_reg[0] [1]),
	.S0(n_87));
   MX2XL g7095__1617 (.Y(n_48),
	.A(\activation[0] [2]),
	.B(\A6M_activation_reg[0] [2]),
	.S0(n_87));
   MX2XL g7096__2802 (.Y(n_47),
	.A(\activation[1] [2]),
	.B(\A6M_activation_reg[1] [2]),
	.S0(n_87));
   MX2XL g7097__1705 (.Y(n_46),
	.A(\activation[0] [6]),
	.B(\A6M_activation_reg[0] [6]),
	.S0(n_87));
   MX2XL g7098__5122 (.Y(n_45),
	.A(\activation[0] [4]),
	.B(\A6M_activation_reg[0] [4]),
	.S0(n_87));
   MX2XL g7099__8246 (.Y(n_44),
	.A(\activation[0] [7]),
	.B(\A6M_activation_reg[0] [7]),
	.S0(n_87));
   MX2XL g7100__7098 (.Y(n_43),
	.A(\activation[0] [3]),
	.B(\A6M_activation_reg[0] [3]),
	.S0(n_87));
   MX2XL g7101__6131 (.Y(n_42),
	.A(\activation[1] [0]),
	.B(\A6M_activation_reg[1] [0]),
	.S0(n_87));
   MX2XL g7102__1881 (.Y(n_41),
	.A(\activation[1] [1]),
	.B(\A6M_activation_reg[1] [1]),
	.S0(n_87));
   MX2XL g7103__5115 (.Y(n_40),
	.A(\activation[1] [5]),
	.B(\A6M_activation_reg[1] [5]),
	.S0(n_87));
   MX2XL g7104__7482 (.Y(n_39),
	.A(\activation[1] [4]),
	.B(\A6M_activation_reg[1] [4]),
	.S0(n_87));
   MX2XL g7105__4733 (.Y(n_38),
	.A(\activation[1] [7]),
	.B(\A6M_activation_reg[1] [7]),
	.S0(n_87));
   MX2XL g7106__6161 (.Y(n_37),
	.A(\activation[1] [3]),
	.B(\A6M_activation_reg[1] [3]),
	.S0(n_87));
   MX2XL g7107__9315 (.Y(n_36),
	.A(\activation[2] [1]),
	.B(\A6M_activation_reg[2] [1]),
	.S0(n_87));
   MX2XL g7108__9945 (.Y(n_35),
	.A(\activation[2] [2]),
	.B(\A6M_activation_reg[2] [2]),
	.S0(n_87));
   MX2XL g7109__2883 (.Y(n_34),
	.A(\activation[2] [3]),
	.B(\A6M_activation_reg[2] [3]),
	.S0(n_87));
   MX2XL g7110__2346 (.Y(n_33),
	.A(\activation[2] [4]),
	.B(\A6M_activation_reg[2] [4]),
	.S0(n_87));
   MX2XL g7111__1666 (.Y(n_32),
	.A(\activation[2] [5]),
	.B(\A6M_activation_reg[2] [5]),
	.S0(n_87));
   MX2XL g7112__7410 (.Y(n_31),
	.A(\activation[2] [6]),
	.B(\A6M_activation_reg[2] [6]),
	.S0(n_87));
   MX2XL g7113__6417 (.Y(n_30),
	.A(\activation[2] [7]),
	.B(\A6M_activation_reg[2] [7]),
	.S0(n_87));
   MX2XL g7114__5477 (.Y(n_29),
	.A(\activation[5] [3]),
	.B(\A6M_activation_reg[5] [3]),
	.S0(n_87));
   NOR2X1 g7119__2398 (.Y(n_109),
	.A(n_26),
	.B(n_135));
   NOR2X1 g7123__5107 (.Y(n_114),
	.A(n_136),
	.B(n_27));
   NOR2X1 g7124__6260 (.Y(n_103),
	.A(n_136),
	.B(n_28));
   NOR2X1 g7125__4319 (.Y(n_116),
	.A(n_28),
	.B(n_135));
   NOR2X1 g7115__8428 (.Y(n_106),
	.A(n_135),
	.B(n_27));
   NOR2X1 g7126__5526 (.Y(n_113),
	.A(n_26),
	.B(n_136));
   MX2XL g7087__6783 (.Y(n_25),
	.A(FE_OFN0_en),
	.B(n_89),
	.S0(A6M_cycle_counter[0]));
   NOR2X1 g7116__3680 (.Y(n_107),
	.A(n_135),
	.B(n_24));
   NAND2X1 g7117__1617 (.Y(n_93),
	.A(A6M_cycle_counter[1]),
	.B(FE_OFN7_n_125));
   NOR2X1 g7118__2802 (.Y(n_104),
	.A(n_136),
	.B(n_24));
   OAI22XL g7121__8246 (.Y(n_21),
	.A0(A6M_cycle_counter[1]),
	.A1(n_19),
	.B0(A6M_cycle_counter[0]),
	.B1(n_18));
   INVX1 g7128 (.Y(n_28),
	.A(FE_OFN6_n_123));
   INVX1 g7127 (.Y(n_26),
	.A(FE_OFN4_n_82));
   INVX1 g7134 (.Y(n_27),
	.A(FE_OFN7_n_125));
   XNOR2X1 g7122__7098 (.Y(n_54),
	.A(\result[0] [0]),
	.B(\result[1] [0]));
   NOR2X1 g7131__6131 (.Y(n_82),
	.A(n_20),
	.B(n_19));
   NAND2X2 g7130__1881 (.Y(n_136),
	.A(A6M_cycle_counter[1]),
	.B(n_94));
   NOR2X1 g7132__5115 (.Y(n_123),
	.A(A6M_cycle_counter[0]),
	.B(n_20));
   INVX1 g7133 (.Y(n_24),
	.A(FE_OFN5_n_83));
   NAND2X2 g7136__7482 (.Y(n_135),
	.A(n_18),
	.B(n_94));
   NOR2X1 g7138__4733 (.Y(n_125),
	.A(A6M_cycle_counter[2]),
	.B(n_19));
   OR2X6 g7139__6161 (.Y(n_87),
	.A(n_3),
	.B(FE_OFN0_en));
   NOR2X1 g7129__9315 (.Y(n_89),
	.A(start),
	.B(FE_OFN0_en));
   CLKAND2X2 g7135__9945 (.Y(n_17),
	.A(\result[0] [0]),
	.B(\result[1] [0]));
   NOR2X1 g7137__2883 (.Y(n_83),
	.A(A6M_cycle_counter[0]),
	.B(A6M_cycle_counter[2]));
   INVXL g7148 (.Y(n_16),
	.A(\result[1] [1]));
   INVXL g7146 (.Y(n_15),
	.A(\result[0] [2]));
   INVX1 g7156 (.Y(n_14),
	.A(\weight[2] [1]));
   INVX1 g7140 (.Y(n_13),
	.A(\weight[1] [2]));
   INVXL g7160 (.Y(n_12),
	.A(\result[0] [3]));
   INVXL g7161 (.Y(n_11),
	.A(\result[0] [1]));
   INVX1 g7154 (.Y(n_10),
	.A(\weight[2] [2]));
   INVX1 g7141 (.Y(n_9),
	.A(\weight[0] [3]));
   INVX1 g7150 (.Y(n_19),
	.A(A6M_cycle_counter[0]));
   INVX1 g7158 (.Y(n_20),
	.A(A6M_cycle_counter[2]));
   INVX1 g7159 (.Y(n_94),
	.A(A6M_cycle_counter[3]));
   INVX1 g7153 (.Y(n_8),
	.A(\weight[1] [3]));
   INVXL g7147 (.Y(n_7),
	.A(\result[1] [3]));
   INVX1 g7142 (.Y(n_6),
	.A(\weight[1] [1]));
   INVXL g7144 (.Y(n_5),
	.A(\result[2] [2]));
   INVXL g7149 (.Y(n_4),
	.A(\result[1] [2]));
   INVX1 g7157 (.Y(n_3),
	.A(start));
   INVX1 g7155 (.Y(n_2),
	.A(\weight[0] [2]));
   INVX1 g7143 (.Y(n_0),
	.A(\weight[0] [1]));
   INVX1 g7162 (.Y(n_18),
	.A(A6M_cycle_counter[1]));
   INVX2 g7151 (.Y(n_199),
	.A(FE_OFN0_en));
   CLKINVX6 g7152 (.Y(n_251),
	.A(rst));
endmodule

