create_constraint_mode -name default_emulate_constraint_mode -sdc_files [list /dev/null]
create_rc_corner -name default_emulate_rc_corner 
create_rc_corner -name default_emulate_early_rc_corner 
create_rc_corner -name default_emulate_late_rc_corner 
create_library_set -name default_emulate_libset_max -timing [list /eda/cadence/pdks/ihp_sg13g2/ixc013g2ng_stdcell/lib/ixc013g2ng_stdcell_slow_1p08V_125C.lib /eda/cadence/pdks/ihp_sg13g2/ixc013g2ng_stdcell/lib/ixc013g2ng_stdcell_fast_1p32V_m40C.lib ../../../../../IHP-Open-PDK/ihp-sg13g2/libs.ref/sg13g2_io/lib/sg13g2_io_slow_1p08V_3p0V_125C.lib ../../../../../IHP-Open-PDK/ihp-sg13g2/libs.ref/sg13g2_io/lib/sg13g2_io_fast_1p32V_3p6V_m40C.lib ../../../../../IHP-Open-PDK/ihp-sg13g2/libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_1024x8_c2_bm_bist_slow_1p08V_125C.lib ../../../../../IHP-Open-PDK/ihp-sg13g2/libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_1024x8_c2_bm_bist_fast_1p32V_m55C.lib]
create_library_set -name default_emulate_libset_min -timing [list /eda/cadence/pdks/ihp_sg13g2/ixc013g2ng_stdcell/lib/ixc013g2ng_stdcell_slow_1p08V_125C.lib /eda/cadence/pdks/ihp_sg13g2/ixc013g2ng_stdcell/lib/ixc013g2ng_stdcell_fast_1p32V_m40C.lib ../../../../../IHP-Open-PDK/ihp-sg13g2/libs.ref/sg13g2_io/lib/sg13g2_io_slow_1p08V_3p0V_125C.lib ../../../../../IHP-Open-PDK/ihp-sg13g2/libs.ref/sg13g2_io/lib/sg13g2_io_fast_1p32V_3p6V_m40C.lib ../../../../../IHP-Open-PDK/ihp-sg13g2/libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_1024x8_c2_bm_bist_slow_1p08V_125C.lib ../../../../../IHP-Open-PDK/ihp-sg13g2/libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_1024x8_c2_bm_bist_fast_1p32V_m55C.lib]
create_delay_corner -name default_emulate_delay_corner -early_library_set default_emulate_libset_min -late_library_set default_emulate_libset_max -rc_corner default_emulate_rc_corner
create_delay_corner -name default_emulate_delay_corner_max -library_set default_emulate_libset_max -rc_corner default_emulate_rc_corner
create_delay_corner -name default_emulate_delay_corner_min -library_set default_emulate_libset_min -rc_corner default_emulate_rc_corner
create_analysis_view -name default_emulate_view -constraint_mode default_emulate_constraint_mode -delay_corner default_emulate_delay_corner
set_analysis_view -setup default_emulate_view -hold default_emulate_view
